### ISSUE TITLE
 Crewai not picking up packages in vscode but still runs fine. 

### ISSUE THREAD

**Issue by MadMaxDP** [crewAIInc/crewAI#1000]
I am using VScode and poetry to biuld a crew using the "crewai create {crew name}" command. Everything works well and the crew works fine but, VScode shows the crewai package as missing in the codes. Is this a common issue, tried it on two separate windows PCs and have the same issue. This is not stopping anything from working just down't understand why it is doing this? If I use VScode and crewai through pip, I do not get this issue.

![1](https://github.com/user-attachments/assets/af89b3e4-07f0-405b-9f9d-ba3e3dc15fd7)

**Comment by gadgethome** [comment]
Try doing poetry shell, copy the env, then go to Enter Interpreter Path and paste it here.  Thanks
