### ISSUE TITLE
The input to this tool should be the coworker, the question you have for them, and ALL necessary context to ask the question properly, they know nothing about the question, so share absolute everything you know, don't reference things but instead explain them.

### ISSUE THREAD

**Issue by pradeepdev-1995** [crewAIInc/crewAI#1010]
I am using 4 agents where 3 are sub-agents(where allow_delegation=false) and one is the manager(where allow_delegation=true). There is no tools I am using in my agentic workflow. But while crew execution I am ettin this message -

```The input to this tool should be the coworker, the question you have for them, and ALL necessary context to ask the question properly, they know nothing about the question, so share absolute everything you know, don't reference things but instead explain them```

**Comment by lorenzejay** [comment]
can you show the code you used to run this ?

are you also using `Process.hierarchical`?

**Comment by pradeepdev-1995** [comment]
@lorenzejay Yes I am using ```Process.hierarchical```

**Comment by cl955** [comment]
I started to see this issue today, how did you fix this?
