### ISSUE TITLE
load_tools(["human"]) Probem in 0.36.1

### ISSUE THREAD

**Issue by probao** [crewAIInc/crewAI#1055]
When I use it in 0.36.1, I may find an error "I encountered an error while trying to use the tool. This was the error: HumanInputRun._run() got an unexpected keyword argument 'guess'.
 Tool human accepts these inputs: You can ask a human for guidance when you think you got stuck or you are not sure what to do next. The input should be a question for the human." 

but when I use it in crewai=="0.30.0rc3" it runs well. Please fix the bug in 0.36.1

from langchain.agents import load_tools
human_tools = load_tools(["human"])

**Comment by theCyberTech** [comment]
Hi please upgrade to version 0.41.1

**Comment by probao** [comment]
Thanks I will try it
