### ISSUE TITLE
i have a Issue with WebsiteSearchTool: Embedding Dimension Mismatch

### ISSUE THREAD

**Issue by Jasonk0825** [crewAIInc/crewAI#1058]
I'm encountering an error while trying to use the WebsiteSearchTool with Gemini Pro as the LLM. The error message is:

"Embedding dimension 768 does not match collection dimensionality 1536. This is commonly a side-effect when an embedding function, different from the one used to add the embeddings, is used to retrieve an embedding from the database."

To resolve this, I tried changing the embedding model to "models/text-embedding-004", but the same error persists. Here's my current configuration:

```python
web_rag_tool = WebsiteSearchTool(
    config=dict(
        llm=dict(
            provider="google",
            config=dict(
                model="gemini-pro",
                temperature=0.7,
            ),
        ),
    )
)
        embedder=dict(
            provider="google",
            config=dict(
                model="models/text-embedding-004",
                task_type="retrieval_document",
            ),
        ),
    )
)
```

I'm unsure why the error mentions 768 dimensions when I'm using "models/text-embedding-004", which should produce 1024-dimensional embeddings.

Questions:

Is there a compatibility issue between Gemini Pro and the current embedding setup in WebsiteSearchTool?
Are there any known issues or additional configurations needed when using Google's embedding models with this tool?
How can I ensure that the correct embedding model is being used and properly recognized by the tool?
Any guidance on resolving this dimension mismatch would be greatly appreciated. Thank you!

**Comment by Jatayu-u** [comment]
Hey @Jasonk0825, I am facing a similar issue. Did you get a solution for this?

**Comment by brukted** [comment]
+1

**Comment by guilegarcia** [comment]
+1

**Comment by BrunoVDM** [comment]
+1

**Comment by pedrosimao** [comment]
I am having the same issue with google embeddings. The issue should not be closed.
Error message:
`ERROR:root:Error during short_term search: Embedding dimension 768 does not match collection dimensionality 1536`
