### ISSUE TITLE
JSONSearchTool Import Path Issue in crewai-tools [BUG]

### ISSUE THREAD

**Issue by nickzren** [crewAIInc/crewAI#1159]
**Description**
I encountered an issue while trying to use the `JSONSearchTool` based on the instructions provided in the CrewAI documentation (https://docs.crewai.com/tools/JSONSearchTool/). The documented import path does not work.

**Steps to Reproduce**
1. Install `crewai` and `crewai-tools` in a conda environment with Python 3.10.
2. Attempt to import `JSONSearchTool` using the following statement:
   ```python
   from crewai.json_tools import JSONSearchTool
   ```

**Expected behavior**
The import should work as documented.

**Environment Details:**
- **Operating System**: macOS
- **Python Version**: 3.10
- **crewAI Version**: 0.41.1
- **crewAI Tools Version**: 0.4.26

**Logs**
Include relevant logs or error messages if applicable:
```
ModuleNotFoundError: No module named 'crewai.json_tools'
```

**Possible Solution**
Update the documentation to reflect the correct import path or adjust the package structure so that the documented import path works correctly.

**Additional context**
None

**Comment by nickzren** [comment]
I found that the import works with the following path instead:
```python
from crewai_tools.tools.json_search_tool.json_search_tool import JSONSearchTool
```

It could just update the documentation to reflect the correct import path or adjust the package structure so that the documented import path works correctly.

**Comment by theCyberTech** [comment]
Hi, The docs need to be updated for this, thanks for pointing this out.

The correct way to import the tools is by doing the following

```from crewai_tools import JSONSearchTool```

Also I would recommend using the cli command to generate your crews, this way all you base imports are already setup

From the cli run:
```crewai create```

https://docs.crewai.com/getting-started/Start-a-New-CrewAI-Project-Template-Method/
