### ISSUE TITLE
[BUG] Documentation shows unreleased features

### ISSUE THREAD

**Issue by zinyando** [crewAIInc/crewAI#1160]
**Description**

The current setup has documentation updates that are deployed instantly even for features that have not been released.

Since everything is merged in `main` when it's ready, we get to a state where documentation is out of sync with features in the current version.

Deploying the doc site for tags only would fix this versus deploying from the `main` branch.

**Steps to Reproduce**

Visiting [Running Your Project](https://docs.crewai.com/getting-started/Start-a-New-CrewAI-Project-Template-Method/#running-your-project) shows `crewai run` command that is not available in v0.41,1

**Expected behavior**

Only released features should be on the documentation site

**Possible Solution**

Either deploy the docs from the latest tag or we have versioned docs

**Comment by theCyberTech** [comment]
Thanks for raising @zinyando,

This has been addressed in #1212 

New version dropping soon so Docs will stay as they are for now
