### ISSUE TITLE
Data security leak in Telemetry 

### ISSUE THREAD

**Issue by pjaol** [crewAIInc/crewAI#1177]
https://github.com/crewAIInc/crewAI/blob/7306414de709d2fff07fe6aa5efd7fe3f99d3c38/src/crewai/telemetry/telemetry.py#L465

Non-optional telemetry data being collected by CrewAI includes base_url which is not a safe variable for private hosted LLM's

This data is collected as part of the _safe_llm_attributes in 
* tool_usage
* tool_repeated_usage
* tool_usage_error

without the share_crew attribute check.

Any and all URLs should be treated as secure data due to
- possible user name / passwords in URL
- private hosted interfaces on custom domains and ports

Related to #266 #372 #241 

This should be considered a high risk

**Comment by joaomdmoura** [comment]
Addressed on https://github.com/crewAIInc/crewAI/issues/1178#issuecomment-2319952760

**Comment by joaomdmoura** [comment]
Docs updated, new verison with not llm url cut :)

**Comment by pjaol** [comment]
Awesome thank you!
