### ISSUE TITLE
[BUG] Crew creation error when langgraph is installed 

### ISSUE THREAD

**Issue by jereesh** [crewAIInc/crewAI#1186]
**Description**
Created an app with Crew AI and tools , working fine , But when I installed Langgraph Crew creation failed

**Steps to Reproduce**
Install langgraph 0.2.3 to an existing crew ai app, try to create a Crew, error occurs

**Expected behavior**
Langgraph and Crew AI should work together if I need to create an App by using both

**Screenshots/Code snippets**
crew = Crew(
            agents = agents,
            tasks = tasks,
            process = Process.sequential,
            full_output = True,
            verbose = 2
        )
**Environment Details:**
- **Operating System**: Ubuntu 22.04.4 LTS
- **Python Version**: 3.10
- **crewAI Version**:  0.51.1

- **crewAI Tools Version**:0.8.3

**Logs**
-xSjLma3a/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Crew
verbose
  Input should be a valid boolean, unable to interpret input [type=bool_parsing, input_value=2, input_type=int]
    For further information visit https://errors.pydantic.dev/2.8/v/bool_parsing

**Possible Solution**
I have tried downgrading langchain and langchain-core version with that of the working app but no luck

**Additional context**
pydantic version in both working and errored app is as below
pydantic                                 2.8.2
pydantic_core                            2.20.1

**Comment by theCyberTech** [comment]
You need to set verbose to 1 or 2 on your crew not True /False
