### ISSUE TITLE
[BUG] Latest langchain-core 0.2.31 release breaks Crew execution w Agent

### ISSUE THREAD

**Issue by andrewpap22** [crewAIInc/crewAI#1191]
**Description**
Provide a clear and concise description of what the bug is.

ImportError: cannot import name 'ToolsRenderer' from 'langchain_core.tools'

    This specific error message means that the code is trying to import ToolsRenderer from the langchain_core.tools module, but it can't find ToolsRenderer in that module the reason is that in their latest release of 0.2.31 they removed the ToolsRendered from `libs/langchain/langchain/tools/render.py` 

**Steps to Reproduce**
Provide a step-by-step process to reproduce the behavior:

Use Python version >= 3.11 and upgrade, crewai[tools], langchain-community, langchain-core packages to latest versions and simply run a Crew execution (you need to be importing somewhere in your app usage an Agent from Crewai -->     from crewai import Agent) and you'll get: 

```md
from langchain.tools.render import render_text_description
  File "/foo/bar/buzz/venv/lib/python3.11/site-packages/langchain/tools/render.py", line 9, in <module>
    from langchain_core.tools import (
ImportError: cannot import name 'ToolsRenderer' from 'langchain_core.tools' (/Users/foo/bar/buzz/venv/lib/python3.11/site-packages/langchain_core/tools/__init__.py)
```

**Expected behavior**

Crew execution shall not break.

**Screenshots/Code snippets**
If applicable, add screenshots or code snippets to help explain your problem.

```md
from langchain.tools.render import render_text_description
  File "/foo/bar/buzz/venv/lib/python3.11/site-packages/langchain/tools/render.py", line 9, in <module>
    from langchain_core.tools import (
ImportError: cannot import name 'ToolsRenderer' from 'langchain_core.tools' (/Users/foo/bar/buzz/venv/lib/python3.11/site-packages/langchain_core/tools/__init__.py)
```

I've addressed the issue also to the corresponding PR on langchain-core 👉🏻 [link](https://github.com/langchain-ai/langchain/pull/25172/files#r1717608351)

**Environment Details:**
- **Operating System**: Artix Linux
- **Python Version**: 3.11.4
- **crewAI Version**: latest
- **crewAI Tools Version**: latest

**Logs**
Include relevant logs or error messages if applicable.

Included above.

**Possible Solution**
Have a solution in mind? Please suggest it here, or write "None".

Currently downgraded the langchain-core package to avoid the error.

**Additional context**

**Comment by pythonbyte** [comment]
Thanks @andrewpap22 for the Bug Report. We are now understanding the issue and fixing it.

**Comment by joaomdmoura** [comment]
<img width="826" alt="Screenshot 2024-08-14 at 21 01 59" src="https://github.com/user-attachments/assets/d268c31f-e173-4aa2-a4c7-c721f74011b6">
langchain fixed it :)

**Comment by andrewpap22** [comment]
Yep they were pretty quick! 🙏🏻 👍🏻 --> [related_fix](https://github.com/langchain-ai/langchain/pull/25419/files)
