### ISSUE TITLE
cannot import name 'NL2SQLTool' from 'crewai_tools'

### ISSUE THREAD

**Issue by syedaameena** [crewAIInc/crewAI#1214]
### Description

 I am facing this issue in mac OS, cannot import name 'NL2SQLTool' from 'crewai_tools'

python version 3.11 crewai==0.22.5 crewai-tools==0.0.15

### Steps to Reproduce

from crewai_tools import NL2SQLTool
from crewai import Crew, Task, Agent
import ollama

### Expected behavior

I want the tool to work 

### Screenshots/Code snippets

from crewai_tools import NL2SQLTool
from crewai import Crew, Task, Agent

### Operating System

macOS Sonoma

### Python Version

3.11

### crewAI Version

crewai==0.22.5 crewai-tools==0.0.15

### crewAI Tools Version

crewai==0.22.5 crewai-tools==0.0.15

### Virtual Environment

Venv

### Evidence

<img width="1250" alt="Screenshot 2024-08-20 at 7 22 08 AM" src="https://github.com/user-attachments/assets/0aa79915-2cf1-4199-b243-e116b8dcc0e9">

### Possible Solution

![Uploading Screenshot 2024-08-20 at 7.22.08 AM.png…]()

### Additional context

the tool import is not working

**Comment by Darshanroy** [comment]
## Version Mismatch: The NL2SQLTool might not exist in the version of crewai-tools you're using (0.0.15). 

It's possible that the tool was added in a later version. 

try: 
``pip install --upgrade crewai-tools``

then try to import again

**Comment by theCyberTech** [comment]
NL2SQLToo is not available in version 00.15 please follow the instructions above to upgrade to latest

crewai-tools       0.8.3
