### ISSUE TITLE
Long-Term Memory Not Storing Data in Crew AI Agent

### ISSUE THREAD

**Issue by pg179-krishna-innoway** [crewAIInc/crewAI#1222]
### Description

I'm currently working on a project where I'm using Crew AI agents with chunking and context retention. As part of this process, I'm attempting to implement long-term memory for the agents using SQLite to store previous context and embedding information. However, I’ve noticed that the long-term memory is not storing any data.

### Steps to Reproduce

1. Integrate Crew AI agents with the logic for chunking SQL queries.
2. Implement the long-term memory storage using SQLite to retain context and embeddings across chunks.
3. Run the agent to process multiple SQL queries.

### Expected behavior

The long-term memory should store and retrieve context and embedding data for use in subsequent query processing.

### Screenshots/Code snippets

<img width="620" alt="Screenshot 2024-08-20 161832" src="https://github.com/user-attachments/assets/3760e0ff-927a-48a5-96a7-60287decfcab">

### Operating System

Windows 11

### Python Version

3.12

### crewAI Version

0.41.1

### crewAI Tools Version

NA

### Virtual Environment

Venv

### Evidence

<img width="620" alt="Screenshot 2024-08-20 161832" src="https://github.com/user-attachments/assets/aa3b4994-bfe3-4514-8478-c4d35a061f10">

### Possible Solution

None

### Additional context

None

**Comment by theCyberTech** [comment]
Can you please provide more info / context on how you are setting this up in your crew I.E the code itself as you have only supplied a screenshot of the underlying crewai code for long term memory

**Comment by pg179-krishna-innoway** [comment]
agent1= Agent(
        role="...",
        goal=...,
        allow_delegation=False,
        verbose=True,
        memory=True,
        llm=llm
    )
    agent2= Agent(
        role=...,
        goal=...
        allow_delegation=False,
        verbose=True,
        memory=True,
        tools = [web_tool],
        llm=llm
    )
    
    
    crew = Crew(
        agents=[agent1, agent2],
        tasks=[task1, task2],
        memory=True,
        process=Process.sequential,
        verbose=True,
        embedder={
            "provider": "google",
            "config":{
                "model": 'models/embedding-001',
                "task_type": "retrieval_document",
                "title": "Embeddings for Embedchain"
            }
        }
    )
    
    This is my code where I am creating two agents and a crew. Other than this I have also used the way to store context in long term memory using theapproach as mentioned in the crewai documentation : https://docs.crewai.com/core-concepts/Memory/#how-memory-systems-empower-agents. 

It is creating a file long_term_memory.db but the file is empty.

**Comment by crazypythonista** [comment]
Any update on this? Encountering the same bug.

**Comment by Tehsmash** [comment]
Also hitting this issue, looking at the code I can only see one place _long_term_memory.save(..) is called (in the agent executor mixin), and there is no reference from anywhere else to it.

**Comment by williamgurzoni** [comment]
I'm also facing something similar. But I'm receiving the error: "Missing attributes for long term memory: 'str' object has no attribute 'quality'".

**Comment by nkeilar** [comment]
I'm also hitting this: 

```
# Agent: Team Manager
## Thought: Thought: I need to engage with the Senior customer communicator to ask about the website URL in a professional manner. They will help us get this crucial information from the customer.
## Using tool: Delegate work to coworker
## Tool Input: 
"{\"coworker\": \"Senior customer communicator\", \"task\": \"Ask the customer which website they want to generate more content for\", \"context\": \"We need to identify the website URL that the customer wants to focus on for content generation. Please ask them in a professional and friendly manner, and ensure to mention that you'll help format it properly (e.g., if they say 'mybusiness.com', you'll format it as 'https://mybusiness.com'). This is the first step in our content generation project and is crucial for moving forward.\"}"
## Tool Output: 
Thank you for providing your website URL! I can confirm that we'll be focusing on https://mybusiness.com/ for your content generation project. I've verified that this URL is properly formatted with the 'https://' protocol, so we're all set to proceed with developing your content strategy. Is there anything specific about your golf challenge website that you'd like me to know as we move forward with content planning?


# Agent: Team Manager
## Final Answer: 
https://mybusiness.com/


Missing attributes for long term memory: 'str' object has no attribute 'quality'
```

**Comment by nkeilar** [comment]
Seems related to this file as its the only place that string occurs: https://github.com/crewAIInc/crewAI/blame/5f46ff883632e4b3396c6dfbae98b9347e807f99/src/crewai/agents/agent_builder/base_agent_executor_mixin.py#L97

And the only change made there recently seems to be this PR:
https://github.com/crewAIInc/crewAI/pull/1444
