### ISSUE TITLE
kickoff_async() not working properly

### ISSUE THREAD

**Issue by pradeepdev-1995** [crewAIInc/crewAI#1234]
### Description

I have 2 crews and I  want to run both crews simultaneously 
```
crew_1 = Crew(
 agents = [agent 1, agent 2],
 tasks = [task 1, task 2],
 process = Process. sequential,
 max_rpm = 1,
 manager_llm = agentLlm,
 cache=True
 )
result_1 = crew_1.kickoff(inputs=inputs)

crew_2 = Crew(
 agents = [agent 1, agent 2],
 tasks = [task 1, task 2],
 process = Process. sequential,
 max_rpm = 1,
 manager_llm = agentLlm,
 cache=True
 )
result_2 = crew_2.kickoff_async(inputs=inputs)
```
But I observe that only crew_1 (which has triggered using normal kickoff()) is executing first and  crew_2(which has triggered using normal kickoff_async()) is after this. Sometimes crew_2 is not executing at all. 

My expected workflow is for both crews to run simultaneously to reduce the sequential flow latency. 

### Steps to Reproduce

```
crew_1 = Crew(
 agents = [agent 1, agent 2],
 tasks = [task 1, task 2],
 process = Process. sequential,
 max_rpm = 1,
 manager_llm = agentLlm,
 cache=True
 )
result_1 = crew_1.kickoff(inputs=inputs)

crew_2 = Crew(
 agents = [agent 1, agent 2],
 tasks = [task 1, task 2],
 process = Process. sequential,
 max_rpm = 1,
 manager_llm = agentLlm,
 cache=True
 )
result_1 = crew_2.kickoff_

### Expected behavior

My expected workflow is for both crews to run simultaneously to reduce the sequential flow latency. 

### Screenshots/Code snippets

no screenshotes

### Operating System

Windows 10

### Python Version

3.10

### crewAI Version

crewai==0.36.1

### crewAI Tools Version

 crewai-tools==0.8.3

### Virtual Environment

Venv

### Evidence

getting lo like this before each crew kick off
<coroutine object Crew.kickoff_async at 0x000001EDD9F8C6D0>

### Possible Solution

My expected workflow is for both crews to run simultaneously to reduce the sequential flow latency. 

### Additional context

My expected workflow is for both crews to run simultaneously to reduce the sequential flow latency.

**Comment by bhancockio** [comment]
Hey @pradeepdev-1995! I put together a quick Loom for you to cover what I'm seeing in your example and I suggest a few next steps.

https://www.loom.com/share/043fbf93991243fcb88c31b9e0c66de5?sid=b6f50a2d-e0a4-4206-9f02-8f03cbeba462

Please let me know if you have any followup questions and if the steps in the video help get your code working as expected.

**Comment by pradeepdev-1995** [comment]
I tried the same way you mentioned—making both crews kickoff_async(). But nothing happening. Both crews are not even started now. Seems like the hanged manner. Attaching the below screenshot which is showing for the last 10 minutes. 

![Capture](https://github.com/user-attachments/assets/ddec9c7b-c62f-42e1-a64c-3ac94e1d19f0)

**Comment by bhancockio** [comment]
Hey @pradeepdev-1995 , please shoot me an email so we can setup a quick Zoom call to look more at your Crew to figure out what's going wrong. My email is brandon@crewai.com.

I'm free pretty much any time tomorrow to help!

**Comment by SONYYA7** [comment]
is it resolved?
the code snippet in doc itself doesn't work 
from crewai import Crew, Agent, Task

# Create an agent with code execution enabled
coding_agent = Agent(
    role="Python Data Analyst",
    goal="Analyze data and provide insights using Python",
    backstory="You are an experienced data analyst with strong Python skills.",
    allow_code_execution=True
)

# Create a task that requires code execution
data_analysis_task = Task(
    description="Analyze the given dataset and calculate the average age of participants. Ages: {ages}",
    agent=coding_agent
)

# Create a crew and add the task
analysis_crew = Crew(
    agents=[coding_agent],
    tasks=[data_analysis_task]
)

# Execute the crew asynchronously
result = analysis_crew.kickoff_async(inputs={"ages": [25, 30, 35, 40, 45]})


and for my agent system : i am recieving <coroutine object Crew.kickoff_async at 0x78230049ab20>

as o/p
