### ISSUE TITLE
[BUG] Asynchronous Agents Terminate Prematurely 

### ISSUE THREAD

**Issue by SONYYA7** [crewAIInc/crewAI#1237]
### Description

the verbose 
> Entering new CrewAgentExecutor chain...

> Entering new CrewAgentExecutor chain...

> Entering new CrewAgentExecutor chain...

> Entering new CrewAgentExecutor chain...

> Entering new CrewAgentExecutor chain...

> Entering new CrewAgentExecutor chain...

> Entering new CrewAgentExecutor chain...

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Finished chain.

> Entering new CrewAgentExecutor chain...

> Finished chain.
Agent stopped due to iteration limit or time limit.
This causes the process to hit the iteration or time limit, resulting in premature termination of the agents' execution.

### Steps to Reproduce

-

### Expected behavior

-

### Screenshots/Code snippets

-

### Operating System

Ubuntu 20.04

### Python Version

3.10

### crewAI Version

-

### crewAI Tools Version

-

### Virtual Environment

Venv

### Evidence

-

### Possible Solution

-

### Additional context

-

**Comment by vineet-codes256** [comment]
same issue

**Comment by SONYYA7** [comment]
for my case,  it is because of subscription expired

**Comment by theCyberTech** [comment]
closing due ti minimal information provided to troublshoot

**Comment by vineet-codes256** [comment]
> for my case, it is because of subscription expired

Same for mine as well. It was the `OPENAI_API_KEY` key issue. I didn't had enough credits on my personal account, so it was not working.

**Comment by theCyberTech** [comment]
thanks for the update
