### ISSUE TITLE
[FEATURE] Option to automatically summarise context window

### ISSUE THREAD

**Issue by joshackland** [crewAIInc/crewAI#1241]
### Feature Area

Core functionality

### Is your feature request related to a an existing bug? Please link it here.

https://github.com/crewAIInc/crewAI/discussions/1111

### Describe the solution you'd like

https://github.com/crewAIInc/crewAI/blob/8119edb4957745a4db26beda9dcf06b34742c90d/src/crewai/agents/executor.py#L369

The current implementation with summarising context window requires the user to say whether the context window should be summarised.
Ideally we could set an option for this to automatically be done so CrewAI can be ran from start to finish without requiring user input.

### Willingness to Contribute

Yes, I'd be happy to submit a pull request

**Comment by joebwd** [comment]
I need this!!
