### ISSUE TITLE
[BUG] [WinError 2] The system cannot find the file specified Error

### ISSUE THREAD

**Issue by GhayourAli** [crewAIInc/crewAI#1282]
### Description

I have created a new crewai project using `crewai create crew <project_name>` command. Without making any changes, I run the 'crewai run' command but it gives the following error. I am using windows machine. 
**_The system cannot find the file specified Error_**
I don't have OpenAI key, therefore I tried using Claude 3.5 from AWS Bedrock. But receiving same error everytime.

### Steps to Reproduce

1. Create a new project using `crewai create crew` comment
2. Run `crewai run` command. It gives error [WinError 2] The system cannot find the file specified Error
3. Use Claude 3.5 from AWS Bedrock as LLM for Agent
4. Still getting same error on crewai run

### Expected behavior

crewai.run command should start the agents and complete the tasks.

### Screenshots/Code snippets

![image](https://github.com/user-attachments/assets/a83e5d16-b5b1-4ab2-8c67-05a08a21bf7a)

### Operating System

Windows 11

### Python Version

3.10

### crewAI Version

0.51.1

### crewAI Tools Version

0.12.0

### Virtual Environment

Venv

### Evidence

![image](https://github.com/user-attachments/assets/0275c80b-01c1-4a39-bdd1-9b600579166f)

### Possible Solution

None

### Additional context

None

**Comment by theCyberTech** [comment]
is that the full error message?

**Comment by GhayourAli** [comment]
@theCyberTech yes this is the full error message

**Comment by BriCusack** [comment]
did you cd into the project?

**Comment by GhayourAli** [comment]
@BriCusack Yes I am in the project directory

**Comment by mike-riff** [comment]
Same issue. 
Windows 11, Python 3.11.3:
> cd riff-crewai
> python -m venv crewai-env
> .\crewai-env\Scripts\activate 
> crewai create crew riff_crew_helloworld
> Crew riff-crew-helloworld created successfully!
> crewai install

![image](https://github.com/user-attachments/assets/d72d8f55-6da8-44d1-98ef-922d74d84086)

**Comment by BriCusack** [comment]
Try using Poetry env not python venv:
`$ crewai create crew <project_name>`
`$ cd project_name`
`$ poetry install --no-root`
`$ poetry shell`
note - in vscode run
`$ poetry env info`
and grab the Executable python path for the interpreter. Add as path.
than:
`$ crewai run`
 Hope this helps

**Comment by sniperadmin** [comment]
Make sure to have the following defined in your windows environment variables PATH: `C:\Users\<your pc name>\.pyenv\pyenv-win\versions\<python version>\Scripts\`

and the path should exist too
