### ISSUE TITLE
[BUG] Pipelines with Routes - unable to start, documentation is broken

### ISSUE THREAD

**Issue by eugenepyvovarov** [crewAIInc/crewAI#1296]
### Description

Trying to get pipelines going with routes, documentation and samples are slightly off.
Imports to Routes and Route are not correct and sample code will fail validation for Tasks, Agent pedantic validation, since it is missing several fields.

But even after fixing that it will not start, I receive this error message no matter what

`RuntimeWarning: coroutine 'Pipeline.kickoff' was never awaited
  main_pipeline.kickoff(inputs=inputs)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback`

As  I understand - the route functionality is done with async module and we can't just run it like normal function. But my experience with async calling is not enough to run it properly, if someone was able to run it - please advice.

### Steps to Reproduce

1. just followed the route documentation https://docs.crewai.com/core-concepts/Pipeline/#routers-in-pipelines

### Expected behavior

I expect it to run and return something so I can start building on top of it

### Screenshots/Code snippets

everything is in the description

### Operating System

macOS Sonoma

### Python Version

3.12

### crewAI Version

0.51

### crewAI Tools Version

--

### Virtual Environment

Venv

### Evidence

![CleanShot 2024-09-05 at 14 42 25](https://github.com/user-attachments/assets/c3138d1d-c95f-46a4-a7a9-9961b58e31d3)

### Possible Solution

I can try to help docs where I did myself, however I. need help with async part

### Additional context

.

**Comment by bhancockio** [comment]
Hey @eugenepyvovarov! I'm working on updating the Pipeline docs this week.

I want to unblock you as fast as possible though! Are you free for a Zoom call today or tomorrow? I'd be happy to review your pipeline and show you how to fix it.

Please shoot me an email at brandon@crewai.com so we can coordinate a time if you're interested in additional support.

If not, no worries! I'll shoot you a message as soon as we fix the docs.

**Comment by Yazooliu** [comment]
> ### Description
> Trying to get pipelines going with routes, documentation and samples are slightly off. Imports to Routes and Route are not correct and sample code will fail validation for Tasks, Agent pedantic validation, since it is missing several fields.
> 
> But even after fixing that it will not start, I receive this error message no matter what
> 
> `RuntimeWarning: coroutine 'Pipeline.kickoff' was never awaited main_pipeline.kickoff(inputs=inputs) RuntimeWarning: Enable tracemalloc to get the object allocation traceback`
> 
> As I understand - the route functionality is done with async module and we can't just run it like normal function. But my experience with async calling is not enough to run it properly, if someone was able to run it - please advice.
> 
> ### Steps to Reproduce
> 1. just followed the route documentation https://docs.crewai.com/core-concepts/Pipeline/#routers-in-pipelines
> 
> ### Expected behavior
> I expect it to run and return something so I can start building on top of it
> 
> ### Screenshots/Code snippets
> everything is in the description
> 
> ### Operating System
> macOS Sonoma
> 
> ### Python Version
> 3.12
> 
> ### crewAI Version
> 0.51
> 
> ### crewAI Tools Version
> --
> 
> ### Virtual Environment
> Venv
> 
> ### Evidence
> ![CleanShot 2024-09-05 at 14 42 25](https://private-user-images.githubusercontent.com/39050/364779418-c3138d1d-c95f-46a4-a7a9-9961b58e31d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzA1MjksIm5iZiI6MTcyNzE3MDIyOSwicGF0aCI6Ii8zOTA1MC8zNjQ3Nzk0MTgtYzMxMzhkMWQtYzk1Zi00NmE0LWE3YTktOTk2MWI1OGUzMWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA5MzAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNTMxOWU3NWVjNDZmNzFjYmM0NmM5ZTA0ZmU4ZGVlNThiY2QxNjY1ZDY0Njg0ZDEzN2JjYWNkNWQ2Y2VhMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ngVkNreGGeoNPNeKLYYaGQnEjuUeu3NyOyBHX3qy-Ec)
> 
> ### Possible Solution
> I can try to help docs where I did myself, however I. need help with async part
> 
> ### Additional context
> .

try to start the pipeline kickoff like this function call, I try this is OK!
gen_pipeline = Pipeline(
    stages=[spam_crew, analyst_crew, writing_crew]
)

#
async def gen_main():
    result_s = await gen_pipeline.kickoff(inputs=[{"discussion": discussion}])
    return result_s

results = asyncio.run(gen_main())
