### ISSUE TITLE
[BUG] Agent can not have tools and allow_delegation together

### ISSUE THREAD

**Issue by hukaidong** [crewAIInc/crewAI#1301]
### Description

When an agent is having non-empty tools and allow_delegation=True together. Two delegation tool descriptions are not present in composed agent tasks.

### Steps to Reproduce

1. Pull and install latest crewAI (0.54.0)
2. `pip install agentops` (tested version 0.3.10)
3. Copy code in [README.md section 2](https://github.com/crewAIInc/crewAI#2-setting-up-your-crew) into main.py
4. Add line `tools=[search_tool]` in `writer: Agent`
5. `python main.py`
6. Look at generated prompt in agentops

### Expected behavior

There should be 3 tools available for writer `[Delegate work to coworker, Ask question to coworker, Search the internet]

### Screenshots/Code snippets

Agentobs shows only one tool available in prompt [Search the internet]

### Operating System

Ubuntu 20.04

### Python Version

3.12

### crewAI Version

0.54.0

### crewAI Tools Version

0.8.3

### Virtual Environment

Venv

### Evidence

You ONLY have access to the following tools, and should NEVER make up tools that are not listed here:

Tool Name: Search the internet(**kwargs: Any) -> Any
Tool Description: Search the internet(search_query: 'string') - A tool that can be used to search the internet with a search_query. search_query: 'Mandatory search query you want to use to search the internet'
Tool Arguments: {'search_query': {'title': 'Search Query', 'description': 'Mandatory search query you want to use to search the internet', 'type': 'string'}}

Use the following format:

### Possible Solution

None

### Additional context

Tested in docker ubuntu 20.04 and opensuse tumbleweed

**Comment by hukaidong** [comment]
The latest version not affected by this bug is 0.51.0.

**Comment by jppaulo06** [comment]
Is there a plan to solve this bug?

**Comment by jppaulo06** [comment]
Bug still persists in version 0.86.0. Will it ever be fixed?

**Comment by jppaulo06** [comment]
Super messy stuff to fix the issue for now, but it works at least :P

Import:
```
from crewai.tools.agent_tools.ask_question_tool import AskQuestionTool
from crewai.tools.agent_tools.delegate_work_tool import DelegateWorkTool
```

Put in agent tools:

```
DelegateWorkTool(
  agents=[self.agent1(), self.agent2()],
  description="Delegate a specific task to one of the following coworkers: agent1, agent2\nThe input to this tool should be the coworker, the task you want them to do, and ALL necessary context to execute the task, they know nothing about thetask, so share absolute everything you know, don't reference things but instead explain them.",
),
AskQuestionTool(
  agents=[self.agent1(), self.agent2()],
  description="Ask a specific question to one of the following coworkers: agent1, agent2\nThe input to this tool should be the coworker,the question you have for them, and ALL necessary context to ask the question properly, they know nothing about the question, so share absolute everything you know, don't reference things but instead explain them.",
),
```

Just replace `agent1` and `agent2` with your agents.
