### ISSUE TITLE
[MISSING_REQUIREMENT] missing documentation code snippet

### ISSUE THREAD

**Issue by N8sGit** [crewAIInc/crewAI#1317]
### Description

Not really a bug but a missing piece of text in the docs.
Location: [https://docs.crewai.com/getting-started/Start-a-New-CrewAI-Project-Template-Method/#creating-a-new-project](https://docs.crewai.com/getting-started/Start-a-New-CrewAI-Project-Template-Method/#creating-a-new-project)
Issue: Under the Creating A New Project header, where it says "To set up a virtual environment, run the following CLI command:" the promised code snippet is missing 
Evidence:
<img width="1016" alt="Screenshot 2024-09-10 at 3 33 32 PM" src="https://github.com/user-attachments/assets/903f12d7-892c-4187-a3ce-a38d97bb4b3f">

A small detail but as some facing sudden environment issues running the framework it would be helpful to have this information to restart from scratch. 

### Steps to Reproduce

Go to [https://docs.crewai.com/getting-started/Start-a-New-CrewAI-Project-Template-Method/#creating-a-new-project](https://docs.crewai.com/getting-started/Start-a-New-CrewAI-Project-Template-Method/#creating-a-new-project)

### Expected behavior

Complete docs

### Screenshots/Code snippets

<img width="1016" alt="Screenshot 2024-09-10 at 3 33 32 PM" src="https://github.com/user-attachments/assets/9d762296-563e-437a-b7d8-fecbf2d9a94e">

### Operating System

Ubuntu 20.04

### Python Version

3.12

### crewAI Version

00

### crewAI Tools Version

00

### Virtual Environment

Venv

### Evidence

See description 

### Possible Solution

Insert missing snippet 

### Additional context

n/a

**Comment by pravincoder** [comment]
@N8sGit  , The Documentation is now updated ,

so I request you to close the issue , so that it's easy to find actual issue that needs attention😁.

Hope you got my point!
