### ISSUE TITLE
[FEATURE] Nested crews (super-crews)

### ISSUE THREAD

**Issue by N8sGit** [crewAIInc/crewAI#1319]
### Feature Area

Core functionality

### Is your feature request related to a an existing bug? Please link it here.

N/A

### Describe the solution you'd like

Perhaps this is already achievable within the existing framework, if so, a more direct API for it could be provided. In any case, I've been playing around with pipelines, which strike me as the point where the framework really starts getting interesting. However, as far as I can tell, parallelized crews at the same stage cannot delegate to each other horizontally, as they would if they were agents in the same crew if allow_delegation=True. 

It would be cool to be able to wrap all of these crews in the same logical frame as the CrewBase class, except where each Agent would go in the CrewBase class a CrewBase class goes. This would provide for the ability to delegate across crews in parallel.  By treating each Crew as a logical stand-in for an Agent, the power of both classes can be leveraged onto both simultaneously.  

### Describe alternatives you've considered

Perhaps the Pipeline class could supply this means for better communication between parallelized crews. The SuperAgent could plausibly be a replacement for the Pipeline API altogether. 

### Additional context

This feature occurred to me when I ran a pipeline that had a paralleled stage step with three adjacent crews. One agent in the crew sought to delegate to another agent in an adjacent crew but failed .  My design tried to encourage awareness between different crews so I'm not sure if this is a common occurence. 

### Willingness to Contribute

I could provide more detailed specifications

**Comment by gadgethome** [comment]
Hi Nathan,

Thanks for the feedback. The dev team are currently working on a new approach that will make it easier to achieve this. We will update you as soon as we have more information. thanks
