### ISSUE TITLE
[BUG] LLM "ollama/llama3.1" does not obey BASE_URL 

### ISSUE THREAD

**Issue by balanceainetwork** [crewAIInc/crewAI#1337]
### Description

Trying to run agents with "ollama/llama3.1" deployed on another server. When setting LLM as "ollama/llama3.1" and providing os.environ["OLLAMA_BASE_URL"] as another server. The LLM is not picked up correctly. 

### Steps to Reproduce

1. Set LLM as "ollama/llama3.1"
2. Set os.environ["OLLAMA_BASE_URL"] to server running Ollama

### Expected behavior

It should be able to create connection to LLM running on another server with model "ollama/llama3.1"

### Screenshots/Code snippets

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

### Operating System

macOS Sonoma

### Python Version

3.12

### crewAI Version

0.61

### crewAI Tools Version

0.12.1

### Virtual Environment

Venv

### Evidence

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

### Possible Solution

LiteLLM should support Ollama running on another host

### Additional context

None

**Comment by theCyberTech** [comment]
Try using OPENAI_BASE_URL instead

**Comment by balanceainetwork** [comment]
It does now work too. Looks like when the model is "ollama/llama3.1" liteLLM uses default localhost:11434 In the old version (0.41) u specify actual model object not a string to Agent creation. Any idea how to make liteLLM to connect to specific port when using ollama?

**Comment by balanceainetwork** [comment]
> Try using OPENAI_BASE_URL instead

It has no effect, when using "ollama/llama3.1" as model it ignores that param imho and uses localhost:11434

I can not find how to change that behaviour in liteLLM. It really messes up our deployment as we need to run Ollama on separate container. 

Any help ?

**Comment by theCyberTech** [comment]
No I mean you set the url using that env

OPENAI_BASE_URL='http://localhost:11434'

**Comment by balanceainetwork** [comment]
Yes, I know but setting that env has no effect. What I mean is that when u provide llm as "ollama/llama3.1" liteLLM uses localhost:11434 to connect, regardless of OPENAI_BASE_URL set. Try to set it to another port and it still works. If I run ollama on another port and set OPENAI_BASE_URL to that port. Crew does not connect at all, it still connects to default port. Any idea?

**Comment by joaomdmoura** [comment]
new version is out v0.63.1
env vars should work again, also ability to control all different attribute for the LLM using the LLM class, if this is still an issue let us know and we can re-open it :)

I also wrote a test for it @balanceainetwork 

```python
@pytest.mark.vcr(filter_headers=["authorization"])
def test_agent_with_ollama_gemma():
    agent = Agent(
        role="test role",
        goal="test goal",
        backstory="test backstory",
        llm=LLM(
            model="ollama/gemma2:latest",
            base_url="http://localhost:8080",
        ),
    )

    assert isinstance(agent.llm, LLM)
    assert agent.llm.model == "ollama/gemma2:latest"
    assert agent.llm.base_url == "http://localhost:8080"

    task = "Respond in 20 words. Who are you?"
    response = agent.llm.call([{"role": "user", "content": task}])

    assert response
    assert len(response.split()) <= 25  # Allow a little flexibility in word count
    assert "Gemma" in response or "AI" in response or "language model" in response
```

**Comment by joaomdmoura** [comment]
Oh you can also use `OPENAI_MODEL_NAME`, `OPENAI_API_BASE`, `OPENAI_API_KEY`

**Comment by balanceainetwork** [comment]
Imported LLM from CrewAI

setting LLM in Agent:
llm = LLM(
            model="ollama/llama3.1:latest",
            base_url="http://localhost:11435",
        )

I get the following error: 

ERROR: LiteLLM call failed: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=(<crewai.llm.LLM object at 0x104d4ac60>,)

**Comment by balanceainetwork** [comment]
I am not calling LLM directly but using Crew with Agents.

**Comment by balanceainetwork** [comment]
@joaomdmoura still the same issue with the latest release
