### ISSUE TITLE
[BUG]LLM creat bug

### ISSUE THREAD

**Issue by aylitat** [crewAIInc/crewAI#1372]
### Description

While I use LLM to creat llm,it show me this error:

`litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=moonshot-v1-32k
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)`
 
# code:
`llm = get_llm(
    api_key=BASE_CONFIG.MOONSHOT_API_KEY,
    base_url=BASE_CONFIG.BASE_URL,
    model=BASE_CONFIG.MODEL
)`

 But I use the custom-model example:
 `llm = LLM(
    model="custom-model-name",
    base_url="https://api.your-provider.com/v1",
    api_key="your-api-key"
)
agent = Agent(llm=llm, ...)`

![image](https://github.com/user-attachments/assets/914adc74-5fcb-424f-913b-e51daa13d00c)

### Steps to Reproduce

https://docs.crewai.com/how-to/LLM-Connections/#using-local-models-with-ollama

### Expected behavior

pass

### Screenshots/Code snippets

 `llm = LLM(
    model="custom-model-name",
    base_url="https://api.your-provider.com/v1",
    api_key="your-api-key"
)
agent = Agent(llm=llm, ...)`

### Operating System

Windows 10

### Python Version

3.10

### crewAI Version

lastest

### crewAI Tools Version

lastest

### Virtual Environment

Venv

### Evidence

![image](https://github.com/user-attachments/assets/914adc74-5fcb-424f-913b-e51daa13d00c)

### Possible Solution

None

### Additional context

pass

**Comment by CStrue** [comment]
Have the same issue

**Comment by gnana70** [comment]
Any one found work around?

**Comment by aavetis** [comment]
same issue when providing a custom api url
