### ISSUE TITLE
[BUG]CrewAI0.6 Memory module failed and was not called at all

### ISSUE THREAD

**Issue by fanhomi** [crewAIInc/crewAI#1388]
### Description

At CrewAI The src\crewai\agents\executor.py file of version 0.55.2 has calls to _create_short_term_memory and _create_long_term_memory from the CrewAgentExecutorMixin .
In the latest version of the agents\agent_builder\base_agent_executor_mixin.py file, there are no calls to the above two functions, resulting in running a store with no long or short term memory.

### Steps to Reproduce

None

### Expected behavior

fix it

### Screenshots/Code snippets

None

### Operating System

Windows 10

### Python Version

3.11

### crewAI Version

0.6

### crewAI Tools Version

0.12.1

### Virtual Environment

Venv

### Evidence

None

### Possible Solution

None

### Additional context

None

**Comment by cburnicki** [comment]
I have the same issue, it looks like the code has been unintentionally (?) removed during a refactoring by @joaomdmoura in commit e77442c.

**Comment by cburnicki** [comment]
I have a branch here, but tests are still broken and new tests are missing. I'll probably not be able to continue working on this before next week.
Branch: issue-1388-restore-create-memory-call

**Comment by claumazz** [comment]
Any update on this?

**Comment by cburnicki** [comment]
I think it was fixed in the meantime: [https://github.com/crewAIInc/crewAI/pull/1444#event-14702169067](https://github.com/crewAIInc/crewAI/pull/1444#event-14702169067)
