### ISSUE TITLE
from crewai import Agent, LLM

### ISSUE THREAD

**Issue by Puneet-sinha-tcgls** [crewAIInc/crewAI#1401]
### Description

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-18-78ea5f6c6260>](https://localhost:8080/#) in <cell line: 2>()
      1 #from crewai import Agent, Task, Crew
----> 2 from crewai import Agent, LLM

ImportError: cannot import name 'LLM' from 'crewai' (/usr/local/lib/python3.10/dist-packages/crewai/__init__.py)

### Steps to Reproduce

just import 

### Expected behavior

this an import error 

### Screenshots/Code snippets

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-18-78ea5f6c6260>](https://localhost:8080/#) in <cell line: 2>()
      1 #from crewai import Agent, Task, Crew
----> 2 from crewai import Agent, LLM

ImportError: cannot import name 'LLM' from 'crewai' (/usr/local/lib/python3.10/dist-packages/crewai/__init__.py)

### Operating System

Ubuntu 20.04

### Python Version

3.10

### crewAI Version

0.67.1

### crewAI Tools Version

0.1.6

### Virtual Environment

Venv

### Evidence

NA

### Possible Solution

NA

### Additional context

NA

**Comment by theCyberTech** [comment]
why are you importing LLM?

**Comment by Puneet-sinha-tcgls** [comment]
I want to use the module 
Using Local Models with Ollama
Link : https://docs.crewai.com/how-to/LLM-Connections/#1-using-a-string-identifier

from crewai import Agent, LLM

agent = Agent(
    role='Local AI Expert',
    goal='Process information using a local model',
    backstory="An AI assistant running on local hardware.",
    llm=LLM(model="ollama/llama2", base_url="http://localhost:11434")
)
llm = LLM(
    model="custom-model-name",
    base_url="https://api.your-provider.com/v1",
    api_key="your-api-key"
)
agent = Agent(llm=llm, ...)
i want to use Ollama 3.1 locally so i want to use LLM

**Comment by Puneet-sinha-tcgls** [comment]
> why are you importing LLM?

you have a quick fix?

**Comment by Hippozhibos** [comment]
Same case. Any update?

**Comment by mkliangcoIA** [comment]
I want to use Ollama with CrewAI but I cannot figure out where in crew.py or main.py i should put the LLM, and also what should i put in the .env? Sorry I am new to this

**Comment by ricobuilds** [comment]
> I want to use Ollama with CrewAI but I cannot figure out where in crew.py or main.py i should put the LLM, and also what should i put in the .env? Sorry I am new to this

here's how I use ollama with crewai this is how I implement it:

```py
base_model = "llama3.2"
code_model = "codegemma"
ollama_api = "http://localhost:11434"

base_llm = Ollama(model=base_model, base_url=ollama_api)
code_llm = Ollama(model=code_model, base_url=ollama_api)
```

make sure to have ollama and the models you wanna use installed 👍

**Comment by SDAravind** [comment]
> here's how I setup ollama with crewai:
> 
> ```python
> base_model = "llama3.2"
> code_model = "codegemma"
> ollama_api = "http://localhost:11434"
> 
> base_llm = Ollama(model=base_model, base_url=ollama_api)
> code_llm = Ollama(model=code_model, base_url=ollama_api)
> ...
> researcher = Agent(...props, llm=base_llm)
> ```
> 
> make sure to have ollama and the models you wanna use installed 👍

@ricobuilds - can you please add imports as well? It's unclear from where Ollama is getting imported. Is it langchain or somewhere else?

**Comment by ricobuilds** [comment]
@SDAravind thanks for the reminder! this is the tweaked example with the imports:

```py
from crewai import Agent, Task, Crew, Process
from langchain_community.llms import Ollama
...
base_model = "llama3.2"
code_model = "codegemma"
ollama_api = "http://localhost:11434"

base_llm = Ollama(model=base_model, base_url=ollama_api)
code_llm = Ollama(model=code_model, base_url=ollama_api)
...
researcher = Agent(...props, llm=base_llm)
```
