### ISSUE TITLE
[BUG] Memory Error

### ISSUE THREAD

**Issue by httplups** [crewAIInc/crewAI#1405]
### Description

Hi. I am using Gemini as the LLM to test this example from Deep Learning AI course.

The crew works fine when Memory is set to False. But when I tried to set True, as in the course, I got the following error:
```
AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: fake. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}```

### Steps to Reproduce

1. Set up Gemini as LLM
`llm = LLM(
    model="gemini-1.5-flash-002",
    temperature=0
)
`
2. Setup agents
```
support_agent = Agent(
    role="Senior Support Representative",
	goal="Be the most friendly and helpful "
        "support representative in your team",
	backstory=(
		"You work at crewAI (https://crewai.com) and "
        " are now working on providing "
		"support to a super important customer "
        " for your company."
		"You need to make sure that you provide the best support!"
		"Make sure to provide full complete answers, "
        " and make no assumptions."
	),
	allow_delegation=False,
	verbose=True,
    llm=llm
)

support_quality_assurance_agent = Agent(
	role="Support Quality Assurance Specialist",
	goal="Get recognition for providing the "
    "best support quality assurance in your team",
	backstory=(
		"You work at crewAI (https://crewai.com) and "
        "are now working with your team "
		"on a request from customer ensuring that "
        "the support representative is "
		"providing the best support possible.\n"
		"You need to make sure that the support representative "
        "is providing full"
		"complete answers, and make no assumptions."
	),
	verbose=True,
    # allow_delegation=False,
    llm=llm
)
```
3. Setup tasks
```
from crewai_tools import SerperDevTool, \
                         ScrapeWebsiteTool, \
                         WebsiteSearchTool

docs_scrape_tool = ScrapeWebsiteTool(
    website_url="https://docs.crewai.com/how-to/Creating-a-Crew-and-kick-it-off/"
)

inquiry_resolution = Task(
    description=(
        "{customer} just reached out with a super important ask:\n"
	    "{inquiry}\n\n"
        "{person} from {customer} is the one that reached out. "
		"Make sure to use everything you know "
        "to provide the best support possible."
		"You must strive to provide a complete "
        "and accurate response to the customer's inquiry."
    ),
    expected_output=(
	    "A detailed, informative response to the "
        "customer's inquiry that addresses "
        "all aspects of their question.\n"
        "The response should include references "
        "to everything you used to find the answer, "
        "including external data or solutions. "
        "Ensure the answer is complete, "
		"leaving no questions unanswered, and maintain a helpful and friendly "
		"tone throughout."
    ),
	tools=[docs_scrape_tool],
    agent=support_agent,
)

quality_assurance_review = Task(
    description=(
        "Review the response drafted by the Senior Support Representative for {customer}'s inquiry. "
        "Ensure that the answer is comprehensive, accurate, and adheres to the "
		"high-quality standards expected for customer support.\n"
        "Verify that all parts of the customer's inquiry "
        "have been addressed "
		"thoroughly, with a helpful and friendly tone.\n"
        "Check for references and sources used to "
        " find the information, "
		"ensuring the response is well-supported and "
        "leaves no questions unanswered."
    ),
    expected_output=(
        "A final, detailed, and informative response "
        "ready to be sent to the customer.\n"
        "This response should fully address the "
        "customer's inquiry, incorporating all "
		"relevant feedback and improvements.\n"
		"Don't be too formal, we are a chill and cool company "
	    "but maintain a professional and friendly tone throughout."
    ),
    agent=support_quality_assurance_agent,
)

```

4. Create Crew
```
crew = Crew(
  agents=[support_agent, support_quality_assurance_agent],
  tasks=[inquiry_resolution, quality_assurance_review],
  verbose=True,
  memory=True
)
```
5. Run  
```
inputs = {
    "customer": "DeepLearningAI",
    "person": "Andrew Ng",
    "inquiry": "I need help with setting up a Crew "
               "and kicking it off, specifically "
               "how can I add memory to my crew? "
               "Can you provide guidance?"
}

result = crew.kickoff(inputs=inputs)
```

### Expected behavior

I expected that the crew runs normally, but Instead I got an error.
I now the problem is with the memory=True parameter, since it works when it is False.

### Screenshots/Code snippets

```
{
	"name": "AuthenticationError",
	"message": "Error code: 401 - {'error': {'message': 'Incorrect API key provided: fake. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}",
	"stack": "---------------------------------------------------------------------------
AuthenticationError                       Traceback (most recent call last)
Cell In[155], line 12
      1 inputs = {
      2     \"customer\": \"DeepLearningAI\",
      3     \"person\": \"Andrew Ng\",
   (...)
      7                \"Can you provide guidance?\"
      8 }
      9 # inputs = {
     10 #     'msg': 'Hello, my name is Luana'
     11 # }
---> 12 result = crew.kickoff(inputs=inputs)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/crew.py:490, in Crew.kickoff(self, inputs)
    487 metrics: List[UsageMetrics] = []
    489 if self.process == Process.sequential:
--> 490     result = self._run_sequential_process()
    491 elif self.process == Process.hierarchical:
    492     result = self._run_hierarchical_process()

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/crew.py:594, in Crew._run_sequential_process(self)
    592 def _run_sequential_process(self) -> CrewOutput:
    593     \"\"\"Executes tasks sequentially and returns the final output.\"\"\"
--> 594     return self._execute_tasks(self.tasks)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/crew.py:692, in Crew._execute_tasks(self, tasks, start_index, was_replayed)
    689     futures.clear()
    691 context = self._get_context(task, task_outputs)
--> 692 task_output = task.execute_sync(
    693     agent=agent_to_use,
    694     context=context,
    695     tools=agent_to_use.tools,
    696 )
    697 task_outputs = [task_output]
    698 self._process_task_result(task, task_output)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/task.py:191, in Task.execute_sync(self, agent, context, tools)
    184 def execute_sync(
    185     self,
    186     agent: Optional[BaseAgent] = None,
    187     context: Optional[str] = None,
    188     tools: Optional[List[Any]] = None,
    189 ) -> TaskOutput:
    190     \"\"\"Execute the task synchronously.\"\"\"
--> 191     return self._execute_core(agent, context, tools)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/task.py:247, in Task._execute_core(self, agent, context, tools)
    243 tools = tools or self.tools or []
    245 self.processed_by_agents.add(agent.role)
--> 247 result = agent.execute_task(
    248     task=self,
    249     context=context,
    250     tools=tools,
    251 )
    253 pydantic_output, json_output = self._export_output(result)
    255 task_output = TaskOutput(
    256     name=self.name,
    257     description=self.description,
   (...)
    263     output_format=self._get_output_format(),
    264 )

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/agent.py:214, in Agent.execute_task(self, task, context, tools)
    208 if self.crew and self.crew.memory:
    209     contextual_memory = ContextualMemory(
    210         self.crew._short_term_memory,
    211         self.crew._long_term_memory,
    212         self.crew._entity_memory,
    213     )
--> 214     memory = contextual_memory.build_context_for_task(task, context)
    215     if memory.strip() != \"\":
    216         task_prompt += self.i18n.slice(\"memory\").format(memory=memory)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/memory/contextual/contextual_memory.py:24, in ContextualMemory.build_context_for_task(self, task, context)
     22 context = []
     23 context.append(self._fetch_ltm_context(task.description))
---> 24 context.append(self._fetch_stm_context(query))
     25 context.append(self._fetch_entity_context(query))
     26 return \"\
\".join(filter(None, context))

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/memory/contextual/contextual_memory.py:33, in ContextualMemory._fetch_stm_context(self, query)
     28 def _fetch_stm_context(self, query) -> str:
     29     \"\"\"
     30     Fetches recent relevant insights from STM related to the task's description and expected_output,
     31     formatted as bullet points.
     32     \"\"\"
---> 33     stm_results = self.stm.search(query)
     34     formatted_results = \"\
\".join([f\"- {result}\" for result in stm_results])
     35     return f\"Recent Insights:\
{formatted_results}\" if stm_results else \"\"

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/memory/short_term/short_term_memory.py:37, in ShortTermMemory.search(self, query, score_threshold)
     36 def search(self, query: str, score_threshold: float = 0.35):
---> 37     return self.storage.search(query=query, score_threshold=score_threshold)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/memory/storage/rag_storage.py:103, in RAGStorage.search(self, query, limit, filter, score_threshold)
     98 with suppress_logging():
     99     try:
    100         results = (
    101             self.app.search(query, limit, where=filter)
    102             if filter
--> 103             else self.app.search(query, limit)
    104         )
    105     except InvalidDimensionException:
    106         self.app.reset()

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/embedchain/embedchain.py:712, in EmbedChain.search(self, query, num_documents, where, raw_filter, namespace)
    701 filter_criteria = raw_filter if raw_filter else where
    703 params = {
    704     \"input_query\": query,
    705     \"n_results\": num_documents,
   (...)
    709     filter_type: filter_criteria,
    710 }
--> 712 return [{\"context\": c[0], \"metadata\": c[1]} for c in self.db.query(**params)]

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/embedchain/vectordb/chroma.py:220, in ChromaDB.query(self, input_query, n_results, where, raw_filter, citations, **kwargs)
    218     where_clause = self._generate_where_clause(where)
    219 try:
--> 220     result = self.collection.query(
    221         query_texts=[
    222             input_query,
    223         ],
    224         n_results=n_results,
    225         where=where_clause,
    226     )
    227 except InvalidDimensionException as e:
    228     raise InvalidDimensionException(
    229         e.message()
    230         + \". This is commonly a side-effect when an embedding function, different from the one used to add the\"
    231         \" embeddings, is used to retrieve an embedding from the database.\"
    232     ) from None

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/chromadb/api/models/Collection.py:327, in Collection.query(self, query_embeddings, query_texts, query_images, query_uris, n_results, where, where_document, include)
    325 if valid_query_embeddings is None:
    326     if query_texts is not None:
--> 327         valid_query_embeddings = self._embed(input=valid_query_texts)
    328     elif query_images is not None:
    329         valid_query_embeddings = self._embed(input=valid_query_images)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/chromadb/api/models/Collection.py:633, in Collection._embed(self, input)
    628 if self._embedding_function is None:
    629     raise ValueError(
    630         \"You must provide an embedding function to compute embeddings.\"
    631         \"https://docs.trychroma.com/embeddings\"
    632     )
--> 633 return self._embedding_function(input=input)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/chromadb/api/types.py:193, in EmbeddingFunction.__init_subclass__.<locals>.__call__(self, input)
    192 def __call__(self: EmbeddingFunction[D], input: D) -> Embeddings:
--> 193     result = call(self, input)
    194     return validate_embeddings(maybe_cast_one_to_many_embedding(result))

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/chromadb/utils/embedding_functions.py:188, in OpenAIEmbeddingFunction.__call__(self, input)
    186 # Call the OpenAI Embedding API
    187 if self._v1:
--> 188     embeddings = self._client.create(
    189         input=input, model=self._deployment_id or self._model_name
    190     ).data
    192     # Sort resulting embeddings by index
    193     sorted_embeddings = sorted(embeddings, key=lambda e: e.index)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/openai/resources/embeddings.py:124, in Embeddings.create(self, input, model, dimensions, encoding_format, user, extra_headers, extra_query, extra_body, timeout)
    118         embedding.embedding = np.frombuffer(  # type: ignore[no-untyped-call]
    119             base64.b64decode(data), dtype=\"float32\"
    120         ).tolist()
    122     return obj
--> 124 return self._post(
    125     \"/embeddings\",
    126     body=maybe_transform(params, embedding_create_params.EmbeddingCreateParams),
    127     options=make_request_options(
    128         extra_headers=extra_headers,
    129         extra_query=extra_query,
    130         extra_body=extra_body,
    131         timeout=timeout,
    132         post_parser=parser,
    133     ),
    134     cast_to=CreateEmbeddingResponse,
    135 )

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/openai/_base_client.py:1271, in SyncAPIClient.post(self, path, cast_to, body, options, files, stream, stream_cls)
   1257 def post(
   1258     self,
   1259     path: str,
   (...)
   1266     stream_cls: type[_StreamT] | None = None,
   1267 ) -> ResponseT | _StreamT:
   1268     opts = FinalRequestOptions.construct(
   1269         method=\"post\", url=path, json_data=body, files=to_httpx_files(files), **options
   1270     )
-> 1271     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/openai/_base_client.py:948, in SyncAPIClient.request(self, cast_to, options, remaining_retries, stream, stream_cls)
    945 else:
    946     retries_taken = 0
--> 948 return self._request(
    949     cast_to=cast_to,
    950     options=options,
    951     stream=stream,
    952     stream_cls=stream_cls,
    953     retries_taken=retries_taken,
    954 )

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/openai/_base_client.py:1052, in SyncAPIClient._request(self, cast_to, options, retries_taken, stream, stream_cls)
   1049         err.response.read()
   1051     log.debug(\"Re-raising status error\")
-> 1052     raise self._make_status_error_from_response(err.response) from None
   1054 return self._process_response(
   1055     cast_to=cast_to,
   1056     options=options,
   (...)
   1060     retries_taken=retries_taken,
   1061 )

AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: fake. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}"
}
```

### Operating System

Ubuntu 20.04

### Python Version

3.10

### crewAI Version

0.67.1

### crewAI Tools Version

0.12.1

### Virtual Environment

Conda

### Evidence

```
{
	"name": "AuthenticationError",
	"message": "Error code: 401 - {'error': {'message': 'Incorrect API key provided: fake. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}",
	"stack": "---------------------------------------------------------------------------
AuthenticationError                       Traceback (most recent call last)
Cell In[155], line 12
      1 inputs = {
      2     \"customer\": \"DeepLearningAI\",
      3     \"person\": \"Andrew Ng\",
   (...)
      7                \"Can you provide guidance?\"
      8 }
      9 # inputs = {
     10 #     'msg': 'Hello, my name is Luana'
     11 # }
---> 12 result = crew.kickoff(inputs=inputs)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/crew.py:490, in Crew.kickoff(self, inputs)
    487 metrics: List[UsageMetrics] = []
    489 if self.process == Process.sequential:
--> 490     result = self._run_sequential_process()
    491 elif self.process == Process.hierarchical:
    492     result = self._run_hierarchical_process()

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/crew.py:594, in Crew._run_sequential_process(self)
    592 def _run_sequential_process(self) -> CrewOutput:
    593     \"\"\"Executes tasks sequentially and returns the final output.\"\"\"
--> 594     return self._execute_tasks(self.tasks)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/crew.py:692, in Crew._execute_tasks(self, tasks, start_index, was_replayed)
    689     futures.clear()
    691 context = self._get_context(task, task_outputs)
--> 692 task_output = task.execute_sync(
    693     agent=agent_to_use,
    694     context=context,
    695     tools=agent_to_use.tools,
    696 )
    697 task_outputs = [task_output]
    698 self._process_task_result(task, task_output)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/task.py:191, in Task.execute_sync(self, agent, context, tools)
    184 def execute_sync(
    185     self,
    186     agent: Optional[BaseAgent] = None,
    187     context: Optional[str] = None,
    188     tools: Optional[List[Any]] = None,
    189 ) -> TaskOutput:
    190     \"\"\"Execute the task synchronously.\"\"\"
--> 191     return self._execute_core(agent, context, tools)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/task.py:247, in Task._execute_core(self, agent, context, tools)
    243 tools = tools or self.tools or []
    245 self.processed_by_agents.add(agent.role)
--> 247 result = agent.execute_task(
    248     task=self,
    249     context=context,
    250     tools=tools,
    251 )
    253 pydantic_output, json_output = self._export_output(result)
    255 task_output = TaskOutput(
    256     name=self.name,
    257     description=self.description,
   (...)
    263     output_format=self._get_output_format(),
    264 )

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/agent.py:214, in Agent.execute_task(self, task, context, tools)
    208 if self.crew and self.crew.memory:
    209     contextual_memory = ContextualMemory(
    210         self.crew._short_term_memory,
    211         self.crew._long_term_memory,
    212         self.crew._entity_memory,
    213     )
--> 214     memory = contextual_memory.build_context_for_task(task, context)
    215     if memory.strip() != \"\":
    216         task_prompt += self.i18n.slice(\"memory\").format(memory=memory)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/memory/contextual/contextual_memory.py:24, in ContextualMemory.build_context_for_task(self, task, context)
     22 context = []
     23 context.append(self._fetch_ltm_context(task.description))
---> 24 context.append(self._fetch_stm_context(query))
     25 context.append(self._fetch_entity_context(query))
     26 return \"\
\".join(filter(None, context))

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/memory/contextual/contextual_memory.py:33, in ContextualMemory._fetch_stm_context(self, query)
     28 def _fetch_stm_context(self, query) -> str:
     29     \"\"\"
     30     Fetches recent relevant insights from STM related to the task's description and expected_output,
     31     formatted as bullet points.
     32     \"\"\"
---> 33     stm_results = self.stm.search(query)
     34     formatted_results = \"\
\".join([f\"- {result}\" for result in stm_results])
     35     return f\"Recent Insights:\
{formatted_results}\" if stm_results else \"\"

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/memory/short_term/short_term_memory.py:37, in ShortTermMemory.search(self, query, score_threshold)
     36 def search(self, query: str, score_threshold: float = 0.35):
---> 37     return self.storage.search(query=query, score_threshold=score_threshold)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/crewai/memory/storage/rag_storage.py:103, in RAGStorage.search(self, query, limit, filter, score_threshold)
     98 with suppress_logging():
     99     try:
    100         results = (
    101             self.app.search(query, limit, where=filter)
    102             if filter
--> 103             else self.app.search(query, limit)
    104         )
    105     except InvalidDimensionException:
    106         self.app.reset()

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/embedchain/embedchain.py:712, in EmbedChain.search(self, query, num_documents, where, raw_filter, namespace)
    701 filter_criteria = raw_filter if raw_filter else where
    703 params = {
    704     \"input_query\": query,
    705     \"n_results\": num_documents,
   (...)
    709     filter_type: filter_criteria,
    710 }
--> 712 return [{\"context\": c[0], \"metadata\": c[1]} for c in self.db.query(**params)]

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/embedchain/vectordb/chroma.py:220, in ChromaDB.query(self, input_query, n_results, where, raw_filter, citations, **kwargs)
    218     where_clause = self._generate_where_clause(where)
    219 try:
--> 220     result = self.collection.query(
    221         query_texts=[
    222             input_query,
    223         ],
    224         n_results=n_results,
    225         where=where_clause,
    226     )
    227 except InvalidDimensionException as e:
    228     raise InvalidDimensionException(
    229         e.message()
    230         + \". This is commonly a side-effect when an embedding function, different from the one used to add the\"
    231         \" embeddings, is used to retrieve an embedding from the database.\"
    232     ) from None

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/chromadb/api/models/Collection.py:327, in Collection.query(self, query_embeddings, query_texts, query_images, query_uris, n_results, where, where_document, include)
    325 if valid_query_embeddings is None:
    326     if query_texts is not None:
--> 327         valid_query_embeddings = self._embed(input=valid_query_texts)
    328     elif query_images is not None:
    329         valid_query_embeddings = self._embed(input=valid_query_images)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/chromadb/api/models/Collection.py:633, in Collection._embed(self, input)
    628 if self._embedding_function is None:
    629     raise ValueError(
    630         \"You must provide an embedding function to compute embeddings.\"
    631         \"https://docs.trychroma.com/embeddings\"
    632     )
--> 633 return self._embedding_function(input=input)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/chromadb/api/types.py:193, in EmbeddingFunction.__init_subclass__.<locals>.__call__(self, input)
    192 def __call__(self: EmbeddingFunction[D], input: D) -> Embeddings:
--> 193     result = call(self, input)
    194     return validate_embeddings(maybe_cast_one_to_many_embedding(result))

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/chromadb/utils/embedding_functions.py:188, in OpenAIEmbeddingFunction.__call__(self, input)
    186 # Call the OpenAI Embedding API
    187 if self._v1:
--> 188     embeddings = self._client.create(
    189         input=input, model=self._deployment_id or self._model_name
    190     ).data
    192     # Sort resulting embeddings by index
    193     sorted_embeddings = sorted(embeddings, key=lambda e: e.index)

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/openai/resources/embeddings.py:124, in Embeddings.create(self, input, model, dimensions, encoding_format, user, extra_headers, extra_query, extra_body, timeout)
    118         embedding.embedding = np.frombuffer(  # type: ignore[no-untyped-call]
    119             base64.b64decode(data), dtype=\"float32\"
    120         ).tolist()
    122     return obj
--> 124 return self._post(
    125     \"/embeddings\",
    126     body=maybe_transform(params, embedding_create_params.EmbeddingCreateParams),
    127     options=make_request_options(
    128         extra_headers=extra_headers,
    129         extra_query=extra_query,
    130         extra_body=extra_body,
    131         timeout=timeout,
    132         post_parser=parser,
    133     ),
    134     cast_to=CreateEmbeddingResponse,
    135 )

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/openai/_base_client.py:1271, in SyncAPIClient.post(self, path, cast_to, body, options, files, stream, stream_cls)
   1257 def post(
   1258     self,
   1259     path: str,
   (...)
   1266     stream_cls: type[_StreamT] | None = None,
   1267 ) -> ResponseT | _StreamT:
   1268     opts = FinalRequestOptions.construct(
   1269         method=\"post\", url=path, json_data=body, files=to_httpx_files(files), **options
   1270     )
-> 1271     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/openai/_base_client.py:948, in SyncAPIClient.request(self, cast_to, options, remaining_retries, stream, stream_cls)
    945 else:
    946     retries_taken = 0
--> 948 return self._request(
    949     cast_to=cast_to,
    950     options=options,
    951     stream=stream,
    952     stream_cls=stream_cls,
    953     retries_taken=retries_taken,
    954 )

File ~/miniconda3/envs/myenv/lib/python3.11/site-packages/openai/_base_client.py:1052, in SyncAPIClient._request(self, cast_to, options, retries_taken, stream, stream_cls)
   1049         err.response.read()
   1051     log.debug(\"Re-raising status error\")
-> 1052     raise self._make_status_error_from_response(err.response) from None
   1054 return self._process_response(
   1055     cast_to=cast_to,
   1056     options=options,
   (...)
   1060     retries_taken=retries_taken,
   1061 )

AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: fake. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}"
}
```

### Possible Solution

None

### Additional context

-

**Comment by omarnahdi** [comment]
@httplups Huhhh.... Please don't provide such long comment, keep it simple, use proper annotations and provide a summary at the end. Anyways here's a solution to it

``` python
crew = Crew(
    agents=[Support_Agent, Support_Quality_Assurance_Agent],
    tasks=[inquiry,quality_assurance_review],
    verbose=True,
    memory=True,
    embedder={
        "provider": "openai",
        "config": {
            "api_key": GEMINI_API_KEY,
            "model_name": "model/text-embedding-004"
        }
    }
)
```
