### ISSUE TITLE
[BUG] CrewAI course: Automating Event Planning lab is broken. 

### ISSUE THREAD

**Issue by ianbruton** [crewAIInc/crewAI#1421]
### Description

screenshot from the lab environment within the course

![image](https://github.com/user-attachments/assets/45b50484-1bbe-4d43-bff3-4ec52014b24f)

running the code locally gives a different error ( I did not alter any of the agents, or tasks:

### Steps to Reproduce

1. do the training course at : https://learn.deeplearning.ai/courses/multi-ai-agent-systems-with-crewai/lesson/12/automate-event-planning-(code)

### Expected behavior

the lab to work

### Screenshots/Code snippets

it's your code

### Operating System

macOS Sonoma

### Python Version

3.10

### crewAI Version

0.64.0

### crewAI Tools Version

0.12.1

### Virtual Environment

Poetry

### Evidence

`❯ python lab_4.py
website_url: None
Traceback (most recent call last):
  File "/Users/ian/Documents/personal/multi_agent_poc/ian_test/crewai/v12.py", line 131, in <module>
    event_management_crew = Crew(
                            ^^^^^
  File "/Users/ian/Documents/personal/multi_agent_poc/ian_test/.venv/lib/python3.11/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Crew
  The crew must end with at most one asynchronous task. [type=async_task_count, input_value={'agents': [Agent(role=Ve...wn.
)], 'verbose': True}, input_type=dict]`

### Possible Solution

i don't know???

### Additional context

none

**Comment by vinodvpillai** [comment]
Faced the same issue it only works with single asynchronous task as mentioned in the error message. 
As per my understanding running multiple tasks asynchronously within a single Crew could create significant complexity in coordinating task completions, handling dependencies between them, and meaningfully aggregating results.

**Comment by ciscofu** [comment]
The issue is that there cannot be multiple outstanding asynchronous tasks active when the "pipeline" ends. Whenever there is a non-synchronous tasks in the list, any pending asynchronous tasks are completed before the synchronous task is run. The idea is that there should always be a synchronous task to correlate the findings of all the other tasks. Regardless, simply make the last task (marketing_task) synchronous. That will get rid of the error.
