### ISSUE TITLE
[BUG] Broken Link in 'Deploying Your Project' Section

### ISSUE THREAD

**Issue by GauriTr** [crewAIInc/crewAI#1427]
### Description

In the documentation for the "Deploying Your Project" section, the link to "CrewAI Enterprise" is broken. Clicking the link does not direct to the intended page.

### Steps to Reproduce

1. Go to the documentation page: https://docs.crewai.com/quickstart#deploying-your-project.
2. Scroll to the "Deploying Your Project" section.
3. Click on the "CrewAI Enterprise" link.
4. The link leads to a broken or invalid page.

### Expected behavior

The "CrewAI Enterprise" link should direct the user to a valid page where the project can be deployed.

### Screenshots/Code snippets

![image](https://github.com/user-attachments/assets/139179dc-68cd-4aaf-b9b2-7973a6aacfe8)

### Operating System

Ubuntu 24.04

### Python Version

3.11

### crewAI Version

0.70.1

### crewAI Tools Version

0.12.1

### Virtual Environment

Venv

### Evidence

![image](https://github.com/user-attachments/assets/78b8ae44-c552-4710-bab8-6ff1339d9ba5)

### Possible Solution

Update the "CrewAI Enterprise" link to point to the correct URL.

### Additional context

None,

**Comment by theCyberTech** [comment]
This was probably due to our migration to a new docs environment - this is now resolved
