### ISSUE TITLE
[BUG] Langchain discrepancy between crewai and crewai-tools

### ISSUE THREAD

**Issue by jerryrinaldo** [crewAIInc/crewAI#1442]
### Description

I am installing both crewai and crewai-tools by placing them in a requirements.txt file. I am installing the latest versions of both crewai and crewai-tools 

`crewai==0.70.1
crewai-tools==0.12.1`

I am not able to install them as there is a langchain discrepancy between both the packages.

`crewai 0.70.1 depends on langchain<0.3.0 and >=0.2.16
crewai-tools depends on langchain<=0.3 and >0.2
embedchain 0.1.123 depends on langchain<0.4.0 and >=0.3.1`

The versions that I am able to install without any conflicting dependencies is crewai==0.51.1 and crewai-tools==0.8.3

### Steps to Reproduce

1. Have a requirements .txt file with the following crewai==0.70.1 and crewai-tools==0.12.1.
2. pip install -r requirements.txt

### Expected behavior

This conflicting dependencies occurs,
`crewai 0.70.1 depends on langchain<0.3.0 and >=0.2.16
crewai-tools depends on langchain<=0.3 and >0.2
embedchain 0.1.123 depends on langchain<0.4.0 and >=0.3.1`

### Screenshots/Code snippets

NA

### Operating System

Windows 10

### Python Version

3.10

### crewAI Version

0.70.1

### crewAI Tools Version

0.12.1

### Virtual Environment

Venv

### Evidence

NA

### Possible Solution

None

### Additional context

Na

**Comment by pythonbyte** [comment]
Thanks for letting us know @jerryrinaldo 
A PR on Tools was added to address this issue
https://github.com/crewAIInc/crewAI-tools/pull/111/files

**Comment by ME-Msc** [comment]
Is it solved?

**Comment by zinyando** [comment]
@ME-Msc crewai-tools latest version is still `0.12.1` according to https://pypi.org/project/crewai-tools/, `v0.13.0` hasn't been released yet.

**Comment by ME-Msc** [comment]
Yes. I am asking for v0.13.0 of crewai-tools mentioned in [https://github.com/crewAIInc/crewAI-tools/pull/111/files](https://github.com/crewAIInc/crewAI-tools/pull/111/files).
I noticed that it has been merged as v0.13.0 (shown in the following link), but has not been released on pypi yet.

https://github.com/crewAIInc/crewAI-tools/commit/e443e342ce6bbb47c4bbfc67cba0133429e9408b#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R3
