### ISSUE TITLE
[BUG] Dependcies compatible problem

### ISSUE THREAD

**Issue by venkatace** [crewAIInc/crewAI#1443]
### Description

ERROR: Ignored the following versions that require a different python version: 0.0.74 Requires-Python >=3.9,<3.13; 0.0.75 Requires-Python >=3.9,<3.13; 0.0.76 Requires-Python >=3.9,<3.13; 0.0.77 Requires-Python >=3.9,<3.13; 0.0.78 Requires-Python >=3.9,<3.13; 0.0.79 Requires-Python >=3.9,<3.13; 0.0.80 Requires-Python >=3.9,<3.13; 0.0.81 Requires-Python >=3.9,<3.13; 0.0.82 Requires-Python >=3.9,<3.13; 0.0.82rc8 Requires-Python >=3.9,<3.13; 0.0.82rc9 Requires-Python >=3.9,<3.13; 0.0.83 Requires-Python >=3.9,<3.13; 0.0.84 Requires-Python >=3.9,<3.13; 0.0.85 Requires-Python >=3.9,<3.13; 0.0.86 Requires-Python >=3.9,<3.13; 0.0.87 Requires-Python >=3.9,<3.13; 0.0.88 Requires-Python >=3.9,<3.13; 0.0.89 Requires-Python >=3.9,<3.13; 0.0.90 Requires-Python >=3.9,<3.13; 0.0.91 Requires-Python >=3.9,<3.13; 0.0.92 Requires-Python >=3.9,<3.13; 0.1.0 Requires-Python >=3.9,<3.12; 0.1.0rc1 Requires-Python >=3.9,<3.13; 0.1.1 Requires-Python >=3.9,<3.12; 0.1.10 Requires-Python >=3.9,<3.12; 0.1.11 Requires-Python >=3.9,<3.12; 0.1.12 Requires-Python >=3.9,<3.12; 0.1.13 Requires-Python >=3.9,<3.12; 0.1.14 Requires-Python >=3.9,<3.12; 0.1.15 Requires-Python >=3.9,<3.12; 0.1.16 Requires-Python >=3.9,<3.12; 0.1.17 Requires-Python >=3.9,<3.12; 0.1.18 Requires-Python >=3.9,<3.12; 0.1.19 Requires-Python >=3.9,<3.12; 0.1.19a1 Requires-Python >=3.9,<3.12; 0.1.19a2 Requires-Python >=3.9,<3.12; 0.1.19a3 Requires-Python >=3.9,<3.12; 0.1.19a4 Requires-Python >=3.9,<3.12; 0.1.19a5 Requires-Python >=3.9,<3.12; 0.1.2 Requires-Python >=3.9,<3.12; 0.1.20a1 Requires-Python >=3.9,<3.12; 0.1.21 Requires-Python >=3.9,<3.12; 0.1.22 Requires-Python >=3.9,<3.12; 0.1.23 Requires-Python >=3.9,<3.12; 0.1.24 Requires-Python >=3.9,<3.12; 0.1.25 Requires-Python >=3.9,<3.12; 0.1.26 Requires-Python >=3.9,<3.12; 0.1.27 Requires-Python >=3.9,<3.12; 0.1.28 Requires-Python >=3.9,<3.12; 0.1.3 Requires-Python >=3.9,<3.12; 0.1.30 Requires-Python >=3.9,<3.12; 0.1.31 Requires-Python >=3.9,<3.12; 0.1.33 Requires-Python >=3.9,<3.12; 0.1.34 Requires-Python >=3.9,<3.12; 0.1.35 Requires-Python >=3.9,<3.12; 0.1.36 Requires-Python >=3.9,<3.12; 0.1.37 Requires-Python >=3.9,<3.12; 0.1.38 Requires-Python >=3.9,<3.12; 0.1.39 Requires-Python >=3.9,<3.12; 0.1.4 Requires-Python >=3.9,<3.12; 0.1.40 Requires-Python >=3.9,<3.12; 0.1.41 Requires-Python >=3.9,<3.12; 0.1.41a0 Requires-Python >=3.9,<3.12; 0.1.41a1 Requires-Python >=3.9,<3.12; 0.1.42 Requires-Python >=3.9,<3.12; 0.1.43 Requires-Python >=3.9,<3.12; 0.1.44 Requires-Python >=3.9,<3.12; 0.1.45 Requires-Python >=3.9,<3.12; 0.1.45a0 Requires-Python >=3.9,<3.12; 0.1.46 Requires-Python >=3.9,<3.12; 0.1.47 Requires-Python >=3.9,<3.12; 0.1.48 Requires-Python >=3.9,<3.12; 0.1.49 Requires-Python >=3.9,<3.12; 0.1.5 Requires-Python >=3.9,<3.12; 0.1.50 Requires-Python >=3.9,<3.12; 0.1.51 Requires-Python >=3.9,<3.12; 0.1.52 Requires-Python >=3.9,<3.12; 0.1.52a0 Requires-Python >=3.9,<3.12; 0.1.53 Requires-Python >=3.9,<3.12; 0.1.54 Requires-Python >=3.9,<3.12; 0.1.55 Requires-Python >=3.9,<3.12; 0.1.55a0 Requires-Python >=3.9,<3.12; 0.1.55a1 Requires-Python >=3.9,<=3.12; 0.1.55a2 Requires-Python >=3.9,<=3.12.1; 0.1.55a3 Requires-Python >=3.9,<=3.12.1; 0.1.56 Requires-Python >=3.9,<3.12; 0.1.57 Requires-Python >=3.9,<3.12; 0.1.58 Requires-Python >=3.9,<3.12; 0.1.59 Requires-Python >=3.9,<3.12; 0.1.59a0 Requires-Python >=3.9,<3.12; 0.1.6 Requires-Python >=3.9,<3.12; 0.1.60 Requires-Python >=3.9,<3.12; 0.1.61 Requires-Python >=3.9,<3.12; 0.1.61a0 Requires-Python >=3.9,<3.12; 0.1.62 Requires-Python >=3.9,<3.12; 0.1.63 Requires-Python >=3.9,<3.12; 0.1.64 Requires-Python >=3.9,<3.12; 0.1.65 Requires-Python >=3.9,<3.12; 0.1.66 Requires-Python >=3.9,<3.12; 0.1.67 Requires-Python >=3.9,<3.12; 0.1.68 Requires-Python >=3.9,<3.12; 0.1.69 Requires-Python >=3.9,<3.12; 0.1.7 Requires-Python >=3.9,<3.12; 0.1.70 Requires-Python >=3.9,<3.12; 0.1.71 Requires-Python >=3.9,<3.12; 0.1.72 Requires-Python >=3.9,<3.12; 0.1.73 Requires-Python >=3.9,<3.12; 0.1.74 Requires-Python >=3.9,<3.12; 0.1.75 Requires-Python >=3.9,<3.12; 0.1.76 Requires-Python >=3.9,<3.12; 0.1.77 Requires-Python >=3.9,<3.12; 0.1.77a0 Requires-Python >=3.9,<3.12; 0.1.77a1 Requires-Python >=3.9,<3.12; 0.1.77a2 Requires-Python >=3.9,<3.12; 0.1.78 Requires-Python >=3.9,<3.12; 0.1.79 Requires-Python >=3.9,<3.12; 0.1.8 Requires-Python >=3.9,<3.12; 0.1.80 Requires-Python >=3.9,<3.12; 0.1.81 Requires-Python >=3.9,<3.12; 0.1.81a0 Requires-Python >=3.9,<3.12; 0.1.9 Requires-Python >=3.9,<3.12; 0.14.0rc0 Requires-Python >=3.10,<3.12; 0.5.12 Requires-Python >=3.7,<3.12; 0.5.13 Requires-Python >=3.7,<3.12; 0.5.14 Requires-Python >=3.7,<3.13; 0.6.2 Requires-Python >=2.7.0.0,<2.8.0.0,>=3.4.0.0,<4.0.0.0; 0.6.3 Requires-Python >=2.7.0.0,<2.8.0.0,>=3.4.0.0,<4.0.0.0; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.1 Requires-Python <3.13,>=3.9; 4.0.0 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement pulsar-client>=3.1.0 (from chromadb) (from versions: none)
ERROR: No matching distribution found for pulsar-client>=3.1.0

### Steps to Reproduce

pip install crewai

### Expected behavior

It is supposed to install the crewai but citing the version incompatibility of dependent tools, it throwe the Error. 

### Screenshots/Code snippets

![image](https://github.com/user-attachments/assets/8149a487-16c2-4d86-9333-6e7bb42c1138)

### Operating System

Windows 11

### Python Version

3.13

### crewAI Version

Not sure as it failed installing midway

### crewAI Tools Version

Not sure

### Virtual Environment

Venv

### Evidence

Help me to rectify the errors generated by CrewAI dependencies incompatibility

### Possible Solution

None

### Additional context

None

**Comment by pythonbyte** [comment]
Thanks for letting us know @venkatace 
A PR on Tools was added to address this issue
https://github.com/crewAIInc/crewAI-tools/pull/111/files

**Comment by jessicalhammond** [comment]
experiencing the same

**Comment by michaeljones1** [comment]
Ignore me if the PR resolves this. It's a python 3.13 pulsar-client problem. "pip install puslar-client" or whatever the command is will not work. 

Reverting to python 3.12 allowed me to install crewai and pulsar-client with no problems.

**Comment by voytas75** [comment]
the crewai team probably uses `pulsar-client` that is modified

**Comment by fahim9778** [comment]
> Thanks for letting us know @venkatace A PR on Tools was added to address this issue https://github.com/crewAIInc/crewAI-tools/pull/111/files

Please let us know if this issue is fixed for Python 3.13

**Comment by fahim9778** [comment]
> Ignore me if the PR resolves this. It's a python 3.13 pulsar-client problem. "pip install puslar-client" or whatever the command is will not work.
> 
> Reverting to python 3.12 allowed me to install crewai and pulsar-client with no problems.

I am facing the same issue and reverted to Python 3.12.7.  Are you using this specific version too? Also, Are you on Windows 10?  I am now trying to install it with `pip install crewai` (wish me luck please).

**Comment by MorenoLabs** [comment]
running crewai install on 3.12.7 fails now with chroma error

**Comment by voytas75** [comment]
it worked but with env set
PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
