### ISSUE TITLE
[BUG] Unsupported data type when using PDFSearchTool

### ISSUE THREAD

**Issue by sorin-costea** [crewAIInc/crewAI#1448]
### Description

I get this error:
```
I encountered an error while trying to use the tool. This was the error: Unsupported data type.
 Tool Search a PDF's content accepts these inputs: Search a PDF's content(query: 'string') - A tool that can be used to semantic search a query the my.pdf PDF's content. query: 'Mandatory query you want to use to search the PDF's content'
# Agent: Researcher...
## Thought: In order to ...
## Using tool: Search a PDF's content
## Tool Input:
"{\"query\": \"key skills and qualifications\"}"
```

### Steps to Reproduce

The code I use is (fluff removed for clarity):
```
from crewai_tools import PDFSearchTool
my_file_tool = PDFSearchTool(config=azure_config, pdf='my.pdf')
my_researcher = Agent(
    role="Researcher...",
    goal="Make sure to...",
    backstory=("As a..."),
    tools=[job_file_tool],
    ...
)
my_task = Task(
    description=("Analyze..."),
    agent=my_researcher,
    tools=[my_file_tool],
    ...
)
crew_test = Crew(
    agents=[my_researcher],
    tasks=[my_task],
    process=Process.sequential,
    full_output=True,
    verbose=True
)

```

### Expected behavior

As I cannot influence the format of what the agent sends to the tools, I'd expect the agent would send properly query=string. Could it be the config=... is messing up things?

### Screenshots/Code snippets

The error is in the description above

### Operating System

Windows 11

### Python Version

3.12

### crewAI Version

0.67.1

### crewAI Tools Version

0.12.1

### Virtual Environment

Poetry

### Evidence

The error is in the description above

### Possible Solution

None

### Additional context

Same behaviour when I use the DOCXSearchTool, so there's either something I completely misunderstand, or worse.

**Comment by mrSingh007** [comment]
Facing the same issue in gemini:
```
pdf_search_tool = PDFSearchTool(pdf="folder/Most_Admired_Wine.pdf", config=dict(
        embedder=dict(provider="google", config=dict(model="models/gemini-1.5-flash"))
    ))

...
	@agent
	def wine_tester(self) -> Agent:
		return Agent(
			config=self.agents_config['wine_tester'],
			verbose=True,
			llm='gemini/gemini-pro',
			tools=[pdf_search_tool]
		)

```
and error
```
I encountered an error while trying to use the tool. This was the error: 400 * BatchEmbedContentsRequest.model: unexpected model name format
* BatchEmbedContentsRequest.requests[0].model: unexpected model name format
.
 Tool Search a PDF's content accepts these inputs: Search a PDF's content(query: 'string') - A tool that can be used to semantic search a query the data-base/Most_Admired_Wine.pdf PDF's content. query: 'Mandatory query you want to use to search the PDF's content'
```

**Comment by sorin-costea** [comment]
@mrSingh007 your error message is different. Are you sure your model name (deployment) is correct?

**Comment by sorin-costea** [comment]
I can confirm that it happens only with Azure. If I switch to OpenAI, there's no need for a config dict, and everything works just fine.

**Comment by sorin-costea** [comment]
Excuse the silly question, but is it that the agents have to _**learn**_ the tools parameters, so the first tries will usually be random???
