### ISSUE TITLE
[FEATURE] Support for creating CrewAI projects using uv instead of poetry

### ISSUE THREAD

**Issue by arthursn** [crewAIInc/crewAI#1450]
### Feature Area

Other (please specify in additional context)

### Is your feature request related to a an existing bug? Please link it here.

NA

### Description

Currently, Crewai uses `Poetry` for project creation and dependency management. While `Poetry` is a robust tool, I propose adding support for [`uv`](https://docs.astral.sh/uv) as an alternative option for creating Crewai projects.

### Proposed Change

Introduce the ability to create Crewai projects using `uv` in addition to the existing `Poetry` setup. This would allow users to choose their preferred tool based on their specific needs. That could be done, for example, with a command such as:

```
crewai create crew <my_project> --package-manager uv
```

### Benefits

- **Faster Dependency Resolution**: `uv` resolves dependencies approximately 10 times faster than `Poetry`, significantly reducing setup time.
- **Flexibility**: Offering `uv` as an option provides users with more flexibility and choice in their development workflow.
- **Performance**: Improved performance in dependency management can lead to a more efficient development process.

### Use Cases

- Projects with large and complex dependency trees that require faster resolution times.
- Development environments where speed and efficiency are critical.
- Teams that prefer `uv` for its performance benefits but still want to use Crewai.

### Impact

- **Minimal Disruption**: This change would not deprecate the current `Poetry` solution, ensuring that existing workflows remain unaffected.
- **Optional Adoption**: Users can opt to use `uv` based on their preference, making the transition smooth and voluntary.

### Describe alternatives you've considered

I've manually migrated some of my Crewai projects to `uv`, but `crewai run` runs `poetry run run_crew`, which is a small nuisance.
I can run them with `uv run <my_script>`, or simply importing the crew class in a notebook.

### Willingness to Contribute

Yes, I'd be happy to submit a pull request

**Comment by tonykipkemboi** [comment]
Thank you for the suggestion. We are actually merging this tomorrow. We've been working on this migration the past few weeks!
