### ISSUE TITLE
[BUG]Azure API key not working for the crewAI agent workflow

### ISSUE THREAD

**Issue by hliuci** [crewAIInc/crewAI#1452]
### Description

Hi, I am testing a simple agent using crewAI. My region (Hong Kong) doesn't support openAI so I am using Azure open AI. But it seems that it doesn't work for crewAI. There is no problem if I use the Azure API settings in other programs like having chats without crewAI. 

### Steps to Reproduce

Error appears when I run the codes.

### Expected behavior

The crewAI agent workflow works.

### Screenshots/Code snippets

Code:
`
import chainlit as cl
from chainlit import run_sync
from crewai import Agent, Task, Crew
from crewai_tools import tool
import os
from langchain_openai import AzureChatOpenAI

azure_api_key = "..."
azure_endpoint = "https://...-openai-evaluation-2.openai.azure.com/"
azure_api_version = "2024-02-15-preview"

OpenAI_LLM_name = "gpt-4-1106-preview" 

os.environ["OPENAI_API_VERSION"] = azure_api_version 
os.environ["AZURE_OPENAI_ENDPOINT"] = azure_endpoint
os.environ["AZURE_OPENAI_API_KEY"] = azure_api_key

os.environ["AZURE_OPENAI_VERSION"] = azure_api_version 
os.environ["AZURE_OPENAI_DEPLOYMENT"] = OpenAI_LLM_name
os.environ["AZURE_OPENAI_KEY"] = azure_api_key

os.environ["AZURE_API_KEY"] = azure_api_key
os.environ["AZURE_API_BASE"] = azure_endpoint
os.environ["AZURE_API_VERSION"] = azure_api_version

llm_chat = AzureChatOpenAI(
    azure_endpoint=azure_endpoint,
    azure_deployment=OpenAI_LLM_name,
    openai_api_version=azure_api_version,
)

@tool("Ask Human follow up questions")
def ask_human(question: str) -> str:
    """Ask human follow up questions"""
    human_response  = run_sync( cl.AskUserMessage(content=f"{question}").send())
    if human_response:
        return human_response["output"]
    
extractor = Agent(
    role='Expert Data Extractor',
    goal='Extract key data from human interaction',
    backstory="""You work at a Data Retrieval Office.
Your expertise lies in extracting facts and data of your need from short incomplete human conversations.
... and ask important follow up questions to extract key data while talking to humans.
You talk with human ... you ask follow up questions to human based on what you need next.
.....
""",
    # verbose=True,
    allow_delegation=False,
    llm=llm_chat,
    tools= [ask_human]
)

task = Task(
    description="""Extract key information from User communication and represent the final extracted  data as JSON""",
    expected_output="All Extracted data in JSON with no extra text only JSON",
    agent=extractor
)

crew = Crew(
    agents=[extractor],
    tasks=[task],
    verbose=True, 
)
crew.kickoff()
`

### Operating System

Windows 11

### Python Version

3.10

### crewAI Version

0.70.1

### crewAI Tools Version

0.12.1

### Virtual Environment

Venv

### Evidence

Error:
`
12:20:45 - LiteLLM:INFO: utils.py:2790 - 
LiteLLM completion() model= gpt-4-1106-preview; provider = openai
# Agent: Expert Data Extractor
## Task: Extract key information from User communication and represent the final extracted  data as JSON
2024-10-16 12:20:45 - 
LiteLLM completion() model= gpt-4-1106-preview; provider = openai
2024-10-16 12:20:45 - LiteLLM call failed: litellm.AuthenticationError: AuthenticationError: OpenAIException - The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
12:20:45 - LiteLLM:INFO: utils.py:2790 - 
LiteLLM completion() model= gpt-4-1106-preview; provider = openai
# Agent: Expert Data Extractor
## Task: Extract key information from User communication and represent the final extracted  data as JSON
2024-10-16 12:20:45 - 
LiteLLM completion() model= gpt-4-1106-preview; provider = openai
2024-10-16 12:20:45 - LiteLLM call failed: litellm.AuthenticationError: AuthenticationError: OpenAIException - The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
12:20:45 - LiteLLM:INFO: utils.py:2790 - 
LiteLLM completion() model= gpt-4-1106-preview; provider = openai
# Agent: Expert Data Extractor
## Task: Extract key information from User communication and represent the final extracted  data as JSON
2024-10-16 12:20:45 - 
LiteLLM completion() model= gpt-4-1106-preview; provider = openai
2024-10-16 12:20:45 - LiteLLM call failed: litellm.AuthenticationError: AuthenticationError: OpenAIException - The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
`

### Possible Solution

None.

### Additional context

None.

**Comment by theCyberTech** [comment]
Please see our docs on our move away from langchain, we use LiteLLM instead now

https://docs.crewai.com/concepts/llms

Also I recommend you rebuild your crew with the ```crewai create crew``` command

https://docs.crewai.com/quickstart

**Comment by ann22** [comment]
> [@theCyberTech](https://github.com/theCyberTech) Thank you!

Is your Azure open AI working? I also encountered this problem and LLM didn't solve it.
