### ISSUE TITLE
[FEATURE] Pass a custom model to an Agent

### ISSUE THREAD

**Issue by Rhuax** [crewAIInc/crewAI#1457]
### Feature Area

Agent capabilities

### Is your feature request related to a an existing bug? Please link it here.

Hi, is it possible to use a custom LLM with crew AI? I mean, passing a custom class that calls in a custom way an LLM (not passing openAI compatible APIs).
I saw it is possible with other similar libraries.

### Describe the solution you'd like

.

### Willingness to Contribute

No, I'm just suggesting the idea

**Comment by tonykipkemboi** [comment]
Do you have an example of a custom LLM you want to configure? This might help us understand what your need better.

**Comment by Rhuax** [comment]
Hi, I ended up letting my classes inherit from the LLM class of CrewAI + implementing the `call` method. I think we can close it
