### ISSUE TITLE
[BUG] Docs Pipeline documentation is removed  

### ISSUE THREAD

**Issue by ketangangal** [crewAIInc/crewAI#1460]
### Description

Pipeline docs is removed is that feature deprecated ?

![image](https://github.com/user-attachments/assets/570cb11f-1f50-43f2-8300-be66834b974a)
 
![image](https://github.com/user-attachments/assets/e5079186-dbaa-40de-b0ca-a65313172b7a)

### Steps to Reproduce

NA

### Expected behavior

NA

### Screenshots/Code snippets

NA

### Operating System

Ubuntu 20.04

### Python Version

3.10

### crewAI Version

NA

### crewAI Tools Version

NA

### Virtual Environment

Venv

### Evidence

NA

### Possible Solution

NA

### Additional context

NA

**Comment by voytas75** [comment]
yeah i noticed it yesterday bc i started learn this :) only web search show me the place.

**Comment by zinyando** [comment]
Pipelines were deprecated in favor of Flows. It was done in this PR https://github.com/crewAIInc/crewAI/pull/1451

There needs to be some form of announcement or deprecation process so that users are not impacted. @tonykipkemboi @joaomdmoura

**Comment by ketangangal** [comment]
Thanks
