### ISSUE TITLE
[BUG] Logs are not displayed during async kickoff

### ISSUE THREAD

**Issue by 11bluetree** [crewAIInc/crewAI#1462]
### Description

Hi,

- agent setting: verbose=True
- crew setting: verbose=True

When the above logging settings are enabled, logs are displayed in the terminal when running the normal kickoff method. However, when using kickoff_async or kickoff_for_each_async, no execution logs are displayed at all. I would like to see the logs for debugging purposes, so I would appreciate it if you could explain the cause and provide a solution.

Kind regards,

### Steps to Reproduce

1. change execute kickoff to kickoff_async or kickoff_for_each_async

### Expected behavior

All log statements should be printed, showing the start and end of each task. Regardless of whether the method is synchronous or asynchronous, verbose logs should be displayed.

### Screenshots/Code snippets

none

### Operating System

macOS Sonoma

### Python Version

3.12

### crewAI Version

0.70.1

### crewAI Tools Version

0.12.1

### Virtual Environment

Poetry

### Evidence

none

### Possible Solution

none

### Additional context

none

**Comment by shivtej-opsverse** [comment]
@11bluetree I have the same issue. Did you manage to figure out why this happens?

**Comment by 11bluetree** [comment]
@shivtej-opsverse no 😶‍🌫️
i suspect that crewai override litellm's log level.
