### ISSUE TITLE
No module named 'tomllib' when updating crewai

### ISSUE THREAD

**Issue by ernestp** [crewAIInc/crewAI#1471]
### Description

crewai update throw error: ModuleNotFoundError: No module named 'tomllib'

Apple M1 Max
macOS 15.0.1 (24A348)
Python 3.10.15
conda 4.9.2

### Steps to Reproduce

crewai update

### Expected behavior

crewai updated

### Screenshots/Code snippets

(openai) user@Mac crewai_new % **pip install --upgrade crewai crewai-tools**
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: crewai in /Users/user/miniconda4/envs/openai/lib/python3.10/site-packages (0.74.2)
Requirement already satisfied: crewai-tools in /Users/user/miniconda4/envs/openai/lib/python3.10/site-packages (0.13.2)

(openai) user@Mac crewai_new % **crewai update**        
Traceback (most recent call last):
  File "/Users/user/miniconda4/envs/openai/bin/crewai", line 5, in <module>
    from crewai.cli.cli import crewai
  File "/Users/user/miniconda4/envs/openai/lib/python3.10/site-packages/crewai/cli/cli.py", line 20, in <module>
    from .run_crew import run_crew
  File "/Users/user/miniconda4/envs/openai/lib/python3.10/site-packages/crewai/cli/run_crew.py", line 4, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'

### Operating System

Other (specify in additional context)

### Python Version

3.10

### crewAI Version

0.74.2

### crewAI Tools Version

0.13.2

### Virtual Environment

Conda

### Evidence

(openai) user@Mac crewai_new % **pip install --upgrade crewai crewai-tools**
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: crewai in /Users/user/miniconda4/envs/openai/lib/python3.10/site-packages (0.74.2)
Requirement already satisfied: crewai-tools in /Users/user/miniconda4/envs/openai/lib/python3.10/site-packages (0.13.2)

(openai) user@Mac crewai_new % **crewai update**        
Traceback (most recent call last):
  File "/Users/user/miniconda4/envs/openai/bin/crewai", line 5, in <module>
    from crewai.cli.cli import crewai
  File "/Users/user/miniconda4/envs/openai/lib/python3.10/site-packages/crewai/cli/cli.py", line 20, in <module>
    from .run_crew import run_crew
  File "/Users/user/miniconda4/envs/openai/lib/python3.10/site-packages/crewai/cli/run_crew.py", line 4, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'

### Possible Solution

None

### Additional context

It's Saturday, not sure if that matter..

**Comment by ernestp** [comment]
Tried to reinstall miniconda with Python 3.13, also had an error, but different due to incompatible libraries

Had success with Python 3.11.10

**Comment by pascalandy** [comment]
> Had success with Python 3.11.10

I confirm it's now working :)

**Comment by Yatima-Kagurazaka** [comment]
It doesn't work yet with 3.11.10 🙃

**Comment by ernestp** [comment]
Confirmed, issue is fixed, closing
