### ISSUE TITLE
Cannot import Crawl4AI AsyncWebCrawler within CrewAI

### ISSUE THREAD

**Issue by Samiii777** [crewAIInc/crewAI#1472]
### Description

When I try to import AsyncWebCrawler from Crawl4AI I get below error.
not sure if there is any dependency issue or this is crawl4ai issue
crewai run
Running the Crew
warning: `VIRTUAL_ENV=/home/sami/src/projects/crewai/venv` does not match the project environment path `.venv` and will be ignored
Traceback (most recent call last):
  File "/home/sami/src/projects/crewai/stock_analyst/.venv/bin/run_crew", line 5, in <module>
    from stock_analyst.main import run
  File "/home/sami/src/projects/crewai/stock_analyst/src/stock_analyst/main.py", line 3, in <module>
    from stock_analyst.crew import StockAnalystCrew
  File "/home/sami/src/projects/crewai/stock_analyst/src/stock_analyst/crew.py", line 7, in <module>
    from crawl4ai import AsyncWebCrawler
ImportError: cannot import name 'AsyncWebCrawler' from 'crawl4ai' (unknown location)
An error occurred while running the crew: Command '['uv', 'run', 'run_crew']' returned non-zero exit status 1.

### Steps to Reproduce

1. pip install crawl4ai
2. add this line to your crew.py 
from crawl4ai import AsyncWebCrawler
crew run

### Expected behavior

no import issues

### Screenshots/Code snippets
```
from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task
from crewai import LLM
from crewai_tools import BaseTool
import asyncio
from crawl4ai import AsyncWebCrawler

# Uncomment the following line to use an example of a custom tool
# from stock_analyst.tools.custom_tool import MyCustomTool

# Check our tools documentations for more information on how to use them
# from crewai_tools import SerperDevTool


llm = LLM(
    model="ollama/llama3.2",
    base_url="http://localhost:11434",
)


class Crawl(BaseTool):
    name: str = "Website Crawler"
    description: str = "We will crawl a given website."

    def _run(self, argument: str) -> str:
        async def crawl_website():
            async with AsyncWebCrawler(verbose=True) as crawler:
                result = await crawler.arun(url=argument)
                return result.markdown[:500]  # Return first 500 characters

        # Run the async function in a synchronous context
        result = asyncio.run(crawl_website())
        return result

    async def _arun(self, argument: str) -> str:
        async with AsyncWebCrawler(verbose=True) as crawler:
            result = await crawler.arun(url=argument)
            return result.markdown[:500]  # Return first 500 characters

crawl = Crawl()
```
### Operating System

Ubuntu 22.04

### Python Version

3.10

### crewAI Version

0.74.2

### crewAI Tools Version

0.13.2

### Virtual Environment

Venv

### Evidence

crewai run
Running the Crew
warning: `VIRTUAL_ENV=/home/sami/src/projects/crewai/venv` does not match the project environment path `.venv` and will be ignored
Traceback (most recent call last):
  File "/home/sami/src/projects/crewai/stock_analyst/.venv/bin/run_crew", line 5, in <module>
    from stock_analyst.main import run
  File "/home/sami/src/projects/crewai/stock_analyst/src/stock_analyst/main.py", line 3, in <module>
    from stock_analyst.crew import StockAnalystCrew
  File "/home/sami/src/projects/crewai/stock_analyst/src/stock_analyst/crew.py", line 7, in <module>
    from crawl4ai import AsyncWebCrawler
ImportError: cannot import name 'AsyncWebCrawler' from 'crawl4ai' (unknown location)
An error occurred while running the crew: Command '['uv', 'run', 'run_crew']' returned non-zero exit status 1.

### Possible Solution

None

### Additional context

currently couldn't try running the main.py alone because of other tomllib issue causing by python3.11 depency

**Comment by bhancockio** [comment]
`ImportError: cannot import name 'AsyncWebCrawler' from 'crawl4ai' (unknown location)`

This looks like dependency issue. Did you add `crawl4ai` to your toml file?

**Comment by Samiii777** [comment]
I think adding it to the toml file resolved the issue, thanks for the suggestion
