### ISSUE TITLE
[BUG] 0.74.1 crewAI+ compatibility issue

### ISSUE THREAD

**Issue by adilazmoon** [crewAIInc/crewAI#1477]
### Description

Tried upgrading my crew to 0.74.1 before deploying on the enterprise platform crewAI+. However, I run into the following issue
2024-10-21 02:05:47 +0000  Building project setup
2024-10-21 02:05:47 +0000  Failed to find CrewAI version
2024-10-21 02:05:47 +0000  Failed to find CrewAI version

Is this because of the move away from poetry?
the crew in question: [https://news-scraper-crew-<redacted>.crewai.com](https://news-scraper-crew-20a42408-267c-4d84-adb7-7afa3434df8a.crewai.com)

### Steps to Reproduce

Upgrade to 0.74.1
deploy on crewAI+

### Expected behavior

Be able to deploy to crewAI+ even after updating the package

### Screenshots/Code snippets

![image](https://github.com/user-attachments/assets/b23676e1-cc21-4dda-b30d-314c7fc7d8b0)

### Operating System

Ubuntu 20.04

### Python Version

3.12

### crewAI Version

0.74.1

### crewAI Tools Version

NA

### Virtual Environment

Venv

### Evidence

Above

### Possible Solution

None

### Additional context

None

**Comment by bhancockio** [comment]
Good morning @adilazmoon !

We're super sorry about this weird error. Could you please try upgrading to 0.74.2 and let us know if you're able to successfully deploy your crew on this newer version?

**Comment by adilazmoon** [comment]
Hi @bhancockio! I actually did try on 0.74.2 alr before submitting this ticket. I suspect crewAI+ was previously looking for the crewAI version under poetry.lock in the older versions, but since package version management has changed to uv recently, has crewAI+ been updated to reference uv.lock for the crewAI version used instead?

**Comment by adilazmoon** [comment]
Just tried again now, still experiencing the same issue 
![image](https://github.com/user-attachments/assets/20990106-f1a5-4ffb-9539-066fb6d83e6d)

**Comment by bhancockio** [comment]
The team made a ton of fixes to enterprise and it's in a much more stable state right now.

Can you please try deploying again and letting us know if you have any additional troubles?

For the best results, I recommend deleting that crew and then redploying it.

**Comment by adilazmoon** [comment]
Oh Matt from support alr helped me get it working. Apparently poetry-old.lock & pyproject-old.toml would still interfere with the crewAI derivation logic, so I just removed that. Also it required "crewai[tools]>=0.74.2", instead of "crewai>=0.74.2" in the toml, which seemed unusually rigid. This was all last week though, are these bugs under the fixes addressed in the latest version?

**Comment by bhancockio** [comment]
We addressed a ton of bugs so if you update to the latest version (0.76.9) that came out last night and try to redeploy again, you shouldn't run into any more issues.

I'm going to close this ticket. If new issues pop up, please let us know!
