### ISSUE TITLE
[BUG] CrewAI Tools -- DirectorySearchTool, FileReadTool --> Requires OPENAI-API-Key

### ISSUE THREAD

**Issue by paarttipaabhalaji** [crewAIInc/crewAI#1483]
### Description

I am using the DirectorySearchTool, FileReadTool, but its ask me to set the "OPENAI_API_KEY"

### Steps to Reproduce

1. Add your local directory  which contains java files to directory_path

### Expected behavior

Crew AI tools like DirectorySearchTool, FileReadTool, need to execute without the OPENAI-API-KEY dependencies.

### Screenshots/Code snippets

import os
from crewai import Agent, Task, Crew, Process
from crewai_tools import DirectorySearchTool, FileReadTool

# Initialize Directory and File Read Tools
directory_tool = DirectorySearchTool()
file_read_tool = FileReadTool()

# Creating the File Retriever Agent
file_retriever = Agent(
    role="File Retriever Agent",
    goal="Retrieve the list of Java files in a given directory",
    verbose=True,
    memory=False,
    backstory=(
        "You specialize in scanning directories to find and return files."
    ),
    tools=[directory_tool]
)

# Creating the Java File Reader Agent
file_reader = Agent(
    role="Java File Reader Agent",
    goal="Read the contents of each retrieved Java file.",
    verbose=True,
    memory=False,
    backstory=(
        "You are efficient at reading Java files and extracting their contents."
    ),
    tools=[file_read_tool]
)

# Task to retrieve Java files from the directory
retrieve_files_task = Task(
    description="Search through the specified directory and retrieve all .java files.",
    expected_output="A list of file paths ending with .java",
    tools=[directory_tool],
    agent=file_retriever,
    async_execution=True
)

# Task to read the contents of the retrieved Java files
read_java_files_task = Task(
    description="Read the content of each retrieved Java file asynchronously.",
    expected_output="The content of each Java file",
    tools=[file_read_tool],
    agent=file_reader,
    async_execution=True
)

# Setup crew with both agents and tasks
crew = Crew(
    agents=[file_retriever, file_reader],
    tasks=[retrieve_files_task, read_java_files_task],
    process=Process.sequential  # First find the files, then read them
)

# Input directory path(removed my original path and replaced with placeholder)
directory_path = "<Directory_Path>"

# Kickoff the crew
result = crew.kickoff(inputs={'directory': directory_path})
print(result)

### Operating System

macOS Sonoma

### Python Version

3.11

### crewAI Version

0.41.0 

### crewAI Tools Version

0.12.1

### Virtual Environment

Venv

### Evidence

(.agentcrewai) paarttipaa@Paarttipaabhalajis-MacBook-Pro IND_SLC_CodeExpDesDocGen % /Users/paarttipaa/ProjectTask/GithubProj/IND_SLC_CodeExpDesDocGen/.agentcrewai/bin/python /Users/p
aarttipaa/ProjectTask/GithubProj/IND_SLC_CodeExpDesDocGen/AgenticApproach/task.py
sagemaker.config INFO - Not applying SDK defaults from location: /Library/Application Support/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /Users/paarttipaa/Library/Application Support/sagemaker/config.yaml
Traceback (most recent call last):
  File "/Users/paarttipaa/ProjectTask/GithubProj/IND_SLC_CodeExpDesDocGen/AgenticApproach/task.py", line 56, in <module>
    directory_tool = DirectorySearchTool()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paarttipaa/ProjectTask/GithubProj/IND_SLC_CodeExpDesDocGen/.agentcrewai/lib/python3.12/site-packages/crewai_tools/tools/directory_search_tool/directory_search_tool.py", line 32, in __init__
    super().__init__(**kwargs)
  File "/Users/paarttipaa/ProjectTask/GithubProj/IND_SLC_CodeExpDesDocGen/.agentcrewai/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paarttipaa/ProjectTask/GithubProj/IND_SLC_CodeExpDesDocGen/.agentcrewai/lib/python3.12/site-packages/crewai_tools/tools/rag/rag_tool.py", line 47, in _set_default_adapter
    app = App.from_config(config=self.config) if self.config else App()
                                                                  ^^^^^
  File "/Users/paarttipaa/ProjectTask/GithubProj/IND_SLC_CodeExpDesDocGen/.agentcrewai/lib/python3.12/site-packages/embedchain/app.py", line 121, in __init__
    self.embedding_model = embedding_model or OpenAIEmbedder()
                                              ^^^^^^^^^^^^^^^^
  File "/Users/paarttipaa/ProjectTask/GithubProj/IND_SLC_CodeExpDesDocGen/.agentcrewai/lib/python3.12/site-packages/embedchain/embedder/openai.py", line 18, in __init__
    api_key = self.config.api_key or os.environ["OPENAI_API_KEY"]
                                     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'OPENAI_API_KEY'

### Possible Solution

None

### Additional context

Please confirm all the crewai tools requires a OPENAI-API-KEY

**Comment by bhancockio** [comment]
Hey @paarttipaabhalaji!

If you are looking to use a different LLM framework, you can update the model you use with your DirectorySearchTool and FileReadTool. Check out the docs below for examples:

https://docs.crewai.com/tools/directorysearchtool#custom-model-and-embeddings

You can see all of the available embedding models here:

https://docs.embedchain.ai/components/embedding-models

Please let us know if you run into additional issues or have any other questions!
