### ISSUE TITLE
[BUG] : CrewAI Doesn't seem to support VertexAI embedding models.

### ISSUE THREAD

**Issue by vicky0106** [crewAIInc/crewAI#1489]
### Description

I need to use memory feature of CrewAI to make sure that my chatBOT uses the recent interactions to answer the follow up questions. Currently, we are using GCP VertexAI platform. I found following code in the documentation link(https://docs.crewai.com/concepts/memory) to implement the memory but this code is failing because CrewAI doesn't have any 'embedding_functions'. can you point me to the right documentation or help me solve this issue?

from crewai import Crew, Agent, Task, Process

my_crew = Crew(
    agents=[...],
    tasks=[...],
    process=Process.sequential,
    memory=True,
    verbose=True,
    embedder=embedding_functions.GoogleVertexEmbeddingFunction(
        project_id="YOUR_PROJECT_ID",
        region="YOUR_REGION",
        api_key="YOUR_API_KEY",
        model_name="textembedding-gecko"
    )
)

### Steps to Reproduce

Create a crew using following code

from crewai import Crew, Agent, Task, Process

my_crew = Crew(
    agents=[...],
    tasks=[...],
    process=Process.sequential,
    memory=True,
    verbose=True,
    embedder=embedding_functions.GoogleVertexEmbeddingFunction(
        project_id="YOUR_PROJECT_ID",
        region="YOUR_REGION",
        api_key="YOUR_API_KEY",
        model_name="textembedding-gecko"
    )
)

### Expected behavior

Code provided in the documentation should be able to create memory using VertexAI embedding model

### Screenshots/Code snippets

from crewai import Crew, Agent, Task, Process

my_crew = Crew(
    agents=[...],
    tasks=[...],
    process=Process.sequential,
    memory=True,
    verbose=True,
    embedder=embedding_functions.GoogleVertexEmbeddingFunction(
        project_id="YOUR_PROJECT_ID",
        region="YOUR_REGION",
        api_key="YOUR_API_KEY",
        model_name="textembedding-gecko"
    )
)

### Operating System

Ubuntu 20.04

### Python Version

3.10

### crewAI Version

latest

### crewAI Tools Version

NA

### Virtual Environment

Venv

### Evidence

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 1
----> 1 from crewai.embedding_functions import GoogleVertexEmbeddingFunction

ModuleNotFoundError: No module named 'crewai.embedding_functions'

### Possible Solution

NOne

### Additional context

None

**Comment by bhancockio** [comment]
You need to import `GoogleVertexEmbeddingFunction` from `chromadb.utils.embedding_functions` instead of from `crewai`

```
from chromadb.utils.embedding_functions import GoogleVertexEmbeddingFunction
from crewai import Crew, Process

my_crew = Crew(
    agents=[...],
    tasks=[...],
    process=Process.sequential,
    memory=True,
    verbose=True,
    embedder=GoogleVertexEmbeddingFunction(
        project_id="YOUR_PROJECT_ID",
        region="YOUR_REGION",
        api_key="YOUR_API_KEY",
        model_name="textembedding-gecko"
    )
)
```

#1497 updates the docs and closes this issue.
