### ISSUE TITLE
[FEATURE]Add UV config to pyproject.toml

### ISSUE THREAD

**Issue by flingjie** [crewAIInc/crewAI#1492]
### Feature Area

Other (please specify in additional context)

### Is your feature request related to a an existing bug? Please link it here.

NA

### Describe the solution you'd like

[tool.uv]
index-url = "https://mirrors.aliyun.com/pypi/simple/"

### Describe alternatives you've considered

For example, in China, using the default pip source (https://pypi.org/) to install will be slow, and need to use a specific pip to speed up. It is better to have a configuration item in the configuration file to configure it.

### Willingness to Contribute

Yes, I'd be happy to submit a pull request

**Comment by pythonbyte** [comment]
@flingjie 
Thanks for bringing this up, if I'm not mistaken in this PR
https://github.com/astral-sh/uv/pull/7747

Was added the ability on UV to add the specific source, in that case you can just run the uv command to add to the pyproject.toml
