### ISSUE TITLE
[BUG]No module named 'tomllib'

### ISSUE THREAD

**Issue by flingjie** [crewAIInc/crewAI#1495]
### Description

When using python3.10, the error `No module named 'tomllib' is reported`

### Steps to Reproduce

1. use python3.10
2. run `crewai run`

### Expected behavior

it can run successfully.

### Screenshots/Code snippets

tomllib starts from Python 3.11, but the supported versions written in the usage documentation are >=3.10 <=3.13.

### Operating System

macOS Catalina

### Python Version

3.10

### crewAI Version

0.74.2

### crewAI Tools Version

0.13.2

### Virtual Environment

Venv

### Evidence

.../.venv/lib/python3.10/site-packages/crewai/cli/update_crew.py", line 5, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'

### Possible Solution

Either continue to use the parse_toml method in utils for compatibility.
Either update the usage documentation to update the supported versions to start with a Python version that supports tomllib

### Additional context

/crewai/cli/utils.py

<img width="528" alt="Snipaste_2024-10-23_21-58-46" src="https://github.com/user-attachments/assets/d78042d6-b2ae-480e-b8d1-3cc7d96e0bef">

**Comment by pythonbyte** [comment]
Hey @flingjie 

tomllib — Parse TOML files[¶](https://docs.python.org/3/library/tomllib.html#module-tomllib)
Added in version 3.11.

We highly suggest starting using Python 3.11

We'll take care of the update of the code/docs

**Comment by pythonbyte** [comment]
Thanks for the report @flingjie 

We fixed this issue with the https://github.com/crewAIInc/crewAI/pull/1506 

Let me know if it works now, I'll close this issue for now.
