### ISSUE TITLE
[BUG] Task Ended telemetry has been stopped

### ISSUE THREAD

**Issue by Hrithikd** [crewAIInc/crewAI#1502]
### Description

In version 0.67.1 I was able to get the Task Executed / ended event from opentelemetry. However, in the most recent version, the task ended/ task executed event is not getting emitted. Something happened between 0.67 and latest version.

### Steps to Reproduce

Just add a console exporter like this:
            from opentelemetry.sdk.trace.export import BatchSpanProcessor, ConsoleSpanExporter
            CrewAILogger._provider.add_span_processor(BatchSpanProcessor(ConsoleSpanExporter()))
           and you will see that the task executed event is not there in the latest version, but is there in 0.67.1

### Expected behavior

The task executed span should be being emitted. I have the share_crew turned on

### Screenshots/Code snippets

            from opentelemetry.sdk.trace.export import BatchSpanProcessor, ConsoleSpanExporter
            CrewAILogger._provider.add_span_processor(BatchSpanProcessor(ConsoleSpanExporter()))

### Operating System

Ubuntu 20.04

### Python Version

3.10

### crewAI Version

latest

### crewAI Tools Version

any

### Virtual Environment

Venv

### Evidence

The span isn't there

### Possible Solution

Make sure the span is being emitted

### Additional context

Thank you!

**Comment by bhancockio** [comment]
Hey @Hrithikd !

We are working on a big refactor that should fix this issue. I'll be sure to keep you posted about the progress of this change. Ideally, the change should be merged in by the end of this week or the beginning of next.
