### ISSUE TITLE
[BUG] TypeError in _extract_thought Due to NoneType Input

### ISSUE THREAD

**Issue by shbfy** [crewAIInc/crewAI#1521]
### Description

When executing the Crew, a `TypeError` occurs in the `_extract_thought` method of `parser.py`. The error arises because the text variable is None when passed to `re.search()`, which expects a string or bytes-like object. This leads to an unhandled exception that terminates the application. This does not occur with Crew version 0.5X.

### Steps to Reproduce

Create a crew with a forced output file:

```python
    @task
    def reporting_task(self) -> Task:
        return Task(
            config=self.tasks_config["reporting_task"],
            output_file=f"{self.output_dir}/report.md",
        )
```

Observe a `TypeError`:
```
  File "/Users/some_user/Library/Caches/pypoetry/virtualenvs/mycrew-agqGppDS-py3.12/lib/python3.12/site-packages/crewai/agents/parser.py", line 123, in _extract_thought
    thought_match = re.search(regex, text, re.DOTALL)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/re/__init__.py", line 177, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

### Expected behavior

The _extract_thought method should receive a valid string for the text parameter and successfully perform regex search operations without raising exceptions. Output is then written to the specified directory.

### Screenshots/Code snippets

NA

### Operating System

macOS Monterey

### Python Version

3.12

### crewAI Version

0.76.2

### crewAI Tools Version

0.13.2

### Virtual Environment

Poetry

### Evidence

  File "/Users/some_user/Library/Caches/pypoetry/virtualenvs/mycrew-agqGppDS-py3.12/lib/python3.12/site-packages/crewai/agents/parser.py", line 123, in _extract_thought
    thought_match = re.search(regex, text, re.DOTALL)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/re/__init__.py", line 177, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

### Possible Solution

NA

### Additional context

Issue is caused by `None` `text` input to the following function:

```python
def _extract_thought(self, text: str) -> str:
    regex = r"(.*?)(?:\n\nAction|\n\nFinal Answer)"
    print("Debug: text is:", repr(text))
    if text is None:
        print("Error: text is None")
        return ""
    thought_match = re.search(regex, text, re.DOTALL)
    if thought_match:
        return thought_match.group(1).strip()
    return ""
```

**Comment by shbfy** [comment]
> Hey @shbfy! Thank you for reporting this!
> 
> I will be looking into this first thing tomorrow and keep you posted on the fix for this issue.

Thank you!!

**Comment by bhancockio** [comment]
Hey @shbfy !

I have a few followup questions for you:
- Which model were you using?
- What does the complete error look like? Are there any additional logs besides the ones you've already shared?
- Would it be possible to share what your crew, agent, and task look like? You can email me at brandon@crewai.com if you'd like to keep it private. The reason I ask is because I cannot reproduce this error.

**Comment by shbfy** [comment]
> Hey @shbfy !
> 
> I have a few followup questions for you:
> 
> * Which model were you using?
> * What does the complete error look like? Are there any additional logs besides the ones you've already shared?
> * Would it be possible to share what your crew, agent, and task look like? You can email me at [brandon@crewai.com](mailto:brandon@crewai.com) if you'd like to keep it private. The reason I ask is because I cannot reproduce this error.

Thanks for taking a look @bhancockio 

* VertexAI with Anthropic (Claude). 
* I'll follow up with full error, but I've pulled out the cause which is None being used as the text input to the extract thought function.
* I'll try and create an example for you :)

**Comment by shbfy** [comment]
> Hey @shbfy !
> 
> I have a few followup questions for you:
> 
> * Which model were you using?
> * What does the complete error look like? Are there any additional logs besides the ones you've already shared?
> * Would it be possible to share what your crew, agent, and task look like? You can email me at [brandon@crewai.com](mailto:brandon@crewai.com) if you'd like to keep it private. The reason I ask is because I cannot reproduce this error.

Working on getting you a reproducible example, it seems like the bug concerns the prompts themselves and presents intermittently which makes reproducing this a little tricky...

**Comment by shbfy** [comment]
> Hey @shbfy !
> 
> I have a few follow-up questions for you:
> 
> * Which model were you using?
> * What does the complete error look like? Are there any additional logs besides the ones you've already shared?
> * Would it be possible to share what your crew, agent, and task look like? You can email me at [brandon@crewai.com](mailto:brandon@crewai.com) if you'd like to keep it private. The reason I ask is because I cannot reproduce this error.

I've found the cause of the bug. VertexAI was returning a 529 overloaded:

```
2024-10-30 16:01:04,644 - 8661307200 - llm.py-llm:161 - ERROR: LiteLLM call failed: litellm.InternalServerError: VertexAIException InternalServerError - {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}
```

This meant a `None` type was eventually passed down to the `_extract_thought` function. For now, I have increased the `max_retry_limit', which has resolved the issue.  It might be worth considering error handling for cases where a `None` is returned from the LiteLLM call. I hope this is useful!

**Comment by bhancockio** [comment]
Thank you so much for update and letting me know about the root issue.

I'm opening an issue now to better handle the scenario when LiteLLM returns none.
