### ISSUE TITLE
[QUESTION]  How can i use a Azure OpenAI service to works on CSVSearchTool

### ISSUE THREAD

**Issue by slx618** [crewAIInc/crewAI#1527]
### Feature Area

Core functionality

### Is your feature request related to a an existing bug? Please link it here.

Can you give me a detail config demo code in the documents?
I have read the source code and try a lot of time but not works.

### Describe the solution you'd like

here is my config, what I have missed? 

config=dict(
                  
                    llm=dict(
                        provider="azure_openai",  # or google, openai, anthropic, llama2, ...
                        config=dict(
                            model="azure/my_dep_name",
                            api_version="2023-12-01-preview",
                            api_key="x",
                            base_url="https://xxx.openai.azure.com",
                        ),
                    ),
                    embedder=dict(
                        provider="azure_openai",  # or google, openai, anthropic, llama2, ...
                        
                        config=dict(
                            model="text-embedding-ada-002",
                            deployment_name="xxx",
                            api_key="xx",
                            base_url="https://xxx.openai.azure.com",
                        ),
                )

### Willingness to Contribute

I can test the feature once it's implemented

**Comment by bhancockio** [comment]
Could you please provide a complete error message with the issue you are you getting with your current config?

**Comment by slx618** [comment]
config like this works for me, thank you! 

 os.environ["AZURE_OPENAI_API_KEY"] = ''
    os.environ["AZURE_OPENAI_ENDPOINT"] = ''



 llm=dict(
                        provider="azure_openai",
                        config=dict(
                            model="your-deploy-name"
                        ),
                    ),
                    embedder=dict(
                        provider="azure_openai",
                        config=dict(
                            model="your-deploy-name"
                        ),
                    ),
