### ISSUE TITLE
Inquiry on Using Memory in Routes for Crew AI

### ISSUE THREAD

**Issue by AlroySe** [crewAIInc/crewAI#1529]
### Feature Area

Core functionality

### Is your feature request related to a an existing bug? Please link it here.

I am currently exploring Crew AI to test its capabilities and functionalities. Specifically, I am interested in incorporating memory within Routes and would like some guidance on the best approach for this integration. Could you advise on whether memory should be implemented directly in the Pipeline, Crew, or Route to achieve optimal results?
I attempted to use memory within the Crew, but encountered an error stating "collection not found." when using it in Routes. Could you please clarify what might be causing this issue or provide guidance on how to resolve it?

### Describe the solution you'd like

Just like memory in crewkickoff add the same for Pipeline that has routes object in stages.

### Willingness to Contribute

Yes, I'd be happy to submit a pull request

**Comment by bhancockio** [comment]
Hey @AlroySe! 

We have deprecated Pipeline and now recommend using flows instead. Here is a link to the flow docs:

https://docs.crewai.com/concepts/flows

Additionally, memory should be implemented directly at the Crew level.

Please checkout these docs:

https://docs.crewai.com/concepts/memory#implementing-memory-in-your-crew

If you have any additional questions about Memory, Crews, or Flows, please let us know!
