### ISSUE TITLE
Example for using crewai with open API (Swagger ) 

### ISSUE THREAD

**Issue by debianmaster** [crewAIInc/crewAI#1537]
### Feature Area

Integration with external tools

### Is your feature request related to a an existing bug? Please link it here.

I would like to use `openapi` from langchain but its not clearly document hence facing issues configuring open api tool with crewai

### Describe the solution you'd like

https://python.langchain.com/docs/integrations/tools/openapi/ 
Want to use open api tool with crew ai

### Willingness to Contribute

I could provide more detailed specifications

**Comment by theCyberTech** [comment]
Can you please provide more context, for example how you've implemented this and what issues you're explicitly having
