### ISSUE TITLE
ModuleNotFoundError: No module named 'agentops'

### ISSUE THREAD

**Issue by shilida** [crewAIInc/crewAI#1539]
### Description

ModuleNotFoundError: No module named 'agentops'
ButI 'm sure agentops is installed

### Steps to Reproduce

PS D:\xxxx> crewai run
Running the Crew
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\xxxx\run_crew.exe\__main__.py", line 5, in <module>
  File "D:\xxxx\main.py", line 3, in <module>
    import agentops
ModuleNotFoundError: No module named 'agentops'
An error occurred while running the crew: Command '['uv', 'run', 'run_crew']' returned non-zero exit status 1.

### Expected behavior

I'm sure agentops is installed

### Screenshots/Code snippets

No

### Operating System

Windows 11

### Python Version

3.11

### crewAI Version

0.76.9

### crewAI Tools Version

0.13.4

### Virtual Environment

Conda

### Evidence

PS D:\xxx>  pip show agentops
Name: agentops
Version: 0.3.14
Summary: Observability and DevTool Platform for AI Agents
Home-page: https://github.com/AgentOps-AI/agentops
Author:
Author-email: Alex Reibman <areibman@gmail.com>, Shawn Qiu <siyangqiu@gmail.com>, Braelyn Boynton <bboynton97@gmail.com>, Howard Gil <howardbgil@gmail.com>
License:
Location: D:\ProgramData\Anaconda3\envs\llms\Lib\site-packages
Requires: packaging, psutil, PyYAML, requests, termcolor
Required-by:

### Possible Solution

NO

### Additional context

NO

**Comment by abhaychitnis** [comment]
I am having the same issue with langtrace and conda environment. I think this has to do with virtual environments. Can someone please respond ?

**Comment by abhaychitnis** [comment]
Try adding 'agentops' in the 'dependencies' section of 'project', in the pyproject.toml file. 
Let me know if it works.
