### ISSUE TITLE
[BUG] step_callback not being called in Crew and Agent class

### ISSUE THREAD

**Issue by maurovz** [crewAIInc/crewAI#1563]
### Description

I want to show tall agent activity to the user.

I created a Crew (code bellow) and used the `step_callback` with a simple print statement. This is never called thus I'm unable to see/show the agent crew activity.

### Steps to Reproduce

Create a crew as follows:
```
crew = Crew(
        agents=agents,
        tasks=tasks,
        process=Process.hierarchical,
        manager_llm=self.llm,
        verbose=True,
        step_callback=lambda step_output: print(f"Step output: {step_output}")                
         )
```
step_callback is never called

### Expected behavior

The print should be called every step `print(f"Step output: {step_output}`

### Screenshots/Code snippets

```
crew = Crew(
        agents=agents,
        tasks=tasks,
        process=Process.hierarchical,
        manager_llm=self.llm,
        verbose=True,
        step_callback=lambda step_output: print(f"Step output: {step_output}")                
         )
```

And for Agent it also doesn't work

```
agent = Agent(
          role=tool.name,
          goal=tool.goal,
          backstory=tool.backstory,
          verbose=True,
          llm=llm,
          step_callback=lambda step_output: print(f"Step output: {step_output}")                
       )
```

### Operating System

Ubuntu 24.04

### Python Version

3.12

### crewAI Version

0.76.9

### crewAI Tools Version

0.13.4

### Virtual Environment

Venv

### Evidence

There is no error messages it's just never called

### Possible Solution

None

### Additional context

I'm using the hierarchical process but may not make a difference

**Comment by sundaresan-r** [comment]
I'm also facing the same issue, `step_callback` is not being called while execution

**Comment by timschott** [comment]
I am also confused as to whether the `callbacks` parameter can be used on the `Agent` class. In the docs example [here](https://docs.crewai.com/concepts/agents#creating-an-agent) the callbacks list is used like

```
from crewai import Agent

agent = Agent(
...,
  callbacks=[callback1, callback2],  # Optional
)
```

however, scrolling up on those [same](https://docs.crewai.com/concepts/agents#agent-attributes) docs, the `callbacks` field is not listed as an attribute of the `Agent` class and appears to have been removed at some point from the [source code](https://github.com/crewAIInc/crewAI/blob/main/src/crewai/agent.py#L50-L64). If the removal of this behavior is intentional, the docs should be updated to reflect this.

**Comment by sundaresan-r** [comment]
Hey this works!! Thanks @amaelftah 

Two observations I made which I'd like to share,

## 1. Without making the above mentioned indentation change in the src code file

- The `step_callback` works for only the agents which are given the access to any tool

- The attributes of the `step_output` in such a case are - `result`, `text`, `thought`, `tool` and `tool_input`

> step_callback=lambda step_output: print(f"Step output: {step_output}")

## 2. With making the above mentioned indentation change in the src code file

- The `step_callback` works for both the cases (i.e) with and without tool accessed agents

- The attributes for the `step_output` in case of non-tool accessed agents are - `output`, `text`, `thought`. This also applies for the steps of agents where it does not uses a tool even though it has access

**Comment by amaelftah** [comment]
@sundaresan-r thanks a lot for the addition 👍

**Comment by maurovz** [comment]
> i faced the same problem and probaley the fix could be indentation of [these lines ] to be outside like the screenshot (
> 
> https://github.com/crewAIInc/crewAI/blob/8610faef22024fb24486851402ae6ee7df95625c/src/crewai/agents/crew_agent_executor.py#L148-L166
> )
> 
> ![image](https://private-user-images.githubusercontent.com/17250137/385106241-99ba72be-8253-4bd8-91cf-703371636b7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTU4MzEsIm5iZiI6MTczMTQ5NTUzMSwicGF0aCI6Ii8xNzI1MDEzNy8zODUxMDYyNDEtOTliYTcyYmUtODI1My00YmQ4LTkxY2YtNzAzMzcxNjM2YjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEwNTg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ODk2NDdlZGU0MmU2YmZlZDM3Mzg4ZjRlZTMwMjZjNzJkMWExYWJmZTBmOWM2YzQxMTBmMzQ0NmZhODQ1NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fwvTDHEwt97xQ1Z3a__1lPeZQ3KFPuepBAzuQdrS36E)

Maybe you should create a PR with this fix?

**Comment by amaelftah** [comment]
@maurovz am fine if anyone want to make a PR with that solution

**Comment by pythonbyte** [comment]
Thanks @amaelftah for the update, we'll add the fix for it.

**Comment by pythonbyte** [comment]
PR Merged.
Thanks.
https://github.com/crewAIInc/crewAI/pull/1595
