### ISSUE TITLE
Best Practices for Reinvoking @router Multiple Times in CrewAI Flow

### ISSUE THREAD

**Issue by jkcg-learning** [crewAIInc/crewAI#1579]
### Description

Hello,

I'm working on creating a custom flow using the CrewAI framework, and I'm encountering an issue where the flow stops completely after the first iteration when using the [@router](https://docs.crewai.com/concepts/flows) decorator. My goal is to have the flow loop, alternating between two methods based on a condition, until a maximum number of iterations is reached. However, after the first iteration, the flow doesn't continue back to the router.

''"

    class ExampleState(BaseModel):
       success_flag: bool = False
       iteration: int = 0
       max_iterations: int = 5  # To prevent infinite loops

    class RouterFlow(Flow[ExampleState]):

    @start()
    def start_method(self):
        print("Starting the structured flow")
        self.state.iteration = 0  # Initialize iteration counter
        self.state.success_flag = random.choice([True, False])
        return "next_step"  # Return event to trigger the router

    @router("next_step")
    def second_method(self):
        if self.state.iteration >= self.state.max_iterations:
            return "end"  # End the flow after max iterations
        if self.state.success_flag:
            return "success"
        else:
            return "failed"

    @listen("success")
    def third_method(self):
        print("Third method running")
        self.state.iteration += 1
        self.state.success_flag = random.choice([True, False])  # Update success_flag
        return "next_step"  # Return event to trigger the router again

    @listen("failed")
    def fourth_method(self):
        print("Fourth method running")
        self.state.iteration += 1
        self.state.success_flag = random.choice([True, False])  # Update success_flag
        return "next_step"  # Return event to trigger the router again

    @listen("end")
    def end_method(self):
        print(f"Ending the flow after {self.state.iteration} iterations.")

    flow = RouterFlow()
    flow.kickoff()
'''

### Steps to Reproduce

My Question:

- Is there an issue with how I'm using the [@router ](https://docs.crewai.com/concepts/flows)decorator in this context?
- Does the [@router ](https://docs.crewai.com/concepts/flows)decorator in CrewAI not support being called multiple times in a loop?
- What is the recommended way to implement a flow that needs to loop back to a router after each iteration based on dynamic conditions?

### Expected behavior

I want to create a flow where:

- The flow starts and sets an initial state.
- Based on a condition (success_flag), it routes to different methods.
- These methods perform actions, update the state, and loop back to the router.
- The flow should continue looping until a certain condition (max_iterations) is met.

### Screenshots/Code snippets

NA

### Operating System

macOS Sonoma

### Python Version

3.12

### crewAI Version

0.76.9

### crewAI Tools Version

0.13.4

### Virtual Environment

Venv

### Evidence

NA

### Possible Solution

NA

### Additional context

NA

**Comment by darkostanimirovic** [comment]
I'm having the same issue. My use case is to extract an array of items in the first step, then pop the first item in the second step and send it to the router to decide what to do based on its type. 

The individual steps that process each item would loop back to the step that pops one items from the array, and the process should loop until there are no more items in the array.

However, it looks like the processing stops any time it should go to the router the second time. I was hoping there was some kind of a looping decorator to simplify things.

From the [Docs example](https://docs.crewai.com/concepts/flows#main-code-highlights), it sounds like this should be possible IF the loop goes back to `start()` and not any point in the flow. So perhaps if I rewrite it to have two flows where one always starts from where the loop would start, it might work.

**Comment by darkostanimirovic** [comment]
Still no luck. I tried looping back to `start("loop")` but it still stops after the first round. I'll try working off of the routing example but so far it doesn't really work like that for me.

**Comment by darkostanimirovic** [comment]
After a number of debugging rounds with Copilot it looks like I found the bug – assuming it is a bug, but perhaps there's just a better/natural way to do this. @joaomdmoura Could you take a look if this makes sense or if we're just obviously doing something wrong?

Copilot:

**Problem:**

The flow stops after the first iteration because the `_execute_single_listener` method in `flow.py` incorrectly handles the event emitted by listener methods. Instead of using the event returned by the listener method (`listener_result`), it incorrectly uses the name of the listener method (`listener_name`), causing the flow to not respond to new events and stop after the first execution.

**Solution:**

Modify the `_execute_single_listener` method to correctly handle the event emitted by the listener method. Specifically, use `listener_result` to trigger the next set of listeners if it is a valid event.

**Code Changes:**

```python
async def _execute_single_listener(self, listener_name: str, result: Any) -> None:
    try:
        method = self._methods[listener_name]
        sig = inspect.signature(method)
        params = list(sig.parameters.values())

        # Exclude 'self' parameter
        method_params = [p for p in params if p.name != "self"]

        if method_params:
            # If listener expects parameters, pass the result
            listener_result = await self._execute_method(
                listener_name, method, result
            )
        else:
            # If listener does not expect parameters, call without arguments
            listener_result = await self._execute_method(listener_name, method)

-        # Incorrectly using listener_name instead of listener_result
-        await self._execute_listeners(listener_name, listener_result)
+        # Corrected code: Use the event emitted by the listener
+        if listener_result and isinstance(listener_result, str):
+            await self._execute_listeners(listener_result, None)
    except Exception as e:
        print(
            f"[Flow._execute_single_listener] Error in method {listener_name}: {e}"
        )
        import traceback
        traceback.print_exc()
```

**Comment by darkostanimirovic** [comment]
Btw I was doing this on `0.79.4` and I see you're on an older version. Not sure it makes a difference though.

**Comment by jkcg-learning** [comment]
> Btw I was doing this on `0.79.4` and I see you're on an older version. Not sure it makes a difference though.

@darkostanimirovic , Thanks for looking into the issue and confirming the same from your end as well. I also tried different version, but the problem exists.

Meantime, I will also try the workaround that you proposed.

**Comment by axel0016** [comment]
import random
from crewai.flow.flow import Flow, listen, router, start
from pydantic import BaseModel

class ExampleState(BaseModel):
   success_flag: bool = False
   iteration: int = 0
   max_iterations: int = 5  # To prevent infinite loops

class RouterFlow(Flow[ExampleState]):

    @start("start")
    def start_method(self):
        print("Starting the structured flow")
         # Initialize iteration counter
        self.state.success_flag = random.choice([True, False])
        print(self.state.success_flag)
        print(self.state.iteration)
        return "next_step"  # Return event to trigger the router

    @router(start_method)
    def second_method(self):
        print("Second method")
        print(self.state.success_flag)
        print(self.state.iteration)
        if self.state.iteration >= self.state.max_iterations:
            return "end"  # End the flow after max iterations
        if self.state.success_flag:
            return "success"
        else:
            return "failed"

    @listen("success")
    def third_method(self):
        print("Third method running")
        print(self.state.iteration)
        self.state.iteration += 1
        self.state.success_flag = random.choice([True, False])  # Update success_flag
        
    @router(third_method)
    def third_router(self):
        print("am router for third")
        return "start"

    @listen("failed")
    def fourth_method(self):
        print("Fourth method running")
        self.state.iteration += 1
        print(self.state.iteration)
        self.state.success_flag = random.choice([True, False])  # Update success_flag
        return "next_step"  # Return event to trigger the router again
    @router(fourth_method)
    def fourth_router(self):
        print("am router for fourth")
        return "start"

    @listen("end")
    def end_method(self):
        print(f"Ending the flow after {self.state.iteration} iterations.")

flow = RouterFlow()
flow.kickoff()
flow.plot()

**Comment by Akashrana1001** [comment]
Hit something adjacent to this — CrewAI loop silently burning tokens/cost before you notice.
Built a small open-source circuit breaker that hooks before_llm_call and kills the call before it's dispatched, instead of after the step finishes. Free, MIT: github.com/Akashrana1001/crew-fusebox

Not selling anything here — just curious if this kind of pre-flight blocker would've caught what you hit, or if your root cause (the @router flow loop not terminating the way max_iterations expected) needed something more specific than a cost gate.
