### ISSUE TITLE
[BUG] Can not import langtrace package with crewai flow

### ISSUE THREAD

**Issue by abhaychitnis** [crewAIInc/crewAI#1592]
### Description

I am trying to use langtrace with crewai 0.79.4. I have installed langtrace-python-sdk 3.3.1 in a conda virtual environment. I have edited the main.py file created by the command 'crewai create flow xxxx', as follows:
```
import os
import sys

from dotenv import load_dotenv

load_dotenv() 

from langtrace_python_sdk import langtrace # Must precede any llm module imports

langtrace.init(api_key = os.environ.get("LANGTRACE_API_KEY"))
````
I have set the environment as described in crewai documentation,
````
crewai install
source .venv/bin/activate
````
However when I run the crewai flow using
````
crewai flow kickoff
````
I get an error as follows:
````
Running the Flow
Traceback (most recent call last):
  File "/home/infdevices/research_crew/test_research_flow/.venv/bin/kickoff", line 5, in <module>
    from test_research_flow.main import kickoff
  File "/home/infdevices/research_crew/test_research_flow/src/test_research_flow/main.py", line 9, in <module>
    from langtrace_python_sdk import langtrace # Must precede any llm module imports
ModuleNotFoundError: No module named 'langtrace_python_sdk'
An error occurred while running the flow: Command '['uv', 'run', 'kickoff']' returned non-zero exit status 1.
````
The flow works correctly if the statements,
````
from langtrace_python_sdk import langtrace # Must precede any llm module imports

langtrace.init(api_key = os.environ.get("LANGTRACE_API_KEY"))
````
are removed.
I have tried to uninstall and reinstall langtrace, but it does not work.

### Steps to Reproduce

Have described the steps in the description above

### Expected behavior

The import should work seamlessly

### Screenshots/Code snippets

Included in the description

### Operating System

Ubuntu 24.04

### Python Version

3.10

### crewAI Version

0.79.4

### crewAI Tools Version

0.14.0

### Virtual Environment

Conda

### Evidence

````
Running the Flow
Traceback (most recent call last):
  File "/home/infdevices/research_crew/test_research_flow/.venv/bin/kickoff", line 5, in <module>
    from test_research_flow.main import kickoff
  File "/home/infdevices/research_crew/test_research_flow/src/test_research_flow/main.py", line 9, in <module>
    from langtrace_python_sdk import langtrace # Must precede any llm module imports
ModuleNotFoundError: No module named 'langtrace_python_sdk'
An error occurred while running the flow: Command '['uv', 'run', 'kickoff']' returned non-zero exit status 1.

````

### Possible Solution

None

### Additional context

None

**Comment by abhaychitnis** [comment]
Found out the solution.
I added,
```
"langtrace_python_sdk>=3.3"
```
In the dependencies section under project and it worked smoothly.

**Comment by GiovanniBalestrieri** [comment]
For anyone unsure about where to place that line, 

`vim pyproject.toml `

You ll find the dependencies section:q
```
dependencies = [
    "crewai[tools]>=0.80.0,<1.0.0",
    "langtrace_python_sdk>=3.3"
]
```
