### ISSUE TITLE
[BUG] Getting a dependency error on `onnxruntime` when I run `crewai install`

### ISSUE THREAD

**Issue by mjgradright** [crewAIInc/crewAI#1599]
### Description

Just getting started with the project, so I'm not sure if I missed anything. I installed crewai as per the documentation and tried the quickstart project. The `crewai install` command is failing with the following error.

```
Distribution `onnxruntime==1.20.0 @ registry+https://pypi.org/simple` can't be installed because it doesn't have a source distribution or wheel for the current platform
An error occurred while running the crew: Command '['uv', 'sync']' returned non-zero exit status 2.
```
Tried older versions as well, but didn't work. Can someone please help me on this?

### Steps to Reproduce

Ran the following commands...

1. `pip install crewai`
2. `crewai create crew latest-ai-development`
3. `cd latest-ai-development`
4. `crewai install`

### Expected behavior

Install process should complete and I should be able to run `crew run` command.

### Screenshots/Code snippets

-

### Operating System

macOS Monterey

### Python Version

3.12

### crewAI Version

0.79.4

### crewAI Tools Version

0.14.0

### Virtual Environment

Conda

### Evidence

<img width="1238" alt="Screenshot 2024-11-13 at 10 11 07 PM" src="https://github.com/user-attachments/assets/839ceb87-db66-4ff1-9471-c6856e84db83">

### Possible Solution

-

### Additional context

-

**Comment by jkcg-learning** [comment]
@mjgradright if you are using macos make sure that the os version is above 13.0

https://pypi.org/project/onnxruntime/#files

**Comment by mjgradright** [comment]
Thanks @jkcg-learning . I'm using 12.7.6 (Montery). Will try with an older version of CrewAI or figure out a docker setup with compatible linux.

**Comment by keerthishekar** [comment]
Still getting the same error when we run it for MacOS 14.4
<img width="472" alt="Screenshot 2024-11-18 at 3 32 31 PM" src="https://github.com/user-attachments/assets/2243427e-782e-4aef-a785-2fdd0f75a9f9">
<img width="1273" alt="Screenshot 2024-11-18 at 3 32 43 PM" src="https://github.com/user-attachments/assets/04d2aceb-4b19-4f7a-92e2-4e6865fbd216">

**Comment by keerthishekar** [comment]
This issue wasnt present friday. Not sure if anything was released from crewai post Friday IST

**Comment by KgotsoK** [comment]
Also debugging this issue on macOS 13.7.1... @keerthishekar did you end up solving it?

**Comment by keerthishekar** [comment]
Nope. I tried removal of onnx still didnt work. One thing that worked was i ended up creating a new user on my Mac and it worked there. No issues with Onnx. Will try to remove python and re add it. Conda and venv are always all over the place.

**Comment by ciaranbaselmans** [comment]
I am having the same issue. I think it's caused by a bug in uv https://github.com/astral-sh/uv/issues/9228. I tried using different versions python, downgrading uv, downgrading onnxruntime but nothing seems to work. I guess using a pre-uv older version of crewAI is a short term solution

**Comment by keerthishekar** [comment]
I tried running 0.79.4 and 0.79.0 version of crewai as well. The issue still persists.

**Comment by mjgradright** [comment]
@ciaranbaselmans , I created the ticket and closed it as my query was answered. Although I did not try the proposed solution as I don't have a mac that supports newer OS. Will try older CrewAI versions. Currently working with a different tech stack to continue with the project.
