### ISSUE TITLE
LiteLLM doesn't like huggingface or ollama.

### ISSUE THREAD

**Issue by Logikschleifen** [crewAIInc/crewAI#1600]
### Description

I'm trying to use memory on my basic crew. I've tried the code from the docs:
https://docs.crewai.com/concepts/memory

Huggingface wasn't working because I think I don't know where to get a api_url for the model I want. So I switched to ollama. 

Now I just get:

```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


Provider List: https://docs.litellm.ai/docs/providers
```

I tried going into the package to learn more but all I can tell is it's trying to use my groq model (one I have set up for agents)? Makes no sense. When I remove memory I have no issues. 

Here is my crew , I had also tried to pass it a embedding function, both versions of this are broken the same way:

```
	@crew
	def crew(self) -> Crew:
		"""Creates the WritingCrew crew"""
		return Crew(
			agents=self.agents, # Automatically created by the @agent decorator
			tasks=self.tasks, # Automatically created by the @task decorator
			process=Process.sequential,
			memory=True,
			verbose=False,
			embedder=embedding_functions.OllamaEmbeddingFunction(
				url="http://localhost:11434/api/embeddings",
				model_name="nomic-embed-text"
			)
			# embedder={
			# 	"provider": "ollama",
			# 	"config": {
			# 		"model": "nomic-embed-text"
			# 	} 
			# }
		)
```

### Steps to Reproduce

Run the code I have with basic groq agents from the template made by crew.

### Expected behavior

It works?

### Screenshots/Code snippets

Already did, didn't notice these boxes when I made description.

### Operating System

Windows 11

### Python Version

3.10

### crewAI Version

0.79.4

### crewAI Tools Version

0.79.4

### Virtual Environment

Conda

### Evidence

Already did

### Possible Solution

Make my own memory functions.

### Additional context

NA

**Comment by ipeevski** [comment]
Here is what works for me for ollama:

```
Agent(
	...,
	llm=LLM(
		model = "ollama/llama-3.1", # Note you have to prepend "ollama" infront of whatever ollama shows when you do ollama ls
		base_url = "http://localhost:11434"
	)
)
```
