### ISSUE TITLE
[BUG] kickoff_for_each ignores the fact that the task is conditional

### ISSUE THREAD

**Issue by aaalexlit** [crewAIInc/crewAI#1629]
### Description

When executed using crew.kickoff_for_each a conditional task always gets executed ignoring the condition.

### Steps to Reproduce

`result = WithConditionalTaskCrew().crew().kickoff_for_each(inputs=inputs)`
executes all the tasks ignoring the condition

whereas when using `kickoff` in a for cycle the condition gets handled properly:
```
    for input in inputs:
        results.append(WithConditionalTaskCrew().crew().kickoff(inputs=input))
```

### Expected behavior

Conditional task handled properly 

### Screenshots/Code snippets

see steps to reproduce

### Operating System

macOS Sonoma

### Python Version

3.11

### crewAI Version

0.70.1

### crewAI Tools Version

not important

### Virtual Environment

Conda

### Evidence

Trust me 😉 

### Possible Solution

I'm almost 100% sure that it has to do with crew cloning in `kickoff_for_each` with `copy` method and specifically the problem is in the `copy` method of the Task class since the [copied task is always of type Task](https://github.com/crewAIInc/crewAI/blob/0b9092702bc39f2f8bf823fa3543b9056404e5f4/src/crewai/task.py#L347), so the ConditionalTask type gets lost when copying
If you agree lmk if you'd like me to contribute with a fix

### Additional context

-

**Comment by cristi-constantin** [comment]
Today I encountered the same issue
