### ISSUE TITLE
[FEATURE] GithubSearchTool include Anthropic

### ISSUE THREAD

**Issue by khalidmaquilang** [crewAIInc/crewAI#1647]
### Feature Area

Core functionality

### Is your feature request related to a an existing bug? Please link it here.

NA

### Describe the solution you'd like

Currently only `'openai', 'gpt4all', 'huggingface', 'vertexai', 'azure_openai', 'google', 'mistralai', 'clarifai', 'nvidia', 'ollama', 'cohere', 'aws_bedrock'` are supported by GithubSearchTool and I would like to add Anthropic for this

### Willingness to Contribute

No, I'm just suggesting the idea

**Comment by theCyberTech** [comment]
Anthropic does not support embeddings unfortunately, so you will have to use one of the above

**Comment by khalidmaquilang** [comment]
too bad.. ill just create my own tools then thank you..
