### ISSUE TITLE
[BUG]  LLM configuration defaults to OpenAI despite specifying a different LLM

### ISSUE THREAD

**Issue by bhav09** [crewAIInc/crewAI#1677]
### Description

When attempting to configure a custom LLM (gemini/gemini-1.5-pro-002), the system still defaults to using OpenAI's credentials and prompts for OPENAI_API_KEY. This occurs even though the LLM object has been explicitly configured with the Gemini API key and model.

### Steps to Reproduce

1. Code mentioned below
```
from crewai import Agent, Task, Crew, LLM
from dotenv import load_dotenv
import os
load_dotenv()

os.environ['GEMINI_API_KEY'] = os.getenv('GEMINI')
llm = LLM(
    model="gemini/gemini-1.5-pro-002",
    api_key=os.getenv('GEMINI'),
    max_tokens=2000,
    temperature=0.7
)

new_agent1 = Agent(llm=llm, ...)
crew = Crew(
    agents=[new_agent1, 
            new_agent2],
    tasks=[task1, 
           task2],
    verbose=1,
    memory=True,
)
```

2. Execute the script
3. Observe that the system prompts for OPENAI_API_KEY, despite using gemini/gemini-1.5-pro-002 as the specified model.

### Expected behavior

The system should utilize the custom LLM (gemini/gemini-1.5-pro-002) with the provided API key and configuration. It should not attempt to reference OpenAI or require OPENAI_API_KEY.

### Screenshots/Code snippets
```
2024-11-30 01:14:12,952 - 8140354112 - __init__.py-__init__:537 - WARNING: Overriding of current TracerProvider is not allowed
ValidationError                           Traceback (most recent call last)

ValidationError: 1 validation error for Crew
  Value error, Please provide an OpenAI API key. You can get one at https://platform.openai.com/account/api-keys [type=value_error, input_value={'agents': [Agent(role=Sa...ose': 1, 'memory': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/value_error
```

### Operating System

Other (specify in additional context)

### Python Version

3.12

### crewAI Version

0.80.0

### crewAI Tools Version

0.14.0

### Virtual Environment

Venv

### Evidence

ValidationError                           Traceback (most recent call last)

ValidationError: 1 validation error for Crew
  Value error, Please provide an OpenAI API key. You can get one at https://platform.openai.com/account/api-keys [type=value_error, input_value={'agents': [Agent(role=Sa...ose': 1, 'memory': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/value_error

### Possible Solution

None

### Additional context

None

**Comment by theCyberTech** [comment]
When setting  memory=True, on your agents memory will default to OpenAI for embeddinsg

See here for info on how to setup correct embeddinsg

https://docs.crewai.com/concepts/memory#additional-embedding-providers

**Comment by bhav09** [comment]
Thank you for the help :)
