### ISSUE TITLE
[BUG]issue with builtin litellm while running watsonx application using crewai version 0.83.0 and above

### ISSUE THREAD

**Issue by adharshctr** [crewAIInc/crewAI#1708]
### Description

While running watsonx application using crewai 0.83.0, we are getting the below error

litellm.exceptions.BadRequestError: litellm.BadRequestError: watsonxException - {"errors":[{"code":"model_no_support_for_function","message":"Model 'ibm/granite-13b-chat-v2' does not support function 'function_text_chat'","more_info":"https://cloud.ibm.com/apidocs/watsonx-ai"}],"trace":"*********","status_code":400}

But it works when we downgrade the litellm version to 1.52.0

### Steps to Reproduce

1. install crewai==0.83.0
2. run the basic watsonx application using LLM from crewai

from crewai import Agent, Task, Crew, Process, LLM
WATSONX_MODEL_ID = "watsonx/ibm/granite-13b-chat-v2"
llm= LLM(
    model=WATSONX_MODEL_ID,
    max_tokens=2000,
    temperature=0.7
)

### Expected behavior

Crew should work perfectly

![image](https://github.com/user-attachments/assets/43be0fc3-dc36-43ee-98a0-1418d2ffcab0)

### Screenshots/Code snippets

Error
![image](https://github.com/user-attachments/assets/f2563a20-f316-4eb6-9d2b-9c89c0e0de23)

### Operating System

Ubuntu 20.04

### Python Version

3.10

### crewAI Version

0.83.0

### crewAI Tools Version

0.14.0

### Virtual Environment

Venv

### Evidence

![image](https://github.com/user-attachments/assets/f2563a20-f316-4eb6-9d2b-9c89c0e0de23)

### Possible Solution

Issue with litellm version

### Additional context

litellm exception

**Comment by naredlarohithreddy** [comment]
@adharshctr  how did you solved the error? im too using watsonx mistralai , getting these errors and also did you use allow_delegation parameter? any idea of how it works.
