### ISSUE TITLE
[BUG] Default embedder initialization attempts OpenAI API key even with Azure configuration

### ISSUE THREAD

**Issue by ericklima-ca** [crewAIInc/crewAI#1797]
### Description

When using a `TextFileKnowledgeSource` with a custom embedder configuration for Azure, the library attempts to initialize the default OpenAI embedder before the custom configuration is applied. This behavior results in a `ValueError` being thrown, as no OpenAI API key is provided.

The documentation states that it is possible to pass a custom embedder configuration, but the `TextFileKnowledgeSource` seems to initialize the default embedder prematurely. This leads to an error when using Azure configurations.

### Steps to Reproduce

1. Create a `TextFileKnowledgeSource` pointing to a text file (e.g., `knowledge/base.txt`).
2. Instantiate a `Crew` with a custom Azure embedder:
   ```python
   embedder=OpenAIEmbeddingFunction(
       api_key=os.getenv("AZURE_API_KEY"),
       api_version=os.getenv("AZURE_API_VERSION"),
       base=os.getenv("AZURE_API_BASE"),
       model_name=os.getenv("AZURE_API_MODEL"),
       type="azure"
   )
   ```
3. Attempt to initialize the `Crew`.
4. Observe the `ValueError` stating "Please provide an OpenAI API key."

### Expected behavior

The `TextFileKnowledgeSource` should respect the custom embedder configuration passed to the `Crew` and not attempt to initialize the default OpenAI embedder.

### Screenshots/Code snippets

Error encountered:
```
ValueError: Please provide an OpenAI API key. You can get one at https://platform.openai.com/account/api-keys
An error occurred while running the crew: Command '['uv', 'run', 'run_crew']' returned non-zero exit status 1.
```

Code snippet for reproduction:
```python
from crewai.knowledge.source.text_file_knowledge_source import TextFileKnowledgeSource
from chromadb.utils.embedding_functions.openai_embedding_function import OpenAIEmbeddingFunction

base = TextFileKnowledgeSource(file_path="knowledge/base.txt")

crew = Crew(
    knowledge_sources=[base],
    embedder=OpenAIEmbeddingFunction(
        api_key=os.getenv("AZURE_API_KEY"),
        api_version=os.getenv("AZURE_API_VERSION"),
        base=os.getenv("AZURE_API_BASE"),
        model_name=os.getenv("AZURE_API_MODEL"),
        type="azure",
    )
)
```

### Operating System

Ubuntu 20.04

### Python Version

3.12

### crewAI Version

0.86.0

### crewAI Tools Version

0.17.0

### Virtual Environment

Venv

### Evidence

- Logs indicate that the `_create_default_embedding_function` is called before the custom embedder configuration is applied.
- Documentation example implies this should work seamlessly:
  ```python
  embedder={
      "provider": "openai",
      "config": {"model": "text-embedding-3-small"},
  }
  ```

### Possible Solution

The library should delay the initialization of the embedder until after the custom configuration is fully applied. Alternatively, allow explicit overrides in the `TextFileKnowledgeSource` instantiation.

### Additional context

This issue blocks the usage of Azure as an embedding provider when working with `TextFileKnowledgeSource`.

**Comment by mtcolman** [comment]
I believe this is related to #1790 and others. There are a number of threads on this topic on crew discord

**Comment by ericklima-ca** [comment]
### Possible Solution

In the file located at [https://github.com/crewAIInc/crewAI/blob/6cc2f510bf737b0053ae01a8a6d5582086ae5ec0/src/crewai/knowledge/knowledge.py#L23](https://github.com/crewAIInc/crewAI/blob/6cc2f510bf737b0053ae01a8a6d5582086ae5ec0/src/crewai/knowledge/knowledge.py#L23), making the following change resolves the issue:

```diff
-    storage: KnowledgeStorage = Field(default_factory=KnowledgeStorage)
+    storage: KnowledgeStorage = Field(default=None)
```

This modification prevents the default embedder initialization and allows using a custom embedder configuration for Azure. 

However, the following additional steps are necessary:
1. **Manually instantiate a `KnowledgeStorage` object** with the custom (Azure) embedder configuration (`embedder_config`).
2. **Pass the custom configuration** during the instantiation of `Crew`.

---

### Entire Code with Fix Applied

```python
import os
from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task
from crewai.knowledge.source.text_file_knowledge_source import TextFileKnowledgeSource
from aicrawler.tools.web_search_tool import search_and_scrape
from crewai.knowledge.storage.knowledge_storage import KnowledgeStorage

# Define custom Azure embedder configuration
embedder_config = {
    "provider": "azure",
    "config": {
        "api_key": os.getenv("AZURE_API_KEY"),
        "api_version": os.getenv('AZURE_API_VERSION'),
        "api_base": os.getenv('AZURE_API_BASE'),
        "api_type": 'azure',
        "model": os.getenv('AZURE_API_EMBEDDING_MODEL'),
    },
}

# Initialize custom KnowledgeStorage with Azure embedder
storage = KnowledgeStorage(embedder_config=embedder_config)

# Define TextFileKnowledgeSource with custom storage
base = TextFileKnowledgeSource(
    file_path="base.txt",
    storage=storage,
)

# Crew definition
@CrewBase
class Aicrawler():
    """Aicrawler crew"""

    agents_config = 'config/agents.yaml'
    tasks_config = 'config/tasks.yaml'

    @agent
    def specs_researcher(self) -> Agent:
        return Agent(
            config=self.agents_config['specs_researcher'],
            verbose=True,
            llm=os.getenv("MODEL"),
            max_iter=2,
            tools=[search_and_scrape],
        )

    @agent
    def product_registration_analyst(self) -> Agent:
        return Agent(
            config=self.agents_config['product_registration_analyst'],
            verbose=True,
            llm=os.getenv("MODEL"),
            max_iter=2,
        )

    @task
    def research_task(self) -> Task:
        return Task(
            config=self.tasks_config['research_task'],
        )

    @task
    def product_registration_task(self) -> Task:
        return Task(
            config=self.tasks_config['product_registration_task'],
        )

    @crew
    def crew(self) -> Crew:
        """Creates the Aicrawler crew"""
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
            memory=False,
            knowledge_sources=[base],
            embedder=embedder_config,
        )
```

---

### Summary of Fix:
- The default embedder initialization in `KnowledgeStorage` was replaced by a manual instantiation.
- A custom Azure embedder configuration (`embedder_config`) is used in both the `KnowledgeStorage` initialization and the `Crew` instantiation.
- The fix allows proper use of Azure as an embedding provider without triggering the default OpenAI embedder.
