### ISSUE TITLE
[BUG]An error occurred when crewai create crew myproject, but it was normal when I opened raw.githubusercontent.com with a browser.

### ISSUE THREAD

**Issue by wwwrookie** [crewAIInc/crewAI#1806]
### Description

An error occurred when crewai create crew myproject, but it was normal when I opened raw.githubusercontent.com with a browser.
![image](https://github.com/user-attachments/assets/34f1f040-cc4c-4d51-926f-6cb0b308a184)

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/43754a45-a7ae-4477-ae74-470df5a36251)

### Expected behavior

crewai create crew myproject ：The directory structure generated after the crewai create crew myproject command is executed, but it is different from the official website and incomplete.
![image](https://github.com/user-attachments/assets/95640a80-b31d-4cd4-b944-f447b13bb624)

### Screenshots/Code snippets

无

### Operating System

Ubuntu 24.04

### Python Version

3.11

### crewAI Version

0.86

### crewAI Tools Version

0.17

### Virtual Environment

Conda

### Evidence

![image](https://github.com/user-attachments/assets/cdb1d454-e720-4864-935c-d67ede55f259)

### Possible Solution

无

### Additional context

无

**Comment by theCyberTech** [comment]
![CleanShot 2024-12-27 at 12 59 48@2x](https://github.com/user-attachments/assets/9c4b3b21-7244-497d-894c-0a29138df941)

This is working fine for me, please try again most likely an issue upstream
