### ISSUE TITLE
[BUG] Error executing tool(Delegate work to coworker). coworker mentioned not found

### ISSUE THREAD

**Issue by pedropmartiniano** [crewAIInc/crewAI#1823]
### Description

I'm getting an error using a hierarquical crew when my manager agent uses the delegate tool to delegate the task to one of my agents, and it says that the agent is not in the valid agents list.

that's my crew code:

`
from crewai import Agent, Crew, Process, Task, LLM
from crewai.project import CrewBase, agent, crew, task, tool
from configs.env import get_env
from infrastructure.crewai.tools import QdrantSimilaritySearchTool

@CrewBase
class CloudioChatCrew:

    agents_config = get_env('AGENTS_CONFIG_PATH')
    tasks_config = get_env('TASKS_CONFIG_PATH')

    @agent
    def manager_agent(self) -> Agent:
        return Agent(
            config=self.agents_config['manager_agent'],
            llm=LLM(model='gpt-4o', temperature=0),
            verbose=True,
            allow_delegation=True
        )

    @agent
    def kb_retriever_agent(self) -> Agent:
        tool = QdrantSimilaritySearchTool()

        return Agent(
            config=self.agents_config['kb_retriever_agent'],
            llm=LLM(model='gpt-4o-mini', temperature=0),
            tools=[tool],
            verbose=True
        )

    @task
    def manager_task(self) -> Task:
        return Task(
            config=self.tasks_config['manager_task'],
            verbose=True
        )

    @crew
    def crew(self) -> Crew:
        return Crew(
            agents=[self.kb_retriever_agent()],
            tasks=self.tasks,
            verbose=True,
            process=Process.hierarchical,
            manager_agent=self.manager_agent(),
            respect_context_window=True,
            memory=True,
            planning=True
        )

`

that's the tool error that I'm getting:

`
Agent: manager_agent
Thought: Thought: Since the `kb_retriever_agent` is available, I will delegate the task to this agent to provide a comprehensive response to the user's query about knowledge base articles for SQL Server backup procedures.
Using tool: Delegate work to coworker
Tool Input: 
"{\"task\": \"Provide a comprehensive response to the user's query about knowledge base articles for SQL Server backup procedures.\", \"context\": \"The user needs to know which KBs can help with backing up SQL Server databases. The question is: 'preciso saber quais KB's que me ajudem a fazer um backup do meu banco SQL Server'.\", \"coworker\": \"kb_retriever_agent\"}"
Tool Output: 

Error executing tool. coworker mentioned not found, it must be one of the following options:
- manager_agent
`

### Steps to Reproduce

1. create a hierarquical crew using the yaml templates. 2. use a custom manager agent. 3. create another custom agent that uses a custom tool. 4. execute the crew trying to make the manager uses the delegate work to coworker

### Expected behavior

the expected behavior would be for my agent to be on the list of the "delegate work to coworker" tool

### Screenshots/Code snippets

![image (5)](https://github.com/user-attachments/assets/d544ec55-8c98-4164-8de4-48fc5ee81cbc)

### Operating System

Ubuntu 20.04

### Python Version

3.12

### crewAI Version

0.86.0

### crewAI Tools Version

0.17.0

### Virtual Environment

Venv

### Evidence

![image (5)](https://github.com/user-attachments/assets/01b05ec1-19fc-4c27-8760-3cc5c77db050)

### Possible Solution

Put all the functions with the decorator `@agent` at this list of that manager tool.

### Additional context

I'm using the yaml templates to create my agents and tasks

**Comment by joaomdmoura** [comment]
We are cutting a new version later tonight or tomorrow with the fix tho :)

**Comment by pedropmartiniano** [comment]
This bug was already fixed or not yet?

**Comment by joshylhs** [comment]
> This bug was already fixed or not yet?

same here!

**Comment by Saadkhh** [comment]
> > This bug was already fixed or not yet?
> 
> same here!

Same, is there a fix?
