### ISSUE TITLE
[BUG]Failed to build `tiktoken` while running `pip install crewai`

### ISSUE THREAD

**Issue by Spartan-71** [crewAIInc/crewAI#1824]
### Description

The build for `tiktoken==0.7.0` while install `crewai`

### Steps to Reproduce

Run `pip install crewai` or `uv pip install crewai`

### Expected behavior

The build for `tiktoken` should not fail

### Screenshots/Code snippets

![image](https://github.com/user-attachments/assets/c755b6a4-667e-428f-adaf-3e975b65ba09)
![image](https://github.com/user-attachments/assets/38aa11b2-8a2a-49c5-ae9f-080bc5c54e95)

### Operating System

Other (specify in additional context)

### Python Version

3.12

### crewAI Version

v0.86.0

### crewAI Tools Version

none

### Virtual Environment

Venv

### Evidence

![image](https://github.com/user-attachments/assets/c755b6a4-667e-428f-adaf-3e975b65ba09)

### Possible Solution

None

### Additional context

OS : Arch Linux
Python Version : 3.13.1

**Comment by joaomdmoura** [comment]
Merged a fix that shoudl address this in main, it will be in the new version later today but you can test directly from main if you want to :D
Also added new instruction to readme about it, great flag @Spartan-71 , if this doesn't help it lmk and I'll reopen the issue
