### ISSUE TITLE
looping tasks

### ISSUE THREAD

**Issue by chriscamacho** [crewAIInc/crewAI#183]
Ideally I'd like to do something like this...

1 programming agent creates code
2 testing agent runs code in repl and provides feedback given some example require output
  testing passed goes to set 4
3 programming agent takes code from step 2 re-codes and goes to step 2
4 resulting code is presented

so this is 3 tasks really, but in particular step 2 needs a way to complete the whole process and step 3 needs a way to be able to get back to step 2

**Comment by Biancamazzi** [comment]
don't forget we have https://chat.openai.com/g/g-qqTuUWsBY-crewai-assistant to help and also the discord community https://discord.com/invite/X4JWnZnxPb

**Comment by punitchauhan771** [comment]
Hey @chriscamacho ,

 I came across your scenario and thought Langraph might be a cool tool to check out. It seems like it could fit the bill for what you're looking for.

 Just in case, here's a handy link that shows how to get started with Langraph for Crew.ai: https://github.com/CrewAI-LangGraph .

Hope this helps!

**Comment by punitchauhan771** [comment]
Hey @chriscamacho ,

 I came across your scenario and thought Langraph might be a cool tool to check out. It seems like it could fit the bill for what you're looking for.

 Just in case, here's a handy link that shows how to get started with Langraph for Crew.ai: https://github.com/joaomdmoura/crewAI-examples/tree/main/CrewAI-LangGraph

 Hope this helps!

**Comment by Kolaposki** [comment]
Check out the ``task.execute()`` method.

That's what I use to get the output of a task and then move on to the next task or perform some operations. You can also use task.output which simply just gives you the result of the executed task.

**Comment by Toppbeatz** [comment]
I been trying to figure out how to do the same thing.
