### ISSUE TITLE
How can we pass the pandas dataframe among the agents?

### ISSUE THREAD

**Issue by raymondyao** [crewAIInc/crewAI#203]
I want to create a scenario to analyze, preprocess and even do machine learning on the pandas dataframe using crewAI. I can create a customized tool for processing a pandas dataframe. I want to know how to pass the transformed dataframe to another agent.

**Comment by pradeepdev-1995** [comment]
Any update on this?

**Comment by samosun** [comment]
Any update on this?

**Comment by rao208** [comment]
@raymondyao: were you able to pass the pandas dataframe to the custom tool? I am unable to pass. I have pydantic schema to validate the input type. The run fails and gives the error

```
"Input should be an instance of DataFrame [type=is_instance_of, input_value={'description': 'Anomaly ...dic
t(orient='records')"}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/is_instance_of.
 Tool AnomalyPrediction accepts these inputs: Tool Name: AnomalyPrediction
Tool Arguments: {'dataframe': {'description': None, 'type': 'DataFrame'}}
Tool Description: This tool predicts anomalies in the given pandas.DataFrame"
```

Any idea how to resolve this issue?

**Comment by chuxinliu** [comment]
I am able to pass very small pandas dataframe using to_dict, basically converting it to a dictionary/json
I think it does not scale though, anyone can help?
