### ISSUE TITLE
How to get the intermidate output from the agent

### ISSUE THREAD

**Issue by yeshwant1995** [crewAIInc/crewAI#208]
`import os
from crewai import Agent, Task, Crew, Process

os.environ["OPENAI_API_KEY"] = "YOUR KEY"

from langchain.tools import DuckDuckGoSearchRun
search_tool = DuckDuckGoSearchRun()

researcher = Agent(
  role='Senior Research Analyst',
  goal='Uncover cutting-edge developments in AI and data science',
  backstory="""You work at a leading tech think tank.
  Your expertise lies in identifying emerging trends.
  You have a knack for dissecting complex data and presenting
  actionable insights.""",
  verbose=True,
  allow_delegation=False,
  tools=[search_tool]
)
writer = Agent(
  role='Tech Content Strategist',
  goal='Craft compelling content on tech advancements',
  backstory="""You are a renowned Content Strategist, known for
  your insightful and engaging articles.
  You transform complex concepts into compelling narratives.""",
  verbose=True,
  allow_delegation=True,
)

task1 = Task(
  description="""Conduct a comprehensive analysis of the latest advancements in AI in 2024.
  Identify key trends, breakthrough technologies, and potential industry impacts.
  Your final answer MUST be a full analysis report""",
  agent=researcher
)

task2 = Task(
  description="""Using the insights provided, develop an engaging blog
  post that highlights the most significant AI advancements.
  Your post should be informative yet accessible, catering to a tech-savvy audience.
  Make it sound cool, avoid complex words so it doesn't sound like AI.
  Your final answer MUST be the full blog post of at least 4 paragraphs.""",
  agent=writer
)

crew = Crew(
  agents=[researcher, writer],
  tasks=[task1, task2],
  verbose=2, # You can set it to 1 or 2 to different logging levels
)

result = crew.kickoff()

print("######################")
print(result)`

**I want to get the reasearcher output maunally and pass it to writer, since i have tool in writer agent which take input.
how to do it?**

**Comment by Kolaposki** [comment]
task1.execute() or task1.output should work for you.

**Comment by Lindesfahl** [comment]
Hello, where is the tool for writer agent to take input ? i dont see it in the code. I would like to use that method to get all the agents outputs but i dont know how to implement the awnser from Kolaposki in my crew code.
If someone could help ?

**Comment by pjaol** [comment]
I just released a logger for langchain that works with CrewAI, it might help you

https://github.com/thevgergroup/langchain-logger

**Comment by Lindesfahl** [comment]
That’s great!As soon as I have time I will try the logger! It seems that I have problems to give the agents the parameters/tasks in a way they understand…Greetings ChorumVon meinem iPhone gesendetAm 13.03.2024 um 18:17 schrieb patrick oleary ***@***.***>:﻿
I just released a logger for langchain that works with CrewAI, it might help you
https://github.com/thevgergroup/langchain-logger

**Comment by harishvs** [comment]
what is the data type of task1.output
