### ISSUE TITLE
Cant join discord "unable to accept invite"

### ISSUE THREAD

**Issue by bilallamal07** [crewAIInc/crewAI#209]
Hello guys, can  you please the discord server admins give me access  l`m getting unable  to access for some reasons or verify my user? niro_2020, l have already login in before with no problems please note l can login to other discord servers without any issue
Many Thanks

**Comment by joaomdmoura** [comment]
Hey @bilallamal07 where did you click on the link, it might be an old like I forgot to update, this one should work: [Discord](https://discord.com/invite/X4JWnZnxPb)

**Comment by bilallamal07** [comment]
Hello Joaomdmoura

Sorry to disturb you l`m still experiencing this login issue saying *enable
to accept the invite*
l have tried the vpn and without vpn, bear in mind the other discord server
works with a vpn
with no issues, could please check with admin

Kindest Regards

Bilal

**Comment by bilallamal07** [comment]
Still no joy   ### **Enable to accept invite**
