### ISSUE TITLE
Default Agent LLM factory Mistral/other OpenAI compatible API problem

### ISSUE THREAD

**Issue by michaelwdombek** [crewAIInc/crewAI#216]
Hi @ all

after some discussions in discord and testing with mistral it seems that the agent setup cases some problems.

https://github.com/joaomdmoura/crewAI/blob/2f0bf3b325c86d913ec0c58a280c85120330776d/src/crewai/agent.py#L94-L99

Right now if I do not explicitly set the LLM.model value, anything that is passed as variable is getting overwritten by the default factory. 

```
export OPENAI_API_KEY=your-mistral-api-key                                  # ok
export OPENAI_API_BASE=https://api.mistral.ai/v1                          # ok
export MODEL_NAME="mistral-medium"                                           # get over written by default factory setting model="gpt4"

```
I can think of two solutions:
- remove the default to gp4 and only add it in __post_init__ after checking for the system environment variables
- write a general wrapper around the agent instantiation that supports alternative settings i.e using the specific implementations from different llm providers.

I'm in discord up for discussion :)
cheers Michael

**Comment by jmbenedetto** [comment]
Me too!

**Comment by whoabuddy** [comment]
Possibly related to #244 ?

**Comment by joaomdmoura** [comment]
Fixing this with a new patch and updating the docs tonight
