### ISSUE TITLE
How to udate to the latest version? How to know which version is installed?

### ISSUE THREAD

**Issue by Zirgite** [crewAIInc/crewAI#219]
How to update to the newest version? Is it enough to run again
 pip install crewai 

How to know which version is installed? In the code structure I do not find document saying which version is running.

**Comment by koktavy** [comment]
`pip list`
will show you the packages you have installed and the versions.

`pip install crewai --upgrade`
will upgrade to the latest, v0.5.0

**Comment by whoabuddy** [comment]
You can also do `pip show crewai` to get info, e.g.

```
$ pip show crewai
Name: crewai
Version: 0.10.0
Summary: Cutting-edge framework for orchestrating role-playing, autonomous AI agents. By fostering collaborative intelligence, CrewAI empowers agents to work together seamlessly, tackling complex tasks.
Home-page: 
Author: Joao Moura
Author-email: joao@crewai.com
License: 
Location: /home/whoabuddy/miniconda3/envs/crewai-0-10-0/lib/python3.11/site-packages
Requires: langchain, langchain-openai, openai, opentelemetry-api, opentelemetry-exporter-otlp-proto-http, opentelemetry-sdk, pydantic
Required-by: 
```

**Comment by dlangleyDXC** [comment]
I try the "pip install crewai --upgrade" but I get:
"Requirement already up-to-date: crewai in ./.local/lib/python3.8/site-packages (0.1.7)"
I am using Python3.12.3. I don't know why it saved to that folder
