### ISSUE TITLE
any way of easier "debugging" what agents are saying in the run?

### ISSUE THREAD

**Issue by dakipro** [crewAIInc/crewAI#220]
Hi,
love the script!
I wonder if there is (and if not if it could be added) some way of visualizing what agents are thinking and doing. 
With a lot of text and instructions, it is very cumbersome to follow what was happening in the console

Thanks!

**Comment by joaomdmoura** [comment]
I hear you, is that a specific style you would like these to be on, a dashboard maybe of sorts?

**Comment by dakipro** [comment]
it would be easiest to use something existing I guess. I like the "gamification" and visualization that devchat has, but it is also difficult to customize (the advantage of crewAI). How does LangChain do that? It is already used in crewAI...

but a simple parser, or a simple HTML with accordions to review the chain after the fact would be helpful. Especially now with several processes. Who said what and to whom. Simple but useful :)

nice job with the project btw, thank you for making it. I've tried them all, and crewai is so far the easiest and goes straight to the point, at least for me for video content creation of 3min youtube videos (if you want to make an example on that usecase - it would be awesome :) )

**Comment by ZmeiGorynych** [comment]
I'd love to see that example ;)

**Comment by JaDenis** [comment]
I agree, langsmith-like logs would be perfect, but I’d be 100% happy with a json :)
My interest lies in collecting prompts agents are sending to each other. These prompts are often crazy good and could be useful to collect.

**Comment by ZmeiGorynych** [comment]
If https://github.com/joaomdmoura/crewAI/pull/246 is accepted, you could just use eg a Langchain agent and LangSmith :)
