### ISSUE TITLE
Adding other agents as tools to an agent who allows delegation could be done at crew creation time, to allow recursive delegation

### ISSUE THREAD

**Issue by ZmeiGorynych** [crewAIInc/crewAI#234]
When I read the code, I see that the other agents are only made available as tools to a task's agent during task execution time. This means that recursive delegation ( A delegates to B, B delegates to C) is impossible, right? 
Is that a deliberate decision?
Seems non-intuitive to me: if I create an agent with `allow_delegation=True`, I'd expect it to be able to delegate regardless of whether it's the agent associated to a task (and even then, only while running that task). 
If you really want to prohibit recursive delegation, you could have a Task-level `allow_delegation` parameter which would produce the current behavior, whereas the agent-level `allow_delegation=True` would result in the other agents being added to that agent's tools at crew creation time.
That would be more logical as well as more flexible, no?

**Comment by ZmeiGorynych** [comment]
Happy to submit a PR if you would consider it ;)

**Comment by ZmeiGorynych** [comment]
And another reason to do this: if we want to allow (suitably wrapped) other agents into a crew (such as those made with LCEL), they will often expect to be initialized with all the tools at creation time, and not provide an easy way to update the tools at runtime, short of re-creating the agent (and thus destroying its memory, if any). 
So calling the agent from each Task with a potentially different set of tools will be less natural than initializing the wrapped agent once during crew.kickoff() with both its own tools and the other agents as tools.

**Comment by naredlarohithreddy** [comment]
@ZmeiGorynych  i have a doubt when we create an agent with allow_delegation=True , how will the second agent takes the output and the context from the first agent and vice versa as we allowed delegation.

should we just simply mention natural language queries or any input format is available?

**Comment by ZmeiGorynych** [comment]
Not really sure how CrewAI does it these days, as I stopped following really closely when my PR on the above was ignored :)
In MotleyCrew.ai, which I then built, agents are just given as regular tools to the main agent (and so on, if needed), so the main agent just passes the relevant information in the request it makes to the relevant sub-agent/tool. I think that's a good thing, as typically the agent used as a tool performs a specialized task that doesn't need the whole context of the parent agent. Back when I wrote the above, CrewAI worked the same way, maybe it still does.

**Comment by naredlarohithreddy** [comment]
will give MotleyCrew.ai a shot. does it support watsonx.ai models?

**Comment by ZmeiGorynych** [comment]
It supports anything that is supported in Langchain and/or llamaindex (depending on which agents you want to use, our default ReACT agent is Langchain-based). [Here is how to integrate a new LLM](https://motleycrew.readthedocs.io/en/latest/choosing_llms.html#using-custom-llms). And Langchain does have a watsonx wrapper, so you should be fine - please ping our Discord if you run into any issues!
