### ISSUE TITLE
README example is giving a 500 error

### ISSUE THREAD

**Issue by howagain** [crewAIInc/crewAI#244]
I was trying to follow the basic example and I'm getting a 500 response from OpenAI. Tried with multiple api keys and multiple envs (local, colab, and codespaces). Thinking it might be something with the way that crew is formatting the request. Is anyone else getting this?

**Comment by whoabuddy** [comment]
I'm having issues with my previously-working OpenAI drop-in API with a local model + textgen.

I'm either getting 500 errors or 404 depending on config.

**Comment by joaomdmoura** [comment]
Hey @howagain can you share more about the example you were trying to run? I just tested the one on README and it worked, what LLM are you using?
