### ISSUE TITLE
RAG implementation in CREWAI

### ISSUE THREAD

**Issue by NeethanShetty07** [crewAIInc/crewAI#247]
Hi,

Is there any method implemented which we can link RAG method with agents.

**Comment by ZmeiGorynych** [comment]
You could run off this branch https://github.com/joaomdmoura/crewAI/pull/246 and use a LangChain agent with RAG? :)

**Comment by slavakurilyak** [comment]
Similar to issue #18

RAG with tools example here: https://mer.vin/2024/02/crewai-rag-using-tools/

**Comment by slavakurilyak** [comment]
[RAG](https://github.com/joaomdmoura/crewai-tools/tree/main/crewai_tools/tools/rag) is now part of [crewai-tools](https://github.com/joaomdmoura/crewai-tools)

**Comment by NeethanShetty07** [comment]
Hi  @slavakurilyak Thanks for the response

**Comment by NeethanShetty07** [comment]
Can we attach any pdf or any document and do RAG on these documents using Agents ??

**Comment by ilyasudakov** [comment]
> Can we attach any pdf or any document and do RAG on these documents using Agents ??

@NeethanShetty07 Yeah, I got it working, here's a simple example with `.txt` file:
```python
from crewai_tools.tools import TXTSearchTool
rag_tool = TXTSearchTool(txt='./sample_data/test.txt')

data_analyst = Agent(
  role='Data Analyst',
  goal='You perfectly know how to analyze any data using provided txt file and searching info via RAG tool',
  backstory='You are data expert',
  verbose=True,
  allow_delegation=False,
  tools=[rag_tool]
)

test_task = Task(
  description="Show me a company name",
  tools=[rag_tool],
  agent=data_analyst
)

test_task.execute()
```

**Comment by Neethan54** [comment]
But i have AzureOPENAI key , But TXTSearchTool is asking OPENAI key for the process , how to do solve this issue?

**Comment by P7201** [comment]
I am having the exact same problem as Neethan54 can anyone please let us know how we pass in the key from AzureOpenAI for the TXTSearchtool?

**Comment by SL13PNIR** [comment]
Bump.

Do [tools](https://docs.crewai.com/core-concepts/Tools/#available-crewai-tools) need Open AI keys? I'm trying to use the PDFSearchTool with Mistral, assumed I'd only need OpenAI keys for using an Open AI llm.

**Comment by thekizoch** [comment]
Im having the same issue as @Neethan54 and @P7201 , for Azure OpenAI for PDFSearchTool

**Comment by manojselvakumar** [comment]
I'd like to understand the same. How to use Azure OpenAI for PDFSearchTool?

**Comment by ItzmeAkash** [comment]
how to use groq and  other embeddings on PDFSearchTool anyone knows??

**Comment by theholymath** [comment]
It seems `embedchain` is making changes to their config for embeddings. Does this help get PDFSearchTool working for Azure? Is there an example of how to get the config working with an Azure subscription?

**Comment by cbarkinozer** [comment]
From the theory, the way tools (function calling) work is by comparing the request's embedding with the tool's description's embedding (vector distance measurement). Therefore tools require an embedding_model. I checked the source code and did the following. The CrewAI framework checks if there is an embedding_model_config given and if not it tries to use OpenAI Embeddings by default. To solve this I used a config dict you can see from the below example:
```
    rag_tool = DOCXSearchTool(
        docx='C:\\Repos\\myproject\\myfolders\\mydocument.docx',
        config={"embedding_model": {
            "provider": "huggingface",
            "config": { "model": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"}
            }
        }
    )
```
Later, the CrewAI framework asked me to download the "docx2txt" package to work, which you can do by running this command: "pip install docx2txt" and it worked without a problem afterwards.

I also had a similar problem with the memory which I solved similarly: [https://github.com/joaomdmoura/crewAI/issues/769#issuecomment-2190041975](https://github.com/joaomdmoura/crewAI/issues/769#issuecomment-2190041975)

**Comment by suvom24** [comment]
[cbarkinozer] Thanks for providing the config. it's working with TXTSearchTool also,

`TXTSearchTool_custom = TXTSearchTool(
    config=dict(
        llm=dict(
            provider="google", 
            config=dict(
                model="gemini-1.5-flash",
            )
            
        ),
        embedding_model ={"provider": "huggingface",
                  "config": { "model": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"}
                  }

        ),
    )
`
