### ISSUE TITLE
What is "output" argument in the Task class, in the documentation it only shows output: TaskOutput | None = None, I want to know how to use it.

### ISSUE THREAD

**Issue by artzuros** [crewAIInc/crewAI#249]
I want to save the "verbose" or the thought process of an individual agents' task, so I looked through the documentation but could only find the "output" argument. I would like to know how to use it. 
Whenever I try to assign it to some object it returns this error.

```ValidationError: 1 validation error for Task
output
  Input should be a valid dictionary or instance of TaskOutput [type=model_type, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type```

**Comment by whoabuddy** [comment]
You can see it in the source here #630
