### ISSUE TITLE
Obtaining chat history?

### ISSUE THREAD

**Issue by nick-youngblut** [crewAIInc/crewAI#261]
`Agent()` includes the `verbose=True` param, but that seems to just print the chat info. 

I would like to store the entire chat history in a time-based vector database (e.g., timescaledb)
and include an agent that can assess the progress of the crew based on the entire history of the crew (e.g., "have we already tried that solution (or similar), and did it work?", or "when we previously tried that solution, the crew predicted that we were (closer/further) away from solving the overall task").  

How does one obtain the chat history for each agent in a crew?

Also, if you have any thoughts on using a time-based vector database for storing the chat history, I'd appreciate any thoughts. The same goes for including >=1 agent for just predicting whether the crew is closer/further away from the goal at each Nth time step (similar to how the vertebrate brain is constantly predicting future reward).

**Comment by bpmcgough** [comment]
@nick-youngblut Could you just pass a callback at the Agent level that writes to your db on each step? It's also available at the Crew and Task level but Agent might be more appropriate for your situation. See `step_callback` at https://docs.crewai.com/core-concepts/Agents/#agent-attributes.
