### ISSUE TITLE
Sequential page in the documentation give 404

### ISSUE THREAD

**Issue by yamz8** [crewAIInc/crewAI#267]
https://docs.crewai.com/how-to/how-to/Sequential -

**Comment by ilyasudakov** [comment]
@yamz8 Pretty sure this is fixed now: https://docs.crewai.com/how-to/Sequential/
https://github.com/joaomdmoura/crewAI/blob/8e4b156f114b836de36b54913a6661bfcce87b7e/mkdocs.yml#L131
