### ISSUE TITLE
pydantic conversion problem

### ISSUE THREAD

**Issue by Natureboy100** [crewAIInc/crewAI#272]
Failed to convert text into a pydantic model due to the following error: Unexpected message with type <class 'langchain_core.messages.system.SystemMessage'> at the position 1.

i keep getting this for everything, just to give some context it doesnt work with gemini at all and it used to work, alot of gemini projects of many diffrnet people that used to work that dont work at all.

**Comment by Natureboy100** [comment]
i would like to update that this error happens only with gemini i have tried many diffrent gemini projects from github on colab and gitpod and they all give the same problems.

**Comment by vnakhate** [comment]
I have the same issue with Gemini as well on Google colab

**Comment by ethanreedy-DC** [comment]
I just upgraded today to 0.16.3 and probably skipped a few releases. Now I'm getting this same error when using Gemini, but not Mixtral on TogetherAI.

**Comment by joaomdmoura** [comment]
Yup it seems gemini doesn't do the function calling, we are working on na
fix that should come out this week still where we will revamp some of the
tool usage logic
--
João Moura
@joaomdmoura <http://twitter.com/joaomdmoura>


Em qui., 29 de fev. de 2024 às 23:44, ethanreedy-DC <
***@***.***> escreveu:
