### ISSUE TITLE
Streamlit Integration

### ISSUE THREAD

**Issue by slavakurilyak** [crewAIInc/crewAI#275]
It would be great to see [Streamlit](https://github.com/streamlit/streamlit) integration with crewAI so these crews can escape from their terminals, pun intended

Related issue [here](https://github.com/joaomdmoura/crewAI-examples/issues/43)

**Comment by slavakurilyak** [comment]
Here's an example implementation by @amadad: 

https://github.com/amadad/civic-agentcy

**Comment by speaks999** [comment]
The example above shows the final output but not the log messages. Need to be able to have the logs write to st.write_stream somehow.

**Comment by slavakurilyak** [comment]
@tonykipkemboi do you tackle this one? 

Your [trip_planner_agent](https://github.com/tonykipkemboi/trip_planner_agent) would benefit from this

**Comment by speaks999** [comment]
Using step_callback=st.write in the agent startup will get you started but there must be a more elegant way.

**Comment by slavakurilyak** [comment]
Check out [multi-agent-streamlit-ui](https://github.com/camel-ai/multi-agent-streamlit-ui) by @camel-ai for inspiration

**Comment by tonykipkemboi** [comment]
So I played with the trip planner app last night for a few minutes trying to implement the streaming logs on the app under **st.status**.

The challenge lies in redirecting the logger outputs from CrewAI agents into the Streamlit app in a way that allows for near real-time updates. 

I tried redirecting the logs to the Streamlit UI but that did not work so I ended up modifying the Crewai source code under the **utilities/logger.py** and was able to get some logs printed on the app but some others (the green log text in console) haven't got to it yet. This is not the best way to do this and maybe I just need a little brainstorming session with @joaomdmoura to get this part working.

**Comment by slavakurilyak** [comment]
@joaomdmoura it would be great to have your input on this

**Comment by chrispangg** [comment]
Maybe modifying the Agent class execute_task() method to take in a langchain callback handler can be part of the solution? Langchain has a streamlit handler https://python.langchain.com/docs/integrations/callbacks/streamlit

Example on how to pass in a handler to invoke():
```
        from langchain_core.callbacks import StdOutCallbackHandler
        handler = StdOutCallbackHandler()

        result = self.agent_executor.invoke(
            {
                "input": task_prompt,
                "tool_names": self.agent_executor.tools_names,
                "tools": self.agent_executor.tools_description,
            },
            **configs={"callbacks": [handler]}**
        )["output"]
```

**Comment by chrispangg** [comment]
I was able to get some of the green log text in the console printed by modifying the agent.py file with the following:

1. Add a callback
      ```
          callbacks: Optional[List[InstanceOf[BaseCallbackHandler]]] = Field(
              default=None, description="Callbacks to be executed"
          )
      ```
2. In create_agent_executor() in the same Agent.py file, add the following
        ```
        self.agent_executor = CrewAgentExecutor(
            agent=RunnableAgent(runnable=inner_agent),
            **executor_args,
            callbacks=self.callbacks,
        )
        ```
3. Pass in the callback handler (using StdOutCallbackHandler as an example) when creating the agent:
        ```
        from langchain_core.callbacks import StdOutCallbackHandler
        callback_handler = StdOutCallbackHandler()
        finance_researcher = Agent(
            role="Finance Research Analyst",
            goal="Provide up-to-date finance market data analysis",
            backstory="An expert analyst with a keen eye for market trends.",
            tools=[web_search, web_scraper],
            callbacks=[callback_handler],
        )
        ```

**Comment by speaks999** [comment]
This would be a great start. The next step would be to facilitate the human in the loop somehow. @joaomdmoura do you have a plan for this? Are you going to incorporate the change above? Thx

**Comment by chrispangg** [comment]
PR for the suggested change [here](https://github.com/joaomdmoura/crewAI/pull/333)

**Comment by tonykipkemboi** [comment]
Thanks for getting this out @chrispangg. I barely got time to keep looking into this.

**Comment by chrispangg** [comment]
PR merged - also added a full example to the PR
https://github.com/joaomdmoura/crewAI/pull/333

**Comment by slavakurilyak** [comment]
@chrispangg really appreciate you implementing this

@joaomdmoura It would be great to see a how-to guide for this streamlit integration

**Comment by Pusse-01** [comment]
I want to take human inputs when executing the agents. According to the documentation we can take it from the terminal by enabling hunan_input from the task. But any methods to get it from the streamlit app and give it to the agent? Any method to get user feedbacks while executing the agents?

**Comment by nethi** [comment]
It looks like callbacks is no longer supported in the recent versions
https://github.com/crewAIInc/crewAI/commit/e77442cf3414d963c89464e4b5cd12b8104985bb

**Comment by RicardoFRocha** [comment]
> It looks like callbacks is no longer supported in the recent versions [e77442c](https://github.com/crewAIInc/crewAI/commit/e77442cf3414d963c89464e4b5cd12b8104985bb)

What's the alternative? Without UI the crew ai solution the value proposition is much smaller!
