### ISSUE TITLE
ImportError: cannot import name 'formatargspec' from 'inspect' (C:\anaconda3\Lib\inspect.py)

### ISSUE THREAD

**Issue by LeventeNagy** [crewAIInc/crewAI#290]
Anyone any idea why this is happening?

just by importing Agents and tasks

`from crewai import Agent, Task, Crew, Process`

I get the following error 

`ImportError: cannot import name 'formatargspec' from 'inspect' (C:\anaconda3\Lib\inspect.py)`

Never really came across this problem ever 

Python version 3.11.5

**Comment by greysonlalonde** [comment]
@LeventeNagy Need more info here (full traceback, are you using conda for env management?)
