### ISSUE TITLE
zsh: no matches found: crewai[tools]

### ISSUE THREAD

**Issue by therohitdas** [crewAIInc/crewAI#304]
<img width="1310" alt="Screenshot 2024-03-03 at 11 26 39 PM" src="https://github.com/joaomdmoura/crewAI/assets/43847374/b19cd624-1699-43a9-bdbf-ff9916c3c65b">

When using zsh, the pip install command returns an unnecessary error. 

If we amend the docs to suggest the command with quotes, it can run everywhere without issue.

```zsh
pip install "crewai[tools]"
```

**Comment by picsoung** [comment]
fixed in #305
