### ISSUE TITLE
Can we stream output from crew.kickoff() to chainlit app?

### ISSUE THREAD

**Issue by rounakskm** [crewAIInc/crewAI#307]
Hello, 
I am trying to build an interactive crew using chainlit. 
Is there any way to stream the output from crew.kickoff() onto chainlit? 
Also to take human input through the chainlit app for taking next steps etc.

**Comment by PiotrEsse** [comment]
Additionally, how to visualize/show intermediate steps where agents share some info.

**Comment by thekizoch** [comment]
would also love to see this is action

**Comment by francisjervis** [comment]
Possibly useful: [`How to Use Human as Tool with crewai Agents on chainlit UI
`](https://medium.com/@pratyush.talent/using-human-as-tool-with-crewai-in-chainlit-da063dea0e31)

**Comment by vishwasnm** [comment]
Found a more recent article - https://krishankantsinghal.medium.com/supercharge-your-conversational-ai-integrating-chainlit-and-crewai-for-powerful-interactions-ca8a50ec1851

If there are other articles which could be used to stream the intermediate steps in crewai onto chainlit, please comment below.

**Comment by tituslhy** [comment]
There's a GitHub repo that has attempted this:

https://github.com/AbubakrChan/crewai-business-product-launch

The approach here is to save sys.stdout as a variable and then perform regex to make the stream not look so raw. But I've found this to not be very aesthetically pleasing.

Does the medium article have a GitHub repo link?

**Comment by agnivabanerjee** [comment]
would be great to have crewai return step results in a way that is compatible.
