### ISSUE TITLE
FastAPI and intermediate steps of Tasks and Agents

### ISSUE THREAD

**Issue by sofiafernandescd** [crewAIInc/crewAI#318]
Hello, thanks for this massive project!

I'm building a UI in Chainlit, for my project with crewAI, and I want to isolate crewAI calls in API calls, using FastAPI, but I'm struggling in getting the intermediate steps, and the endpoint ends up outputing only the final answer. 

What is the best way to run a crew, and orchestrate a solution where Chainlit calls several FastAPI endpoints, one of them including the tool, tool_input and log of the intermediary steps?

Thanks in advance 🙏

**Comment by amazingnerd** [comment]
I'm also looking for it. By the way, where did you read about how to get the CrewAI endpoint? I have not using ChatGPT Plus so I cannot chat with Crew Assistant.

**Comment by UmutAlihan** [comment]
I assume you should write a CustomTool for that by inheriting the BaseTool.
