### ISSUE TITLE
Multiple file read tools provide same content

### ISSUE THREAD

**Issue by LarsAC** [crewAIInc/crewAI#319]
Hello,

I have tried to set up a crew where one agent / task uses two FileReadTools with different file arguments:

```
file1_tool = FileReadTool(file_path="./file1.json")
file2_tool = FileReadTool(file_path="./file2.txt")

[...]

researcher = Agent(
	role='Researcher',
	goal='You research interesting projects in the automotive industry.',
    backstory="You work as freelancer and write for magazines.",
    verbose = True,
    tools = [file1_tool, file2_tool],
)

[...]

research_task = Task(
  description="""Find out facts about interesting projects in the automotive industry.""",
  expected_output="""A description of a project developing new cars.""",
  agent = researcher,
  tools = [file1_tool, file2_tool]
)
```

However, execution of the crew runs into a message, that the two files have the same content, but in fact they are different:

```
Thought: 
The second file contains the exact same data as the first file. This means that I don't have additional information about the project's goals, innovations, and potential impact on the industry. However, based on the information available, I can still provide a basic overview of the project.
```

Is this a bug or anything I need to modify on my end to use contents of two files in the same task / agent ?

Lars

**Comment by gadgethome** [comment]
Could you try the tool DirectoryReadTool 

This will allow the agent with this tool to read only the directory specified during it's execution
tool = DirectoryReadTool(directory='./directory')

**Comment by LarsAC** [comment]
That does not seem to do what I want:

```

Action 'Read file' don't exist, these are the only available Actions: List files in directory: List files in directory() - A tool that can be used to list ./testdocs's content.

Thought: 
Given that I only have the 'List files in directory' tool available and not a 'Read file' tool, I am unable to provide detailed, specific information about a new project in the automotive industry. However, I can provide a general structure for the article based on my experience and expertise in the field. 
```

**Comment by yshean** [comment]
I encountered the same problem. Different files but same output by the FileReadTool, even though by manual inspection they have a completely different content.

**Comment by amir-the-java-positive** [comment]
we have encountered same issue. any plans when will it be fixed?

**Comment by theCyberTech** [comment]
Why are you assign the two tasks to the same agent? Why not assign to an agent each?

**Comment by yshean** [comment]
> Why are you assign the two tasks to the same agent? Why not assign to an agent each?

What do you mean? There is only one task for each agent, but an agent could access multiple tools (in this case, two file read tools, one for each file)

**Comment by theCyberTech** [comment]
Sorry I meant tools, so for example each tool gets assigned to its own agent

**Comment by amir-the-java-positive** [comment]
is there any limit or problem if you assign more than one (fileread) tools in one agent ?  to my knowledge, agents to tool mapping is not 1:1 or is it?  
Thanks for your clarification in advance.

**Comment by alexfazio** [comment]
Hello. I am experiencing the same problem with the `DirectoryReadTool`.

```
> Entering new CrewAgentExecutor chain...
From these variables, it seems like my task is to return the name of all the folders within the directory "output-files". For this, I can use the "List files in directory" tool.

Action: List files in directory
Action Input: {"directory": "./output-files"} 

File paths: 
-

Thought: 
From the above observations, it seems that I am not allowed to use the tool to achieve the task. Without using the tool, I'm unable to gather the information needed to complete the task as I can't list the files in the directory. 

Final Answer: 
Unable to provide the final answer because the tool needed to perform the task is not allowed to be used.
```

Check this notebook to reproduce the error.
https://colab.research.google.com/drive/1BvUQfXcr-gw-We07xRNpuqF0PgOr0eoP?usp=sharing

**Comment by alexfazio** [comment]
I just tested this in version `0.30.0rc3` and it still has problems. 

Refer to this notebook for a quick reproduction of the issue:
https://colab.research.google.com/drive/1BvUQfXcr-gw-We07xRNpuqF0PgOr0eoP?usp=sharing

**Comment by felixgao** [comment]
I am still seeing the same problem in `0.30.11` Is there a fix or workaround?

**Comment by Alezipa** [comment]
I'm running with the same issue. Any ideas?

**Comment by AdelDima** [comment]
1- Use `FileReadTool` without any parameters and send it to the agent.
2- on the agent `goal` add the files that you want to read like this
```python
goal=f"""
Understand files. from
{path_storyline_01} and {path_toryline_02}
""",
```

**Comment by ricardolousada** [comment]
I don't understand how can the issue be close without being solved....I have just used the last versions and have exactly the same problem!?

**Comment by ricardolousada** [comment]
> 1- Use `FileReadTool` without any parameters and send it to the agent. 2- on the agent `goal` add the files that you want to read like this
> 
> ```python
> goal=f"""
> Understand files. from
> {path_storyline_01} and {path_toryline_02}
> """,
> ```

Imagine you have 20 or more files, this is crazy.....

**Comment by akshay-rakheja** [comment]
> 1- Use `FileReadTool` without any parameters and send it to the agent. 2- on the agent `goal` add the files that you want to read like this
> 
> ```python
> goal=f"""
> Understand files. from
> {path_storyline_01} and {path_toryline_02}
> """,
> ```

This worked for me

**Comment by saalmaan** [comment]
Here he the code snippet on how to pass multiple files to agent for new python folks, passing multiple instances of FileReadTool wont work to instead do this as suggest above

```python
#other imports
from crewai_tools import tool, FileReadTool

file_read_tool = FileReadTool() #< this is what you pass to agent's tool

file_path_01 = 'folder/file1.txt' #< this is what you pass to agent's goal
file_path_02 = 'folder/file2.txt' #< this is what you pass to agent's goal

Agent1 = Agent(
    role="Agent Role",
    goal=f""" analyse these files {cvpath} and {jobspecpath} """,  #< passed file paths here
    backstory="""backstory """,
    tools=[file_read_tool, search], #add any other tools you want #< passed empty FileReadTool instances
    verbose=True,  # enable more detailed or extensive output
    allow_delegation=True,  # enable collaboration between agent
    llm=llm
)
    #code continues
```
