### ISSUE TITLE
 Could not build wheels for chroma-hnswlib

### ISSUE THREAD

**Issue by joaolvivas** [crewAIInc/crewAI#344]
Has anyone experienced this issue before?

Could it be something related to my Python version?

<img width="869" alt="Screenshot 2024-03-12 at 7 59 10 PM" src="https://github.com/joaomdmoura/crewAI/assets/163067796/5fd26a37-3f14-4f43-9b18-010cc4e6a86c">

**Comment by joaolvivas** [comment]
I fixed this by downgrading my Python version to 3.10.

Thanks.

**Comment by Traveltainer007** [comment]
Ive upgraded to 3.12 and the MSVSC C++ on win10 pro and everything downloads and installs except the chromalib 
I also rebooted 

│ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hnswlib' extension
      creating build
      creating build\temp.win32-cpython-312
      creating build\temp.win32-cpython-312\Release
      creating build\temp.win32-cpython-312\Release\python_bindings
      "D:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX86\x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\user\AppData\Local\Temp\pip-build-env-4_9y2dxx\overlay\Lib\site-packages\pybind11\include -IC:\Users\user\AppData\Local\Temp\pip-build-env-4_9y2dxx\overlay\Lib\site-packages\numpy\core\include -I./hnswlib/ -IC:\Users\user\AppData\Local\Programs\Python\Python312\include -IC:\Users\user\AppData\Local\Programs\Python\Python312\Include "-ID:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-ID:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-ID:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-ID:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /EHsc /Tp./python_bindings/bindings.cpp /Fobuild\temp.win32-cpython-312\Release\./python_bindings/bindings.obj /EHsc /openmp /O2 /DVERSION_INFO=\\\"0.7.3\\\"
      bindings.cpp
      D:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\yvals.h(20): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
      error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chroma-hnswlib
Failed to build chroma-hnswlib

**Comment by j-dominguez9** [comment]
Still getting this error.

system: Fedora Linux 39
python version: 3.12.2

Why is chroma-hnswlib even a dependency?

**Comment by Kei1yn** [comment]
Is there any progress to it? 

I am too getting the same error, trying suggested actions did not help so far.

**Comment by Kei1yn** [comment]
What worked for me was installing the [VS Build Tools](https://github.com/bycloudai/InstallVSBuildToolsWindows?tab=readme-ov-file).

**Comment by Cap0n3** [comment]
> Still getting this error.
> 
> system: Fedora Linux 39 python version: 3.12.2
> 
> Why is chroma-hnswlib even a dependency?

To resolve this issue on Fedora version 32 or newer, you'll need to install the equivalent of the build-essential package. Execute the following command in the terminal to install the necessary development tools and libraries:

```console
sudo dnf groupinstall "Development Tools" "Development Libraries"
```

**Comment by Free-Radical** [comment]
For Ubuntu 22  fix-

```
sudo apt install python3-dev
sudo apt-get install build-essential -y
```

**Comment by ZealLab** [comment]
> What worked for me was installing the [VS Build Tools](https://github.com/bycloudai/InstallVSBuildToolsWindows?tab=readme-ov-file).

This worked for me

**Comment by huangpan2507** [comment]
> apt-get install build-essential -y

it workds for me!!!!!

**Comment by HarishChandran3304** [comment]
> > Still getting this error.
> > system: Fedora Linux 39 python version: 3.12.2
> > Why is chroma-hnswlib even a dependency?
> 
> To resolve this issue on Fedora version 32 or newer, you'll need to install the equivalent of the build-essential package. Execute the following command in the terminal to install the necessary development tools and libraries:
> 
> ```
> sudo dnf groupinstall "Development Tools" "Development Libraries"
> ```

Worked for me, thank you!

**Comment by TentionLin** [comment]
> For Ubuntu 22 fix-
> 
> ```
> sudo apt install python3-dev
> sudo apt-get install build-essential -y
> ```

@Free-Radical Fixed the issue, thank you!
