### ISSUE TITLE
Bug: Error when trying to create a project with multiple Crews

### ISSUE THREAD

**Issue by wagnerdriva** [crewAIInc/crewAI#346]
I created a project that would have two crews, one called BoardCrew and another called DataOpsCrew, using the new decorators from the latest version. When he started to install and run the first crew, I received the following error:

```
   File "/home/wagner/projects/driva/driva-crew-ai/.venv/lib/python3.10/site-packages/crewai/project/annotations.py", line 23, in wrapper
     possible_task = getattr(self, task_name)
AttributeError: 'WrappedClass' object has no attribute 'sql_developer_task'
```

Looking at the source code, I discovered that it is because it tries to fetch the sql_developer_task from the other crew in the wrapper. This generates the error, since the getattr function returns an error when we do not define a default value. In this case I changed from `getattr(self, task_name)` to `getattr(self, task_name, None)`.

**Comment by mhdhazmi** [comment]
I am facing the same issue with multiple crews

**Comment by joaomdmoura** [comment]
I think we now fixed this in main, would you folks mind double checking this in case?
