### ISSUE TITLE
A.I. Agent Report: I encountered an error while trying to use the tool. This was the error: 'SERPER_API_KEY'.

### ISSUE THREAD

**Issue by BracerJack** [crewAIInc/crewAI#352]
I copied and pasted the example code directly from the Crew A.I. front page just to get a taste of what this does.
I am using Ollama.

I kept on getting:
I encountered an error while trying to use the tool. This was the error: 'SERPER_API_KEY'.
 Tool Search the internet accepts these inputs: Search the internet(search_query: 'string') - A tool that can be used to semantic search a query from a txt's content.

That message appeared 11 times.
After that, the final blog message appears:
Final Answer:
The year 2023 marked a significant milestone in the development of Artificial Intelligence (AI), with numerous advancements taking place across various sectors. Some key trends bla bla bla~

I didn't add anything new to the code; everything is "as is,"  direct "copy and paste" from the front page, only that I am connecting it with Ollama local A.I.

How do I resolve this message that appears 11 times?

**Comment by WorldICTown** [comment]
I thoroughly enjoyed reading this.Learned a lot. The writing style is PROFESSIONAL, and the content is both interesting and valuable. Looking forward to more! By the way,if you have any ICs' need, find all your chip needs at https://www.worldictown.com/ – your one-stop destination for a diverse range of chips and solutions.You can contact us on Worldictown
