### ISSUE TITLE
Hierarchical process: Agents only run once

### ISSUE THREAD

**Issue by rabejens** [crewAIInc/crewAI#355]
I am trying to set up a crew with three agents. They should perform a task hierarchically. For the task to complete, they should talk to each other back and forth, so the crew manager should i.e. delegate a subtask to agent A, this gives a result where the manager can then delegate to agent B. When agent B comes back and the result is then to be processed by agent A again, this never happens. All agents are only ever ran once.

Am I missing some settings or is this currently by design?

Edit: if the agent can run several of the subtasks without returning or delegating, it does it. The agent is only not re-ran when another agent runs in between.

**Comment by aliensouls** [comment]
I'm also curious about non sequential modes for this, how did you made them run several subtasks and in which order? if you make multiple task objects and assign them all to same agent, how do you know the order in which it will run them? this is something I didn't find in the docs 🧐 .
a back and forth loop in hierarchical mode would be amazing, I hope it's possible to make it work, will be experimenting with it soon 🧑‍🍳
