### ISSUE TITLE
Add support of g4f

### ISSUE THREAD

**Issue by pencilvania** [crewAIInc/crewAI#367]
Hi Guys

I added gpt4free (import g4f) https://github.com/xtekky/gpt4free and using it , but the problem is when I want using tools like WebsiteSearchTool
it seems need to OPENAI_API_KEY when we are using even llm
can it be integrated ?

**Comment by rrfaria** [comment]
looking at documentation
I guess you can run it by running a docker container 
```shell
docker pull hlohaus789/g4f
docker run -p 8080:8080 -p 1337:1337 -p 7900:7900 --shm-size="2g" hlohaus789/g4f:latest
```

it exposes an api for you
```
http://localhost:1337/v1
```
and you can use this api with openAi lib
```python
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    openai_api_base="http://localhost:1337/v1",
    openai_api_key="anything_noneeded",
    model_name="gpt-3.5-turbo"
)

... 
# code of your agents
Agent(
      role='your role',
      goal='your goal.',
      verbose=True,
      backstory="""your backstory""",
      allow_delegation=True,
      llm=llm,
    )
```
Pass llm to your agents and it will work

**Comment by WorldICTown** [comment]
I thoroughly enjoyed reading this.Learned a lot. The writing style is PROFESSIONAL, and the content is both interesting and valuable. Looking forward to more! By the way,if you have any ICs' need, find all your chip needs at https://www.worldictown.com/ – your one-stop destination for a diverse range of chips and solutions.You can contact us on Worldictown
