### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by greysonlalonde** [crewAIInc/crewAI#37]
@joaomdmoura Is there a project roadmap or anything similar ? I'd like to sync up on this so I can contribute more efficiently.

**Comment by joaomdmoura** [comment]
@greysonlalonde good call, what is your X handle so I can DM you? I think we can put something together in Github itself, but there are options

**Comment by joaomdmoura** [comment]
Added you but seems I can't message you, feel free to shoot me an email at joao@ainestlabs.com and we can take from there

**Comment by greysonlalonde** [comment]
@joaomdmoura Weird! Just sent you an email

**Comment by leoffx** [comment]
@joaomdmoura I would be curious to know about the roadmap as well

> I think we can put something together in Github itself

sounds like a good idea
