### ISSUE TITLE
AttributeError: 'str' object has no attribute 'bind'. Did you mean: 'find'?

### ISSUE THREAD

**Issue by charlesbiggs07** [crewAIInc/crewAI#376]
When following the Getting Started documentation (using the provided code). When I run it, I get the following error:
AttributeError: 'str' object has no attribute 'bind'. Did you mean: 'find'?

I'm running this in VSCode now but I get the same error in PyCharm_Community, as well as if I follow the Linux instructions in wsl.

Also, I'm following the directions to connect to Ollama.
Also tried running on another windows machine; same result.

My code:
from crewai import Agent, Task, Crew, Process
from langchain_community.llms import Ollama

OPENAI_API_BASE='http://localhost:11434/v1'
OPENAI_MODEL_NAME='mistral'  # Adjust based on available model
OPENAI_API_KEY=''

ollama_mistral=Ollama(model='mistral')

researcher = Agent(
    role='Researcher',
    goal='Research ai trends',
    backstory='You are an AI reseach assistant.',
    verbose=True,
    allow_delegation=False,
    llm='mistral'
)

writer = Agent(
    role='Writer',
    goal='Write a blog post about ai trends.',
    backstory='You are an internet blog post writer.',
    verbose=True,
    allow_delegation=False,
    llm='mistral'
)

task1 = Task(description='Investigate latest AI trends.', agent=researcher)
task2 = Task(description='Write a blog post about the latest ai trends.', agent=writer)

crew = Crew(
    agents=[researcher, writer],
    tasks=[task1, task2],
    verbose=2,
    process=Process.sequential
)
result = crew.kickoff()

**Comment by amansingh9097** [comment]
has anyone found any work around? I'm also facing this issue.

**Comment by LordJABA** [comment]
same for me when trying to make "hello world"

**Comment by thomas-latterner** [comment]
Same for me when I try to use another LLM (other than GPT with OpenAI, Azure for instance)
