### ISSUE TITLE
Dependency error using tool GithubSearchTool

### ISSUE THREAD

**Issue by nikolaidk** [crewAIInc/crewAI#380]
Iam testing out CrewAI and encountered an error while trying to use the tool GithubSearchTool. This was the error: GithubLoader requires extra dependencies. Install with `pip install --upgrade 'embedchain[github]'`.
 Tool Search a github repo's content accepts these inputs: Search a github repo's content(search_query: 'string') - A tool that can be used to semantic search a query the https://github.com/shadcn-ui/ui/tree/main github repo's content.

Dependencies:
[tool.poetry.dependencies]
python = ">=3.10,<3.13"
crewai = {extras = ["tools"], version = "^0.22.5"}

Code:
github_search_tool = GithubSearchTool(
    
    github_repo=default_git_repo,
    content_types=['code'],
    gh_token=os.getenv("GITHUB_API_KEY"),
    config=dict(
        llm=dict(
            provider="openai",
            config=dict(
                model=default_model,
                temperature=0.0,
                top_p=1             
            ),
        ),
        embedder=dict(
            provider="openai",
            config=dict(
                model=default_embedding_model,
                task_type="retrieval_document"                            
            ),
        ),
    )
)

The behavior on error looks incorrect. On a dependency error the code should exit, but it continues ...

Action: Search a github repo's content

Action Input: {"search_query": "chat interface components"}
 

I encountered an error while trying to use the tool. This was the error: GithubLoader requires extra dependencies. Install with `pip install --upgrade 'embedchain[github]'`.
 Tool Search a github repo's content accepts these inputs: Search a github repo's content(search_query: 'string') - A tool that can be used to semantic search a query the https://github.com/shadcn-ui/ui/tree/main github repo's content.

Thought: Since my initial attempt to search the GitHub repository directly encountered an error, my next best step is to delegate this task to a co-worker who might have better luck or alternative methods to access the necessary information. I will ask a React developer to search for chat interface components within the specified GitHub repository, providing them with all the context they need to understand the task fully.

Action: Delegate work to co-worker

**Comment by WorldICTown** [comment]
I thoroughly enjoyed reading this.Learned a lot. The writing style is PROFESSIONAL, and the content is both interesting and valuable. Looking forward to more! By the way,if you have any ICs' need, find all your chip needs at https://www.worldictown.com/ – your one-stop destination for a diverse range of chips and solutions.You can contact us on Worldictown
