### ISSUE TITLE
How to custom translations

### ISSUE THREAD

**Issue by ly0303521** [crewAIInc/crewAI#381]
How can I custom the translations, as we can see in "i18n.py", dir_path is fixed，so I can rewrite the "python3.11/site-packages/crewai/translations/en.json", but I don't want to rewrite, Is there a better way?
`

    @model_validator(mode="after")
    def load_translation(self) -> "I18N":
        """Load translations from a JSON file based on the specified language."""
        try:
            dir_path = os.path.dirname(os.path.realpath(__file__))
            prompts_path = os.path.join(
                dir_path, f"../translations/{self.language}.json"
            )

            with open(prompts_path, "r") as f:
                self._translations = json.load(f)
        except FileNotFoundError:
            raise ValidationError(
                f"Translation file for language '{self.language}' not found."
            )
        except json.JSONDecodeError:
            raise ValidationError(f"Error decoding JSON from the prompts file.")

        if not self._translations:
            self._translations = {}

        return self

    def slice(self, slice: str) -> str:
        return self.retrieve("slices", slice)

    def errors(self, error: str) -> str:
        return self.retrieve("errors", error)

    def tools(self, error: str) -> str:
        return self.retrieve("tools", error)

    def retrieve(self, kind, key) -> str:
        try:
            return self._translations[kind][key]
        except:
            raise ValidationError(f"Translation for '{kind}':'{key}'  not found.")`

**Comment by cbarkinozer** [comment]
@ly0303521 There is an "en.json" file inside "C:\myproject\crew\venv\Lib\site-packages\crewai\translations", I copied the same file in the same folder and changed its name to "tr.json" and translated the values to Turkish. Later changed the part where you mentioned like below so "utf-8" characters do not cause an exception:
```py
 try:
            if self.language_file:
                with open(self.language_file, "r", encoding='utf-8') as f:
                    self._translations = json.load(f)
            else:
                dir_path = os.path.dirname(os.path.realpath(__file__))
                prompts_path = os.path.join(
                    dir_path, f"../translations/{self.language}.json"
                )

                with open(prompts_path, "r", encoding='utf-8') as f:
                    self._translations = json.load(f)
```

Even though the project began without a problem, it failed when using a tool. It might be compatible with your language translation. To address translation issues, I recommend using English prompts with "answer in <your language>" sentences in all agent and task prompts. LLMs also perform better in English prompts. Because these translations JSONs include crew.ai's inner working prompts, they should be tested thoroughly and later added by the crew.ai in my opinion.

**Comment by cbarkinozer** [comment]
> How can I custom the translations, as we can see in "i18n.py", dir_path is fixed，so I can rewrite the "python3.11/site-packages/crewai/translations/en.json", but I don't want to rewrite, Is there a better way? `
> 
> ```
> @model_validator(mode="after")
> def load_translation(self) -> "I18N":
>     """Load translations from a JSON file based on the specified language."""
>     try:
>         dir_path = os.path.dirname(os.path.realpath(__file__))
>         prompts_path = os.path.join(
>             dir_path, f"../translations/{self.language}.json"
>         )
> 
>         with open(prompts_path, "r") as f:
>             self._translations = json.load(f)
>     except FileNotFoundError:
>         raise ValidationError(
>             f"Translation file for language '{self.language}' not found."
>         )
>     except json.JSONDecodeError:
>         raise ValidationError(f"Error decoding JSON from the prompts file.")
> 
>     if not self._translations:
>         self._translations = {}
> 
>     return self
> 
> def slice(self, slice: str) -> str:
>     return self.retrieve("slices", slice)
> 
> def errors(self, error: str) -> str:
>     return self.retrieve("errors", error)
> 
> def tools(self, error: str) -> str:
>     return self.retrieve("tools", error)
> 
> def retrieve(self, kind, key) -> str:
>     try:
>         return self._translations[kind][key]
>     except:
>         raise ValidationError(f"Translation for '{kind}':'{key}'  not found.")`
> ```

I explained my trial and opinion of the solution about this topic here: https://github.com/joaomdmoura/crewAI/issues/532#issuecomment-2208890061
