### ISSUE TITLE
Deprecated reference: crewai[tools] locked to python-dotenv  v1.0.0

### ISSUE THREAD

**Issue by nikolaidk** [crewAIInc/crewAI#383]
Because crewai[tools] (0.22.5) depends on python-dotenv (1.0.0)
 and no versions of crewai match >0.22.5,<0.23.0, crewai[tools] (>=0.22.5,<0.23.0) requires python-dotenv (1.0.0).
So, because agentflow depends on both crewai[tools] (^0.22.5) and python-dotenv (^1.0.1), version solving failed.

**Comment by zboyles** [comment]
I was running into a similar issue with python-dotenv and one of the langchain libraries although I didn't have time to run it down so I created a new poetry project with `python = "^3.11, <3.12"`. In this empty project I tried to `poetry add "crewai[tools]" "unstructured[all-docs]"` and ran into different dependency issues. I'll include below incase it's of interest.

```sh
Because opentelemetry-sdk (1.23.0) depends on opentelemetry-api (1.23.0)
 and opentelemetry-sdk (1.22.0) depends on opentelemetry-api (1.22.0), opentelemetry-sdk (1.22.0 || 1.23.0) requires opentelemetry-api (1.22.0 || 1.23.0).
And because opentelemetry-api (1.23.0) depends on importlib-metadata (>=6.0,<7.0)
 and opentelemetry-api (1.22.0) depends on importlib-metadata (>=6.0,<7.0), opentelemetry-sdk (1.22.0 || 1.23.0) requires importlib-metadata (>=6.0,<7.0).
Because no versions of unstructured match >0.12.6,<0.13.0
 and unstructured (0.12.6) depends on importlib-metadata (7.0.1), unstructured (>=0.12.6,<0.13.0) requires importlib-metadata (7.0.1).
Thus, unstructured (>=0.12.6,<0.13.0) is incompatible with opentelemetry-sdk (1.22.0 || 1.23.0).
And because no versions of opentelemetry-sdk match >1.22.0,<1.23.0 || >1.23.0,<2.0.0, unstructured (>=0.12.6,<0.13.0) is incompatible with opentelemetry-sdk (>=1.22.0,<2.0.0).
And because crewai (0.22.5) depends on opentelemetry-sdk (>=1.22.0,<2.0.0)
 and no versions of crewai match >0.22.5,<0.23.0, unstructured (>=0.12.6,<0.13.0) is incompatible with crewai (>=0.22.5,<0.23.0).
So, because <project> depends on both crewai (^0.22.5) and unstructured (^0.12.6), version solving failed.
```

**Comment by joaomdmoura** [comment]
Oh looking into fixing this now for the next version that drops this week

Em ter., 26 de mar. de 2024 às 03:40, Zac ***@***.***>
escreveu:
