### ISSUE TITLE
Update ScrapeWebsiteTool Documentation

### ISSUE THREAD

**Issue by kjenney** [crewAIInc/crewAI#386]
The ScrapeWebsiteTool documentation example only shows how to initialize the class - not how to use it.

I opened a PR for this: https://github.com/joaomdmoura/crewAI/pull/385

**Comment by tiagodavi** [comment]
ScrapeWebsiteTool vs WebsiteSearchTool 
What are the differences between them?

Which one can I use to read the entire website by including its internal links/pages?

I am not sure whether they will either read the entire website or just the specified page.

I mean, all pages from the main provided page…
