### ISSUE TITLE
Vllm or Huggingface  for local LLMs  for CrewAI

### ISSUE THREAD

**Issue by rajeshkochi444** [crewAIInc/crewAI#388]
Would it be possible for us to use Huggingface or vLLM for loading models locally. Ollama implantation bit more challenging

**Comment by tridungduong-unsw** [comment]
I have the same request features.

**Comment by ITZRei** [comment]
I have the same request features.

**Comment by Atakey** [comment]
I have the same request features.

**Comment by ITZRei** [comment]
Hi, 

my solution on this request:

```python
from langchain_openai import ChatOpenAI as LOAI

os.environ["OPENAI_API_KEY"] = "NA"

llm_model = LOAI(base_url="http://your_endpoint/v1", model_name = 'your_model')

your_agent = Agent(
    role="Your Role",
    goal="Your goal",
    backstory="Your backstory",
    async_execution=False,
    allow_delegation = False,
    llm=llm_model
)
```
or setting the environment varaibles:

```python
os.environ["OPENAI_API_KEY"] = "NA"
os.environ["OPENAI_API_BASE"] = "Your Endpoint"
os.environ["OPENAI_MODEL_NAME"] = "Your Model"
```

I'm using the first solution because of the ability to use several models in my crew. The second is for those who only need one model.

**Comment by MohamedAliRashad** [comment]
This solution is giving me this
```
Provider List: https://docs.litellm.ai/docs/providers

ERROR:root:Failed to get supported params: argument of type 'NoneType' is not iterable
```

**Comment by ruianlc** [comment]
same situation here. anyone has solved it?

![Image](https://github.com/user-attachments/assets/93ec83ee-5fd9-463d-8809-d37e02621702)

**Comment by kellyaa** [comment]
You'll want to preface your model name with the provider.

I.e. for [VLLM](https://docs.litellm.ai/docs/providers/vllm) and llama3 it would be:
model="hosted_vllm/meta-llama/Llama-3.3-70B-Instruct"

**Comment by Pranjal-Tripathi-01** [comment]
> You'll want to preface your model name with the provider.
> 
> I.e. for [VLLM](https://docs.litellm.ai/docs/providers/vllm) and llama3 it would be: model="hosted_vllm/meta-llama/Llama-3.3-70B-Instruct"

I was working with vLLM hosted model and adding prefix "hosted_vllm/" worked for me. Thanks @kellyaa
