### ISSUE TITLE
Here's a hierarchical use case example with tool usage

### ISSUE THREAD

**Issue by donbr** [crewAIInc/crewAI#396]
Feel free to use it (or not).

This code will work under OpenAI GPT4 default configuration (after removing the tool config) :  [karpathy_tutor](https://github.com/donbr/karpathy_tutor)

Why I think clear examples are essential:  In spite of removing ChatOpenAI imports and keys from .env files, crewAI still managed to call the non-turbo version of GPT4 for all agent and tool requests.
- It would be appreciated if we can get this example working without depending on GPT4 for all LLM calls that don't require a huge context window.

**Comment by xitex** [comment]
You just need specify what model to use and attach it to all agent with llm parameter.
