### ISSUE TITLE
output_json bug with groq (also with  openai wrapper)

### ISSUE THREAD

**Issue by xitex** [crewAIInc/crewAI#398]
Hi, i create pydantic model with fields to fill in. I attach it to my task as output_json and with openai models its work well but with groq i get error.
This is how i create llm as i understand this is openai wrapper:
llm = ChatOpenAI(
    temperature=0,
    openai_api_base="https://api.groq.com/openai/v1",
    openai_api_key=os.getenv("GROQ_API_KEY"),
    model_name="mixtral-8x7b-32768"

)
and i create a task that have pydantic model and this work with openai but don't with groq (mixtral in my case)

 File "/python/3_11/venv/lib/python3.11/site-packages/crewai/crew.py", line 204, in kickoff
    result = self._run_sequential_process()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/python/3_11/venv/lib/python3.11/site-packages/crewai/crew.py", line 240, in _run_sequential_process
    output = task.execute(context=task_output)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/python/3_11/venv/lib/python3.11/site-packages/crewai/task.py", line 148, in execute
    result = self._execute(
             ^^^^^^^^^^^^^^
  File "/python/3_11/venv/lib/python3.11/site-packages/crewai/task.py", line 163, in _execute
    exported_output = self._export_output(result)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/crewai/task.py", line 213, in _export_output
    model_schema = PydanticSchemaParser(model=model).get_schema()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/python3.11/site-packages/crewai/utilities/pydantic_schema_parser.py", line 16, in get_schema
    return self._get_model_schema(self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/crewai/utilities/pydantic_schema_parser.py", line 21, in _get_model_schema
    field_type_str = self._get_field_type(field, depth + 1)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/python3.11/site-packages/crewai/utilities/pydantic_schema_parser.py", line 37, in _get_field_type
    elif issubclass(field_type, BaseModel):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 123, in __subclasscheck__
TypeError: issubclass() arg 1 must be a class

Thank you!!!

**Comment by jiveshkalra** [comment]
Did you find any solution? 
I am facing the exactly same problem

**Comment by xitex** [comment]
this method just not implemented so we waiting(

**Comment by xitex** [comment]
json output has been implemented in langchain, but it is called with invoke method. Can we count on implementation of this method or suggestion some temporary solution? https://python.langchain.com/docs/modules/model_io/chat/structured_output/

**Comment by johnsutor** [comment]
I'd be open to contributing to this.

**Comment by joaomdmoura** [comment]
Could you try defining the llm like this instead? Just want to double check if this could indica another bug

`pip install langchain-groq`

```python
from langchain_groq import ChatGroq
chat = ChatGroq(temperature=0, model_name="mixtral-8x7b-32768")
```

**Comment by joaomdmoura** [comment]
> https://python.langchain.com/docs/modules/model_io/chat/structured_output/

Looks interesting, I think we could try it for sure

**Comment by bitsnaps** [comment]
> Could you try defining the llm like this instead? Just want to double check if this could indica another bug
> 
> `pip install langchain-groq`
> 
> ```python
> from langchain_groq import ChatGroq
> llm = ChatGroq(temperature=0, model_name="mixtral-8x7b-32768")
> ```

It works for me, here is my setup:
```python
from langchain_groq import ChatGroq
from langchain_openai import ChatOpenAI

MODEL_NAME = 'mixtral-8x7b-32768'

#llm = ChatGroq(temperature=0.9, model_name = MODEL_NAME, api_key=os.environ["GROQ_API_KEY"])

# if the previous instruction doesn't work try this one:
llm = ChatOpenAI(model = MODEL_NAME, base_url = "https://api.groq.com/openai/v1", temperature=0.9, api_key=os.environ["GROQ_API_KEY"])

from crewai import Agent, Task, Crew, Process

# Define your agents with roles and goals
storyteller = Agent(
  role='Story teller for kids',
  goal='Write a nice educational story for kids.',
  backstory='You are a successfully story teller and world class ebooks best seller.',
  verbose=True,
  allow_delegation=False,
  # You can pass an optional llm attribute specifying what model you wanna use.
  # llm=ChatOpenAI(model_name="gpt-3.5", temperature=0.7),
  llm=llm
)

# Create tasks for your agents
task1 = Task(
  description="Write a short story.",
  expected_output="One paragraph of text.",
  agent=storyteller
)


# Instantiate your crew with a sequential process
crew = Crew(
  agents=[storyteller],
  tasks=[task1],
  verbose=2, # You can set it to 1 or 2 to different logging levels
)

# Get your crew to work!
result = crew.kickoff()

print("######################")
print(result)
```
Tested on colab.

**Comment by xitex** [comment]
> > Could you try defining the llm like this instead? Just want to double check if this could indica another bug
> > `pip install langchain-groq`
> > ```python
> > from langchain_groq import ChatGroq
> > llm = ChatGroq(temperature=0, model_name="mixtral-8x7b-32768")
> > ```
> 
> It works for me, here is my setup:
> 
> ```python
> from langchain_groq import ChatGroq
> from langchain_openai import ChatOpenAI
> 
> MODEL_NAME = 'mixtral-8x7b-32768'
> 
> #llm = ChatGroq(temperature=0.9, model_name = MODEL_NAME, api_key=os.environ["GROQ_API_KEY"])
> 
> # if the previous instruction doesn't work try this one:
> os.environ["OPENAI_API_KEY"] = GROQ_API_KEY
> os.environ["OPENAI_API_BASE"] = 'https://api.groq.com/openai/v1'
> os.environ["OPENAI_MODEL_NAME"] = MODEL_NAME  # Adjust based on available model
> llm = ChatOpenAI(model = MODEL_NAME, base_url = os.environ["OPENAI_API_BASE"], api_key=os.environ["OPENAI_API_KEY"])
> 
> from crewai import Agent, Task, Crew
> 
> # Define your agents with roles and goals
> storyteller = Agent(
>   role='Story teller for kids',
>   goal='Write a nice educational story for kids.',
>   backstory='You are a successfully story teller and world class ebooks best seller.',
>   verbose=True,
>   allow_delegation=False,
>   # You can pass an optional llm attribute specifying what model you wanna use.
>   # llm=ChatOpenAI(model_name="gpt-3.5", temperature=0.7),
>   llm=llm
> )
> 
> # Create tasks for your agents
> task1 = Task(
>   description="Write a short story.",
>   expected_output="One paragraph of text.",
>   agent=storyteller
> )
> 
> 
> # Instantiate your crew with a sequential process
> crew = Crew(
>   agents=[storyteller],
>   tasks=[task1],
>   verbose=2, # You can set it to 1 or 2 to different logging levels
> )
> 
> # Get your crew to work!
> result = crew.kickoff()
> 
> print("######################")
> print(result)
> ```
> 
> Tested on colab.

Try to understand what the topic is before you write a response.

**Comment by bitsnaps** [comment]
> Try to understand what the topic is before you write a response.

I apologize if my comment was off-topic or unhelpful for your specific issue, I thought that would be helpful for someone else. If you'd prefer, I'm ready to delete my comment if that makes you happy. Thank!
