### ISSUE TITLE
Error found in the 'README' example.

### ISSUE THREAD

**Issue by haderalva** [crewAIInc/crewAI#405]
I installed it using the following command:
```
pip install 'crewai[tools]'
```

However, when I attempted to run the example provided in the README, I encountered an error:

```
    from crewai_tools import SerperDevTool
ModuleNotFoundError: No module named 'crewai_tools'
````

**Comment by xitex** [comment]
from crewai_tools.tools import SerperDevTool
Try this man

**Comment by VideoFX** [comment]
I have the same issue. Windows 10. Python 3.8.

**Comment by lugq1990** [comment]
Also remember to create a python 3.10 over virtual env
