### ISSUE TITLE
CSVSearchTool seem like not functional

### ISSUE THREAD

**Issue by casxoon** [crewAIInc/crewAI#415]
I test by  upload csv file that has like 7 record and when i ask about data in csv file it alway random pick  3 record to answer even i ask to give all the record info to me

**Comment by casxoon** [comment]
[temp.csv](https://github.com/joaomdmoura/crewAI/files/14846311/temp.csv)

**Comment by Tolkoton** [comment]
same for me

**Comment by darshanjoshi9801** [comment]
@casxoon did you find any soltuion to this? like getting more than 3 records or as many records that needs to retrieved?
