### ISSUE TITLE
CSVSearchTool._run() missing 1 required positional argument: 'search_query'

### ISSUE THREAD

**Issue by mjhapp** [crewAIInc/crewAI#426]
I noticed in the output:
`Action: Search a CSV's content`
`Action Input: {"query": "Bonjour"}`

To troubleshoot, I changed CSVSearchTool._run
from
```
    def _run(
        self,
        search_query: str,                                   #here
        **kwargs: Any,
    ) -> Any:
        return super()._run(query=search_query)        #and here
```

to
```
    def _run(
        self,
        query: str,
        **kwargs: Any,
    ) -> Any:
        return super()._run(query=query)
```

Which fixed the problem.  

I don't, however, know whether that is the ideal solution or whether the Action Input should be rendered as 
`{"search_query": "xxx"}`

This is the first tool I've played with so not sure what the other ones are expecting.

**Comment by AlexeyYakovlev1** [comment]
same problem, I see several posts on other forums about this

**Comment by GregHilston** [comment]
@AlexeyYakovlev1 I'm unfamiliar with the forums, may you link me?
