### ISSUE TITLE
Yellow is a terrible color for visibility

### ISSUE THREAD

**Issue by 1of13** [crewAIInc/crewAI#427]
Let me begin by saying that I appreciate your hard work and dedication to this project. 

When kicking off a crew, the verbose output can sometimes be challenging to read. For example, the color yellow is tough to read. While I can manually go in and edit the code and manually setup crewAI, it would be nice if you would consider changing the text color yellow to, say, orange, which is easier to read. Thanks for considering this request. 

<img width="933" alt="SCR-20240405-jjuw" src="https://github.com/joaomdmoura/crewAI/assets/31781349/09473dfb-0549-42e5-801c-9e2ab2665432">

**Comment by joaomdmoura** [comment]
will do 😎👉👉
--
João Moura
@joaomdmoura <http://twitter.com/joaomdmoura>


Em sex., 5 de abr. de 2024 às 14:20, 1of13 ***@***.***>
escreveu:

**Comment by Freffles** [comment]
Is there a setting we can change to alter the default text colors? I typically use a dark theme and the bold purple is a hard read for an old bugger like me.

**Comment by theCyberTech** [comment]
There is no setting to change the colors, but you can money patch,

Closing as original issue fixed

**Comment by fdaugan** [comment]
I have created #5630 for this
