### ISSUE TITLE
Action: duckduckgo\_search

### ISSUE THREAD

**Issue by bschwab** [crewAIInc/crewAI#429]
After a thought, it started to use duck duck go for search, but it runs into this issue:

> Action: duckduckgo\\_search
> Action Input: {"query": "vector space definition"}

> Action 'duckduckgo\\_search' don't exist, these are the only available Actions: duckduckgo_search: A wrapper around DuckDuckGo Search. Useful for when you need to answer questions about current events. Input should be a search query.

Expected output: It shouldn't have a "\\" character and get confused

> $ pip show crewai
> Name: crewai
> Version: 0.27.2

**Comment by noggynoggy** [comment]
That's not a crew AI Issue. The LLM you are using is just "too stupid" to use tools correctly. I've maneuvered around this by using camelCase instead of under_scores. LLMs seem to have fewer problems with that.
