### ISSUE TITLE
Erro na instalação do CrewAI na plataforma Visual Studio Code

### ISSUE THREAD

**Issue by Victornic2013** [crewAIInc/crewAI#437]
![Captura de tela 2024-04-06 192115](https://github.com/joaomdmoura/crewAI/assets/166258961/5c2a27e8-89c7-4c45-b69b-b3fca92140f6)

Alguem pode me ajudar como resolver esse problema ? desde já agradeço!

**Comment by GoldBull3t** [comment]
Precisa de instalar o Microsoft Visual C++
