### ISSUE TITLE
too chatty to solve a simple problem

### ISSUE THREAD

**Issue by arjunkrishna** [crewAIInc/crewAI#440]
Hello,

   How is this thing better than just writing code to solve what you want to do. 

   I tried one of the trip planning sample and it seems too chatty and uses too many computer resources to complete the task. I did use locally hosted mistral on ollama. Maybe I am using it incorrectly.  

  will try stock analysis sample next.

Arjun

**Comment by arjunkrishna** [comment]
Thanks. Will try that out.

**Comment by raghav135** [comment]
Can you let us know how it goes with process.sequential with allow_delegation=False.
