### ISSUE TITLE
crewai changes `logging` settings

### ISSUE THREAD

**Issue by X3NOOO** [crewAIInc/crewAI#441]
after importing crewai changing the `logging` config becomes impossible, is this an intended behaviour?

example:
```python
import crewai
import logging

logger = logging.getLogger(__name__)


def main():
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s | %(name)s | %(levelname)s | %(message)s",
    )

    logger.debug("foobar")


if __name__ == "__main__":
    main()
```
expected output: `<date> | __main__ | DEBUG | foobar`
real output: nothing

even after manually changing the level of the logger used with the `.setLevel` method the output still doesn't match the expected formatting and looks like this: `<date> - <numbers> - <filename>-test:<file_line> - DEBUG: foobar`

**Comment by joaomdmoura** [comment]
cc @GabeKoga  I think this might be related to some of the changes you did last week? Could you do some checking on it?

**Comment by Kurdzik** [comment]
Hi, is there an update on this, for version 0.36.0 my logger is still being overwritten

**Comment by X3NOOO** [comment]
not stale/afaik still not fixed

**Comment by thoraxe** [comment]
logging still doesn't work
