### ISSUE TITLE
The issue with running tool

### ISSUE THREAD

**Issue by marfantyk** [crewAIInc/crewAI#453]
I created a custom tool that is supposed to extract information from a server through API call. This information is supposed to be used later, summarized in a different task and provided to a user. For some reason, when Crew decides to use this tool, it gets stuck in a loop of executing API calls until it reaches the limit of  tokens. Those calls return information in purple color that should be used further but it never does it and makes another API call with words like 

"> Entering new CrewAgentExecutor chain...
I need to fetch comprehensive information about the APOE gene from the database. To do this, I should use the "read information 
"APOE" gene as the input."

Here is the code of this tool:

```
@tool("read information about genes")
def gene_tool(input: str):
    """
    Read content about genes from API call

    Parameters:
    - input: the input that will be used for api calls, should be the name of the gene,a string in capital letter. For example "APOE"

    Returns:
    - results_from_api_calls: a json with information about the gene, can be structured as a table
    """
    response = requests.get(api_url+"gene_lookup/"+ input)
    if response.status_code != 200:
        return "Failed to retrieve gene information"
    return response.json()
```

**Comment by antonkulaga** [comment]
I also tried to make @marfantyk code work ( https://www.dfg.de/de/aktuelles/neuigkeiten-themen/info-wissenschaft/2024/ifw-24-32 ) and failed.  Curios why the agent has issues with pretty basic tasks
