### ISSUE TITLE
CAnnot install Agentops on version 0.28.7

### ISSUE THREAD

**Issue by theCyberTech** [crewAIInc/crewAI#456]
Unable to install agentops in a clean env when crewai and crewai-tools are installed due to a dependancy problem

![image](https://github.com/joaomdmoura/crewAI/assets/84775494/0fce5bc7-4398-4a19-a0a1-d192845abb18)

**Comment by areibman** [comment]
@theCyberTech -- Alex from AgentOps here. Taking a look at this now. 

Also, AgentOps is not officially merged into Crew yet, so keep in mind you may not get what you're after until it is.

**Comment by areibman** [comment]
@theCyberTech If you upgrade AgentOps to the latest version, this should be resolved. Thanks for pointing this out!
`pip install -U agentops`

https://github.com/AgentOps-AI/agentops/releases/tag/0.1.4
