### ISSUE TITLE
Add list of tools to Wiki / Docs / Readme

### ISSUE THREAD

**Issue by joaomdmoura** [crewAIInc/crewAI#46]
People keep asking about tools, I usually point them to langchain tools and toolkits but I think folks would benefit from having those links close to crewAI, we should have a dedicate list linking to some of the most common ones and also link to it form the README

**Comment by nitverse** [comment]
Can you assign it to me?

**Comment by iplayfast** [comment]
I think it would also be beneficial  to have a separate category of  tools that work with a local llm.
Also a category for tools that require keys. 

And the most beneifical documentation of all would be a snippet of example code using the tool.

**Comment by jbdatascience** [comment]
> I think it would also be beneficial to have a separate category of tools that work with a local llm. Also a category for tools that require keys.
> 
> And the most beneifical documentation of all would be a snippet of example code using the tool.

I complete agree with that !

**Comment by joaomdmoura** [comment]
Love this, I actually started to work on this, it will be a separate package called crewAI-tools that we will release soon

**Comment by theCyberTech** [comment]
Completed
