### ISSUE TITLE
Process.hierarchical forces openAI 

### ISSUE THREAD

**Issue by debankadas** [crewAIInc/crewAI#462]
This works with local Ollama

crew = Crew(
           agents=[research_agent,summarize_agent],
            tasks=[task,task1],
            process=Process.sequential,
            memory=False,
           max_rpm=2,
            share_crew=False,
            manager_llm=mistral,
            function_calling_llm=mistral,
           verbose=2
       )
       
 This doesn't
 
 crew = Crew(
    agents=[research_agent, summarize_agent],
    tasks=[task, task1],
    manager_llm=mistral,  # Mandatory for hierarchical process
    process=Process.hierarchical,  # Specifies the hierarchical management approach
    memory=True,
    max_rpm=2,
    function_calling_llm=mistral,
    verbose=2
)

The agents and task code remains same, so looks like Process.hierarchical is forcing openAI ?

**Comment by theCyberTech** [comment]
You havent specified the manager_llm attribute in your crew - https://docs.crewai.com/core-concepts/Processes/

**Comment by punitchauhan771** [comment]
```
crew = Crew(
agents=[research_agent, summarize_agent],
tasks=[task, task1],
manager_llm=mistral, # Mandatory for hierarchical process
process=Process.hierarchical, # Specifies the hierarchical management approach
memory=True,
max_rpm=2,
function_calling_llm=mistral,
verbose=2
)
```
mark memory - False, (when you use memory = True, it creates a rag and stores your data, for storing your data into a rag, it needs a embedding which by default is set to openai.

**Comment by joaomdmoura** [comment]
Exactly, but you can also set it to use other providers for memory too :):
https://docs.crewai.com/core-concepts/Memory/#using-google-ai-embeddings

--
João Moura
@joaomdmoura <http://twitter.com/joaomdmoura>


Em sex., 12 de abr. de 2024 às 01:56, punitchauhan771 <
***@***.***> escreveu:
