### ISSUE TITLE
Trivy Scan result show Risk high

### ISSUE THREAD

**Issue by Palakorn-Voramongkol** [crewAIInc/crewAI#467]
I have scan CrewAI repo for security scanning with Trivy by using the command:
"docker run -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest repo https://github.com/joaomdmoura/crewAI.git"
There are few Secerity = High.
If you can resolve this, it will make your component be more perfect.

![2024-04-13_15-23-14](https://github.com/joaomdmoura/crewAI/assets/102006914/99a9a947-63a9-4cbd-b0cc-5ff13dfe7e99)

**Comment by pbadeer** [comment]
@joaomdmoura Turning on Github Dependabot for the repo will automatically propose a PR for updating the poetry lockfile with a fix.
