### ISSUE TITLE
SUGGESTION: Making it easire to "try it" with Dockerfile / devcontainer / etc. 

### ISSUE THREAD

**Issue by bitshop** [crewAIInc/crewAI#473]
I, like many others, wanted to try out crewAI and generally the first thing I do is run sometihng in Docker or a devcontainer (which is Docker behind the scenes). This can be as simple as clicking the "Code" green button in GitHub and opening in CodeSpaces (online / on their servers). 

In looking at the repo and the README it appeared I didn't need to clone this repo, just set up the basic things you said - As such instead of a PR (which I'm perfectly willing to make) I just made a new repo with the example in the README - https://github.com/bitshop/crewai-devcontainer

Generally I'd do a PR instead of a distinct repo - Do you think there's some good way to merge this somewhere? Perhaps a second repo like crewAI-example or such? I'm obviously happy to keep the repo myself but this is a trivial amount of work and contributing it is fine.

**Comment by theCyberTech** [comment]
The way I use crewAI with dev containers is by having dev containers start with the requirements file loading in all the crewAI, no need for a docker file as using a Python base image build, this works perfectly as if I need anything extra I add it to the requirements.txt file, I will be migrating to poetry with the Python poetry base image

**Comment by bitshop** [comment]
Thank you and I agree there's no need for Dockerfile but I was thinking this can be a fork or copy/paste as a template for new devs / projects - Those often will want a Dockerfile to add apt installs to. I'll change to requirements.txt for the same reason, thanks for that tip.  

My assumption is more and more people will be developing in containers and remote, so trying to make something easier for those devs.

For simpler projects (like this demo) I do agree the format of post install commands and base python image works very well.
