### ISSUE TITLE
src/crewai/telemetry/telemetry.py tracing question

### ISSUE THREAD

**Issue by openjay** [crewAIInc/crewAI#476]
src/crewai/telemetry/telemetry.py

Hi,

Just asking about the telemetry, if I do not want to be traced and send any data out, what I can do?
can I just remove the tracing module?

For some projects I am fine, but for some workloads, I would say no for now. Can we?

Thanks for your answer. Appreciate

**Comment by Christian24** [comment]
There is already an open PR for this: https://github.com/joaomdmoura/crewAI/pull/402
