### ISSUE TITLE
output_pydantic inconsistencies

### ISSUE THREAD

**Issue by Christian24** [crewAIInc/crewAI#481]
Hello everyone,

the docs still mention that `output_pydantic` is only supported when using OpenAI. However, looking at the code it seems other LLMs are also supported. 

In addition Instructor seems to support a lot of other clients now: https://python.useinstructor.com/hub/mistral/#mistral-client

Now, because the docs were unclear I implemented this myself:

``` py
def get_visa(input: str) -> Visa:
    parser = PydanticOutputParser(pydantic_object=Visa)
    prompt = ChatPromptTemplate.from_messages([
    ("system", """You an expert on JSON. Use the input given to you and convert it to JSON like {format_instructions}
     """),
    ("user", "{input}")
])
    chain = prompt | json_model | parser
    result = chain.invoke({"input": input, 'format_instructions': parser.get_format_instructions()})
    return result
```

`Visa` is my Pydantic model.

First of all as a developer I wonder why crewAI does not implement it like this. I am sure there is a reason, but I would love if you guys would document some design decisions, because it helps me as a developer understand the tools I am using. 

Now thanks to some pointers I was able to get the task working as well:
```py
Task(
            description=f"""Map the information given by your colleagues into a JSON object.""",
            expected_output="""A JSON object with the following structure:

            {"visa_information": "A string containing visa information.",
            "visa_required": "True if a visa is needed, False if it is not needed",
             "safe_to_travel": "True if it is save to visit the destination, False if it is unsafe",
             "security_information": "A string containing security information."
             }
               
                 """,
            agent=agent,
            context=context,
            output_pydantic=Visa
        )
```

Now funny thing why does the crewAI version need an `expected_output` if Langchain does not? Well because it is required in the `Task`. :P 

If I pass an empty `expected_output`, it still works:
```py
Task(
            description=f"""Map the information given by your colleagues into a JSON object.""",
            expected_output="""""",
            agent=agent,
            context=context,
            output_pydantic=Visa
        )
```
There are multiple ways out of this dilemma:

1. making `expected_output` optional, that would be a breaking change and probably break things in other places
2. add a `BaseTask` class from which a `PydanticTask` and `Task` inherit. 
3. there are probably more possible solutions

I would love to help make this more developer friendly as I think validations are one of the most important things when using AI. I am happy to write a guide for the documentation, but currently I do not know how this is supposed to be used.

Best regards,
Christian

**Comment by nkeilar** [comment]
There is a stronger case for validation on other models that are not OpenAI, as they often would need more retries to get a valid output. This seems like an essential thing to be tackled to support local, or at least more local and use of smaller models for some tasks / agents.
