### ISSUE TITLE
Custom Model Support differs between agents and tools

### ISSUE THREAD

**Issue by deanchanter** [crewAIInc/crewAI#497]
Why do the agents use langchain-type models, and tools use embedchain for custom models? This is confusing and limits the tools' flexibility since the embedchain does not support the number of LLMs that the langchain does, including BYOM.

**Comment by theCyberTech** [comment]
Can you explain what you mean by langchain-type models?

**Comment by theCyberTech** [comment]
I see what you mean, Im not sure as to design decision but your are not limited to that you can import any langchain integration LLM, Embeddings, Tools, Vector storage etc as use them
