### ISSUE TITLE
CrewAI in Flowise and the JS/TS version

### ISSUE THREAD

**Issue by magedhelmy1** [crewAIInc/crewAI#517]
In this [link](https://github.com/FlowiseAI/Flowise/issues/1670#issuecomment-1930399694) the creators of Flowise are awaiting the completion of the JS/TS version. Recognizing the immense potential of having CrewAI in Flowise, I was wondering if there might be an estimated timeline for its completion?

**Comment by elix1er** [comment]
up

**Comment by thiagodebugs** [comment]
up

**Comment by joaomdmoura** [comment]
We are about to start working on this transition :)
