### ISSUE TITLE
Callbacks for Delegation

### ISSUE THREAD

**Issue by emorling** [crewAIInc/crewAI#520]
Are there any callbacks which return this information that I see logged to the terminal?

I believe this is by the CrewAgentExecutor in a Hierarchical process:

<img width="892" alt="image" src="https://github.com/joaomdmoura/crewAI/assets/988266/e5cd4c76-ec2c-4b6e-9aa8-319161457e0c">

**Comment by noggynoggy** [comment]
This is probably possible, but you'd have to use a custom manager as in #474 and then wrap the tools the Manager uses for delegation in code that acts a callback.
