### ISSUE TITLE
yaml config is not escaped properly for output requirements

### ISSUE THREAD

**Issue by antonkulaga** [crewAIInc/crewAI#528]
When I configure my output for agents and tasks I often use JSON and describe it using curly braces.
```
{
      'requirement_name': {
        'score': 'score value',
        'comment': 'additional comment if needed',
        'pros': 'what was good',
        'cons': 'what was bad'
      }
}
```
Unfortunately, your config loader uses the Python format function to load text and crashes. I have to use double brackets like {{ and }} in my yaml which is extremely annoying. I would like to be able to switch this formating behavior off for output requirements because it adds additional layer of complexity to my yaml prompts.

**Comment by joaomdmoura** [comment]
@GabeKoga if you don't mind taking a look at this.
Also notices that ({var}) doesn't work because of the parenthesis, so maybe we need to fix that too.
