### ISSUE TITLE
Add option to set llm attribute on a crew 

### ISSUE THREAD

**Issue by joaomdmoura** [crewAIInc/crewAI#53]
For folks not trying to have each agent use a different LLM this will allow them to set it once on the crew and forget about it

**Comment by siddartha-10** [comment]
Hey I can work on this.

**Comment by joaomdmoura** [comment]
Let's go @siddartha-10 if you find the time feel free to open a PR otherwise I might do it soon ;)

**Comment by siddartha-10** [comment]
Working on it.

**Comment by siddartha-10** [comment]
Hey @joaomdmoura i was working on it,
from my understanding it is not just adding the llm as an attribute in the crew.py right we should also make some changes in the agents.py file as well right?
