### ISSUE TITLE
undocumented sqlite3 dependency

### ISSUE THREAD

**Issue by nick-youngblut** [crewAIInc/crewAI#534]
Dockerfile:

```dockerfile
# Use an official Python runtime as a base image
FROM python:3.11-slim-buster

# Set the working directory in the container
WORKDIR /crewai

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      gcc curl gnupg2 less vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements.txt file into the container
COPY requirements.txt ./

# Copy the package files into the container
#COPY ./crewai ./

# Install any needed Python packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
```

requirements.txt file:

```
openai==1.23.6
crewai==0.28.8
crewai-tools==0.1.7
```

Import:

```bash
python -c "import crewai"
```

Error:

```console
ERROR: Could not find a version that satisfies the requirement pysqlite3-binary (from versions: none)
ERROR: No matching distribution found for pysqlite3-binary
2024-04-29 13:05:52,755 [embedchain] [ERROR] Failed to swap std-lib sqlite3 with pysqlite3 for ChromaDb compatibility. Error: Command '['/usr/local/bin/python', '-m', 'pip', 'install', 'pysqlite3-binary', '--quiet', '--disable-pip-version-check']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/crewai/__init__.py", line 1, in <module>
    from crewai.agent import Agent
  File "/usr/local/lib/python3.11/site-packages/crewai/agent.py", line 23, in <module>
    from crewai.agents import CacheHandler, CrewAgentExecutor, CrewAgentParser, ToolsHandler
  File "/usr/local/lib/python3.11/site-packages/crewai/agents/__init__.py", line 2, in <module>
    from .executor import CrewAgentExecutor
  File "/usr/local/lib/python3.11/site-packages/crewai/agents/executor.py", line 16, in <module>
    from crewai.memory.entity.entity_memory_item import EntityMemoryItem
  File "/usr/local/lib/python3.11/site-packages/crewai/memory/__init__.py", line 1, in <module>
    from .entity.entity_memory import EntityMemory
  File "/usr/local/lib/python3.11/site-packages/crewai/memory/entity/entity_memory.py", line 3, in <module>
    from crewai.memory.storage.rag_storage import RAGStorage
  File "/usr/local/lib/python3.11/site-packages/crewai/memory/storage/rag_storage.py", line 7, in <module>
    from embedchain import App
  File "/usr/local/lib/python3.11/site-packages/embedchain/__init__.py", line 5, in <module>
    from embedchain.app import App  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/embedchain/app.py", line 33, in <module>
    from embedchain.vectordb.chroma import ChromaDB
  File "/usr/local/lib/python3.11/site-packages/embedchain/vectordb/chroma.py", line 4, in <module>
    from chromadb import Collection, QueryResult
  File "/usr/local/lib/python3.11/site-packages/chromadb/__init__.py", line 79, in <module>
    raise RuntimeError(
RuntimeError: Your system has an unsupported version of sqlite3. Chroma                     requires sqlite3 >= 3.35.0.
Please visit                     https://docs.trychroma.com/troubleshooting#sqlite to learn how                     to upgrade.
```

The [installation docs](https://docs.crewai.com/how-to/Creating-a-Crew-and-kick-it-off/#step-0-installation) do not state that sqlite3 must be installed, in addition to running `pip install crewai`.

**Comment by nick-youngblut** [comment]
At least with my Dockerfile setup, `apt-get update && apt-get install sqlite3` will only install sqlite3 version `3.27.2 2019-02-25`, but Chroma requires `sqlite3 >= 3.35.0`. So the install of the required version of sqlite3 appears to be non-trivial for at least some OS environments, and docs on installing this dependency would likely be quite helpful.

**Comment by nick-youngblut** [comment]
The last option in the [Chroma docs on this issue](https://docs.trychroma.com/troubleshooting#sqlite):

> If you are using a Debian based Docker container, older Debian versions do not have an up to date SQLite, please use `bookworm` or higher.


...seemed rather cryptic, at least to me, but after looking at the [Chroma Dockerfile](https://github.com/chroma-core/chroma/blob/main/Dockerfile), I see that `python:3.11-slim-bookworm` is used instead of `python:3.11-slim-buster`.

However, when I switch from `python:3.11-slim-buster` to `python:3.11-slim-bookworm`, my docker build fails with the following error:

```
30.53 ERROR: Could not find a version that satisfies the requirement regex<2024.0.0,>=2023.12.25 (from crewai) (from versions: none)
30.53 ERROR: No matching distribution found for regex<2024.0.0,>=2023.12.25
```

**Comment by robink** [comment]
Same issue here, tried to build manually [pysqlite3](https://github.com/coleifer/pysqlite3#building-a-statically-linked-library ) but it didn't work either

**Comment by alexfazio** [comment]
Hello. I currently don't have a precise solution to your problem. 

However, if you're aiming to utilize a PostgreSQL database, I recommend checking out [this template notebook](https://github.com/alexfazio/crewAI-quickstart/blob/main/crewai_sequential_PGSearchTool_quickstart.ipynb). 

I hope it can provide you with some useful pointers.

**Comment by gromag** [comment]
Its's 16th of July and this still seems a problem. I just started with crew following the getting started and this still gives RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0. 😞 

Is there a solution, the Issue is still open.

**Comment by dregules** [comment]
This continues to be an issue for me, what's the solution? currently have in my requirements.txt

crewai
crewai[tools]
chromadb==0.4.0
pysqlite3-binary>=0.5.0

**Comment by theCyberTech** [comment]
Investigating

**Comment by theCyberTech** [comment]
> This continues to be an issue for me, what's the solution? currently have in my requirements.txt
> 
> crewai crewai[tools] chromadb==0.4.0 pysqlite3-binary>=0.5.0

Hi @dregules,

I am struggling to reproduce this issue, is it possible you could send me your Dockerfile and reqs file?

**Comment by dregules** [comment]
@theCyberTech thanks for looking into it. I spent a good amount of time and the end result is that it was failing when i deployed only to streamlit cloud, which seems to have a known lower version of sqlite3 than what's required for chromadb dependency. I deplpyed to heroku and railway, and the issue resolved. 
For your reference, here's one of the main threads discussing this: https://discuss.streamlit.io/t/issues-with-chroma-and-sqlite/47950/5

**Comment by tsukhu** [comment]
we still face this issue as well. reverting to 0.65.2 for now, which does not have the chroma dependency

**Comment by Madhuvod** [comment]
omg someone from crewai pls help with this! it still give me the error while deploying my crewai agent project in streamlit cloud,

>  Please visit                     https://docs.trychroma.com/troubleshooting#sqlite to learn how                     to upgrade.
> 2024-11-08 11:33:02.813 503 GET /script-health-check (127.0.0.1) 60085.27ms
> Traceback (most recent call last):
>   File "/mount/src/ai-business-insider/news_summarizer_analyzer/src/news_summarizer_analyzer/main.py", line 6, in <module>
>     from crew import NewsSummarizerAnalyzerCrew
>   File "/mount/src/ai-business-insider/news_summarizer_analyzer/src/news_summarizer_analyzer/crew.py", line 1, in <module>
>     from crewai import Agent, Crew, Process, Task
>   File "/home/adminuser/venv/lib/python3.12/site-packages/crewai/__init__.py", line 2, in <module>
>     from crewai.agent import Agent
>   File "/home/adminuser/venv/lib/python3.12/site-packages/crewai/agent.py", line 9, in <module>
>     from crewai.agents.crew_agent_executor import CrewAgentExecutor
>   File "/home/adminuser/venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 6, in <module>
>     from crewai.agents.agent_builder.base_agent_executor_mixin import CrewAgentExecutorMixin
>   File "/home/adminuser/venv/lib/python3.12/site-packages/crewai/agents/agent_builder/base_agent_executor_mixin.py", line 4, in <module>
>     from crewai.memory.entity.entity_memory_item import EntityMemoryItem
>   File "/home/adminuser/venv/lib/python3.12/site-packages/crewai/memory/__init__.py", line 1, in <module>
>     from .entity.entity_memory import EntityMemory
>   File "/home/adminuser/venv/lib/python3.12/site-packages/crewai/memory/entity/entity_memory.py", line 2, in <module>
>     from crewai.memory.memory import Memory
>   File "/home/adminuser/venv/lib/python3.12/site-packages/crewai/memory/memory.py", line 3, in <module>
>     from crewai.memory.storage.rag_storage import RAGStorage
>   File "/home/adminuser/venv/lib/python3.12/site-packages/crewai/memory/storage/rag_storage.py", line 10, in <module>
>     from chromadb.api import ClientAPI
>   File "/home/adminuser/venv/lib/python3.12/site-packages/chromadb/__init__.py", line 86, in <module>
>     raise RuntimeError(
> RuntimeError: Your system has an unsupported version of sqlite3. Chroma                     requires sqlite3 >= 3.35.0.
> Please visit                     https://docs.trychroma.com/troubleshooting#sqlite to learn how                     to upgrade.

I’m currently working on deploying a project that uses crewai (version 0.74.2 as recommended) and crewai-tools (0.13.2). However, I'm facing a persistent issue with chromadb requiring a specific version of sqlite3 during deployment on Streamlit Cloud.

Error Summary

When deploying, I encounter the following error:

RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.
Please visit https://docs.trychroma.com/troubleshooting#sqlite to learn how to upgrade.
Streamlit Cloud doesn’t seem to allow the necessary updates to sqlite3, and although my local environment has sqlite3 version 3.43.2 (which works fine), the deployment environment on Streamlit Cloud doesn’t meet the requirements of chromadb.

Steps I’ve Taken to Troubleshoot

Pinned Versions: I tried using crewai==0.74.2 and crewai-tools==0.13.2, as suggested by other users, to avoid chromadb dependency issues, but it didn’t resolve the problem.
Checked SQLite Version: I verified that my local system has sqlite3 version 3.43.2, which satisfies chromadb’s requirements. However, this isn’t mirrored in the Streamlit Cloud environment.

**Comment by Edgar454** [comment]
Has this been solved?
I ran into the same problem

**Comment by 4F2E4A2E** [comment]
related https://github.com/crewAIInc/crewAI/issues/1841

**Comment by tibbon** [comment]
does this problem still exist? It seems to keep being closed automatically?
