### ISSUE TITLE
Reflection for agent

### ISSUE THREAD

**Issue by afeezaziz** [crewAIInc/crewAI#559]
How can I be using crewai to make the agents to reflect/learn from its own output? Do I have to use crewai in conjunction with langgraph? 

Example case is a code monkey agent write a Python code, then the tester would test and check the errors. It will inform the code monkey agent of the error and it would rewrite it. Another example perhaps a writer agent that rewrite based on the feedback by editor agent.

**Comment by alexfazio** [comment]
> Do I have to use crewai in conjunction with langgraph?

That's correct. It may not be the only solution, but it is the most effective and well-tested one.

https://www.youtube.com/watch?v=5eYg1OcHm5k&t=132s
