### ISSUE TITLE
duckduckgo_search

### ISSUE THREAD

**Issue by xjq284** [crewAIInc/crewAI#569]
from langchain_community.tools import DuckDuckGoSearchRun
ddgs_search_tool = DuckDuckGoSearchRun()

--------
Action: duckduckgo_search
Action Input: {"q": "financial management and control within China's shipping industry"} 

I encountered an error while trying to use the tool. This was the error: DuckDuckGoSearchRun._run() got an unexpected keyword argument 'q'.
 Tool duckduckgo_search accepts these inputs: A wrapper around DuckDuckGo Search. Useful for when you need to answer questions about current events. Input should be a search query.

**Comment by noggynoggy** [comment]
The llm is misusung the tool. It shout be "query" not "q". The model doestnt read the error and fix itself zhe solution is a "smarter" model unfortunately

**Comment by noggynoggy** [comment]
> Is this due to hallucination? @noggynoggy 

Hallucination is a broad term and by **my** definition this would not be that. I would just call this the  model guessing what to do (as it always does) and being wrong. Hallucination is making up facts and being confident about those.

**Comment by noggynoggy** [comment]
> hmm.. how do you even term it? @noggynoggy  jus asking out of kuriosity

This is not a chatroom. Sorry.
