### ISSUE TITLE
Any way to set crew Input Arguments at runtime?

### ISSUE THREAD

**Issue by vmsaif** [crewAIInc/crewAI#575]
I am using the .yaml files for agents and tasks. So to send arguments to those agents or tasks, we are supposed to call kickoff() like this at main:

```
myArgs = {
      'user_info_orgainzed_file_path': file_path
}
crew().kickoff(inputs=myArgs)
```

Any way to set the variables at runtime and not declaring at the main? What I mean to say, what are the other ways to set the myArgs?

**Comment by theCyberTech** [comment]
You dont need to use the inputs method, you can jsut define it all in your crew for example
