### ISSUE TITLE
Integrating OpenAI Vision Models with Crew Agents

### ISSUE THREAD

**Issue by anmol1810rs** [crewAIInc/crewAI#580]
Hi, 
Is it possible to insert images to crew agents using Vision models such as 'gpt-4-vision-preview' or 'gpt-4-turbo'. Any help would be appreciated.

**Comment by slavakurilyak** [comment]
Yes, you can also use Google's `Gemini 1.5 Pro` (state-of-the-art model) and `Gemini 1.0 Pro Vision` (previous model) to accomplish this

**Comment by tusharmctrl** [comment]
Hey guys! How do I attach that image to any task. Can you guys please help me out on this one? Much appreciated, thanks.
