### ISSUE TITLE
RAG capability with Opensource Models

### ISSUE THREAD

**Issue by varskann** [crewAIInc/crewAI#593]
More like a KT/Question.

I am trying to have RAG support for Open LLM (mamba), But unable to get it to work.
I am following this video, but Code is not working properly.

Any relevant resources or example codes for the same?

**Comment by mustangs0786** [comment]
I also need help how to use csv rag with local llama, it is not working..

**Comment by slavakurilyak** [comment]
What errors are you seeing? What's your stack trace?

**Comment by varskann** [comment]
Hey @slavakurilyak
For me, I am not able to make it run. Most likely some issue with the way I am adding the workflow. Haven't seen any example, so just implementing my thought process. Will share code in sometime(Might be entirely garbage)
