### ISSUE TITLE
Cannot install crewai[tools]

### ISSUE THREAD

**Issue by Tibiritabara** [crewAIInc/crewAI#595]
CrewAI has a dependency on top of embedchain. Latest embedchain (0.1.103) requires ChromaDB with version >= 0.5.0 while crewai-tools depends on versions <= 0.5.0. This dependency conflict does not allow me to install crewai-tools.

**Comment by slavakurilyak** [comment]
Use `poetry` to resolve the deps

**Comment by Tibiritabara** [comment]
I did this with Poetry. This is the error log:

```
Because no versions of crewai-tools match >0.2.5,<0.3.0
 and crewai-tools (0.2.5) depends on chromadb (>=0.4.22,<0.5.0), crewai-tools (>=0.2.5,<0.3.0) requires chromadb (>=0.4.22,<0.5.0).
And because embedchain (0.1.103) depends on chromadb (>=0.5.0,<0.6.0)
 and no versions of embedchain match >0.1.103,<0.2.0, crewai-tools (>=0.2.5,<0.3.0) is incompatible with embedchain (>=0.1.103,<0.2.0).
So, because temporal-python-worker depends on both embedchain (^0.1.103) and crewai-tools (^0.2.5), version solving failed.
```

As seen, it crashes with the chromaDB version used in `embedchain` lib

**Comment by stivaldj** [comment]
> I did this with Poetry. This is the error log:
> 
> ```
> Because no versions of crewai-tools match >0.2.5,<0.3.0
>  and crewai-tools (0.2.5) depends on chromadb (>=0.4.22,<0.5.0), crewai-tools (>=0.2.5,<0.3.0) requires chromadb (>=0.4.22,<0.5.0).
> And because embedchain (0.1.103) depends on chromadb (>=0.5.0,<0.6.0)
>  and no versions of embedchain match >0.1.103,<0.2.0, crewai-tools (>=0.2.5,<0.3.0) is incompatible with embedchain (>=0.1.103,<0.2.0).
> So, because temporal-python-worker depends on both embedchain (^0.1.103) and crewai-tools (^0.2.5), version solving failed.
> ```
> 
> As seen, it crashes with the chromaDB version used in `embedchain` lib

same here

**Comment by MarcoLooy** [comment]
Is there a solution?

**Comment by uditapatelgithub** [comment]
I just doewngraded my python to 3.11.9 and then it downloaded all fine. The latest versions of crewai still have this issue especially if you are on newer than 3.11 python versions

**Comment by nigel-daniels** [comment]
Is there a fix for this? I'm attempting to build a docker container to run a crew in and I hit this defect :(
