### ISSUE TITLE
while using async_execution=True in task

### ISSUE THREAD

**Issue by aman-vink** [crewAIInc/crewAI#600]
.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

**Comment by joaomdmoura** [comment]
Hey @aman-vink can you share some of the code so we can try to replicate locally?
