### ISSUE TITLE
Works fine with OpenAI, but local Ollama and LM-Studio fail with co-worker errors

### ISSUE THREAD

**Issue by tholonia** [crewAIInc/crewAI#602]
When running local, i can't get past coworker errors.   When I run the exact same workflow on OpenAI (using the last Exa example, below), it works fine.

On local Ollama or LM-Studio, it seems to be sensitive to the search tool.  

With `search_tool = DuckDuckGoSearchRun()` I get errors like this:

```
Action 'Delegate work to Internet Research' don't exist, these are the only available Actions:
```

With ` search_tool = SerperDevTool()`
```
Action 'None (I will think of potential improvements without using any tools)' don't exist
```
With `search_tool = ExaSearchTool.search`

```
Action Input: "epigenetics site:.edu OR site:.gov" I encountered an error while trying to use the too
```
With `search_tool = ExaSearchTool.search` AND `find_similar_tool = ExaSearchTool.find_similar` AND 
`search_and_contents_tool = ExaSearchTool.search_and_contents`

```
Error executing tool. Co-worker mentioned not found, it must to be one of the following options:
- internet research

```
'internet research' definitely exists...

CrewAI does not seem to play nice with anything local, and I have tried dozens of different configs :/

Presumably, the tools are working the same, so perhaps the OpenAI API is not as compatible as claimed for Ollama and LMS? Or, it is something related to CrewAI?

The very simple  code I am using to test is at https://github.com/tholonia/crewai-blogger/blob/main/blogger_v0.py

The log outputs are 
https://github.com/tholonia/crewai-blogger/blob/main/output_ddgs.log
https://github.com/tholonia/crewai-blogger/blob/main/output_exa.log
https://github.com/tholonia/crewai-blogger/blob/main/output_openai.md
https://github.com/tholonia/crewai-blogger/blob/main/output_serper.log

**Comment by italovieira** [comment]
I can confirm this. Running with llama3 locally gives me the same error "Co-worker mentioned not found...".

**Comment by italovieira** [comment]
I figure it out it's a regression.
I did a bisect and the bad commit is 0b781065d277564077fdaf630d46995c210cc9d1. Before that, it works without error.

**Comment by scruffynerf** [comment]
@italovieira is correct...  reverting the one line changed DOES help.  It's not perfect, but it helps greatly.
