### ISSUE TITLE
TikToken has no encoding value for "gpt-4o"

### ISSUE THREAD

**Issue by jhines2k7** [crewAIInc/crewAI#612]
https://github.com/joaomdmoura/crewAI/blob/615ac7f297070950e140f0ac529e01f96fc02c64/src/crewai/utilities/token_counter_callback.py#L46

I am using the ChatOpenAI model from LangChain as my manager llm. ChatOpenAI has a property called `tiktoken_model_name`, maybe we can use that value.

**Comment by j-zhrv** [comment]
up! actual problem

**Comment by TiMMaTTiee** [comment]
fixed this in my code using:
`tiktoken.get_encoding('cl100k_base')`
