### ISSUE TITLE
How to export the results of working agent, starting task, thoughts and tool calls to the front end？

### ISSUE THREAD

**Issue by 421333** [crewAIInc/crewAI#616]
I think websocket is a good option, but I can't find exactly where the thoughts and tool calls output is located.

**Comment by noggynoggy** [comment]
If you want everything, it is probably best right now to just redirect terminal output. If you just want to give the users feedback un whats happening, look into callbacks:

https://docs.crewai.com/core-concepts/Tasks/#callback-mechanism

**Comment by noggynoggy** [comment]
> > If you want everything, it is probably best right now to just redirect terminal output. If you just want to give the users feedback un whats happening, look into callbacks:
> > 
> > https://docs.crewai.com/core-concepts/Tasks/#callback-mechanism
> 
> Thanks @noggynoggy  - is there a way to access the agent name in the call back . We get the summary, description and exported_output, but is there a way to pass the agent or let the user know which agent produced that output ?

I'm afraid I don't know if there is a way to access like a `self.role` in the callback function from the to of my head (I'm on holiday). I believe the whole callback code is from before `Process.hierarchical` was a thing (in seq. you assign agents) so there is a chance that this was not thought to be necessary at the time.
