### ISSUE TITLE
Coworkers not specified with last commits

### ISSUE THREAD

**Issue by ruypex** [crewAIInc/crewAI#617]
---

### Issue Summary

Yesterday's commits ([7fd8850](https://github.com/joaomdmoura/crewAI/commit/7fd8850ddb175eee506a8008749f6e023914711d)) changed the declaration of `delegate` or `ask_coworker` functions, leading to prompts like this:

```
Ask question to co-worker: Ask question to co-worker(question: str, context: str, coworker: Optional[str] = None, **kwargs) - Ask a specific question to one of the following co-workers: [xxx,yyy,zzz]
```

I believe that due to `coworker: Optional[str] = None`, the response of LLM now lacks the "coworker" parameter.

### Steps to Reproduce

1. Action: Ask question to co-worker
2. Action Input:
    ```json
    {
        "question": "Can you provide me with the DNS hosts that the domain 'xxx.com' is delegated to?",
        "context": "The client is inquiring about the DNS hosts that the domain 'xxx.com' is delegated to. They are requesting this information."
    }
    ```

### Expected Result

The "coworker" parameter should be included in the Action Input.

### Actual Result

The "coworker" parameter is missing, which ends with an error:

```
Error executing tool. Co-worker mentioned not found, it must be one of the following options: [xxx,yyy,zzz]
```

---

**Comment by drcyberfolks** [comment]
I've noticed the same problem with 0.30.
