### ISSUE TITLE
Error "Co-worker mentioned not found..." when using with local llama3

### ISSUE THREAD

**Issue by italovieira** [crewAIInc/crewAI#620]
With the example below I get the following error:
```
Error executing tool. Co-worker mentioned not found, it must to be one of the following options:
- pilot
```

```python
from crewai import Agent, Task, Crew

from langchain_community.llms import Ollama

import os

os.environ["OPENAI_API_KEY"] = "NA"


llm = Ollama(model="llama3")


# Agents
luke = Agent(
    role="pilot",
    goal="Destroy the Death Star",
    backstory="The young destined-to-be-Jedi pilot, summoned to attack the Death Star.",
    llm=llm,
)

leia = Agent(
    role="strategist",
    goal="Coordinate the attack on the Death Star",
    backstory="The Rebel leader, essential for strategy and communication.",
    llm=llm,
)

# Tasks
coordinate_attack = Task(
    description="""Leia must coordinate the mission,
    maintaining communication and providing strategic support.
    Leia must ensure that everything is in order, providing a safe path for Luke""",
    expected_output="""Successfully coordinated attack, Death Star destroyed. All units informed and aligned.""",
    agent=leia,
    allow_delegation=True,
)


destroy_death_star = Task(
    description="""Luke must pilot his X-Wing and shoot at the Death Star's weak point to destroy it.""",
    expected_output="""Death Star destroyed, mission successful.""",
    agent=luke,
)


# Crews
rebel_alliance = Crew(
    agents=[leia, luke],
    tasks=[coordinate_attack, destroy_death_star],
    verbose=2,
)


rebel_alliance.kickoff()
```

**Comment by noggynoggy** [comment]
There are multiple issues with your code.
1. manager llm only works with proccess.hierarchical
2. it is generally recommended to use English for promoting and then just instruct to "translate" the response
3. When using Ollama use the ollama model class not OpenAI `from langchain_community.llms import Ollama
`

If i havn't missed anything, the coworker not being found is either because points 1-3 or because llama3 is "too dumb"

**Comment by noggynoggy** [comment]
Actually this might be related to #602

**Comment by italovieira** [comment]
> There are multiple issues with your code.
> 
>     1. manager llm only works with proccess.hierarchical
> 
>     2. it is generally recommended to use English for promoting and then just instruct to "translate" the response
> 
>     3. When using Ollama use the ollama model class not OpenAI `from langchain_community.llms import Ollama `

I've updated the code in the description with what you indicated.

For the point 3, I used `ChatOpenAI` just like the example in the doc https://docs.crewai.com/how-to/LLM-Connections/#ollama-integration-ex-for-using-llama-2-locally, though.

Either way, the error still occurs.

**Comment by italovieira** [comment]
This might be a problem in how the ollama or langchain outputs the steps for the agents.

But I did a bisect and found out crewAI was able to cope with that before https://github.com/joaomdmoura/crewAI/commit/0b781065d277564077fdaf630d46995c210cc9d1.
It was only after this commit this error started.

**Comment by Yazington** [comment]
Hey @italovieira have you been able to fix it? Getting same issue :(

**Comment by jp-gorman** [comment]
I am also getting the same issue when using with LLAMA3 when using hierarchical process and when I use mistral I get another "Action 'Delegate work to <agent name>' don't exist, these are the only available Actions:
 Delegate work to co-worker"

....It appears it tries to run a specific action that does not exist in both cases. Perhaps we should have much more documentation on the way the calling is achieved. It looks non deterministicm, in that the llm tried multiple different things (tries to call a tool...then tries to call an agent (unsuccessfully based on bad parameters, then tries to learn the correct calling convention and tries again..... this loops for a seemingly non deterministic fashion...

**Comment by italovieira** [comment]
> Hey @italovieira have you been able to fix it? Getting same issue :(

I've opened a MR to fix this issue, but it's not merged yet.

**Comment by madmag77** [comment]
Without logs it's hard to figure out the reason. I've had the same problem when LLM (Mistral 0.3 in my case) return action input key as `co-worker` instead of required `coworker` and this caused the same misleading error about absent agent. I fix it in this [PR](https://github.com/joaomdmoura/crewAI/pull/712). Already tested in my fork - it works fine. Maybe you can try this fix and see the result....

**Comment by psyq0** [comment]
Sorry to ask, maybe I missed something. Did you solved this issue with an workaround? If yes can please let me know how ?
Thanks in advance!

**Comment by madmag77** [comment]
If you asking about co-worker problem then yes, I made a [fork](https://github.com/madmag77/crewAI) and raised a PR to the this repo but it's not merged yet. 
I managed to make example with tools and delegation work on open source LLMs - this is the [example](https://github.com/madmag77/crewai-article-example). It works with LM Studio + Mistral 0.3, Phi3 medium and Llama 3 7B, also with Ollama + Llama 3 7B. 

Hope it helps.

**Comment by Sisif-eu** [comment]
> Sorry to ask, maybe I missed something. Did you solved this issue with an workaround? If yes can please let me know how ? Thanks in advance!

For me the fix from @madmag77 didn't work.
It seems that for me the reason it is not able to match the co-worker role is that i got an extra " in the role name.

Comparing available_agents to agent in [agent_tools.py](https://github.com/joaomdmoura/crewAI/blob/ea893432e89095b50b3b49c622b32e4772c90df4/src/crewai/tools/agent_tools.py#L64) :

```
"senior research analyst
['senior research analyst', 'tech content strategist', 'french translator']
```
So as a dirty fix i replaced [this line](https://github.com/joaomdmoura/crewAI/blob/ea893432e89095b50b3b49c622b32e4772c90df4/src/crewai/tools/agent_tools.py#L64) with the following one :

`if available_agent.role.casefold().strip() == agent.casefold().strip().replace('"', '')`

And now it works with llama3:8b without issue. 

A bit dirty but i hope it helps waiting for a fix.


For reference this is how i initialize the agent : 

```
def initialize_agent(agent):
    initialized_agent = crewai.Agent(
        role=agent.role,
        goal=agent.goal,
        backstory=agent.backstory,
        verbose=agent.verbose,
        allow_delegation=agent.allow_delegation,
        llm = ChatOllama(
                    model = 'llama3:8b",
                    base_url = "http://localhost:11434"
         )

    )
    return initialized_agent
```
