### ISSUE TITLE
tools in crew ai

### ISSUE THREAD

**Issue by SumaiyaSultan2002** [crewAIInc/crewAI#629]
do tools in crew ai require open ai api key. currently i want to use groq with llama 3 model but i keep getting in error with i try to run CSVSearchTool() in the agents `
I encountered an error while trying to use the tool. This was the error: Error code: 401 - {'error': {'message': 'Incorrect API key provided: NA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}.
 Tool Search a CSV's content accepts these inputs: Search a CSV's content(search_query: 'string') - A tool that can be used to semantic search a query the Sample_helpdesk_tickets.csv CSV's content.
`

i dont want to use openai key for the tools. are there any alternatives?

**Comment by SumaiyaSultan2002** [comment]
`tool = CSVSearchTool(
    config=dict(
        llm=dict(
            provider="groq", # or google, openai, anthropic, llama2, ...
            config=dict(
                model="llama3",
                # temperature=0.5,
                # top_p=1,
                # stream=true,
            ),
        ),
        embedder=dict(
            provider="google", # or openai, ollama, ...
            config=dict(
                model="models/embedding-001",
                task_type="retrieval_document",
                # title="Embeddings",
            ),
        ),
    )
)` i also configured CSVsearchtool like this. but not sure what to so next. Would be great if someone could help me out of this.

**Comment by Timilla** [comment]
Hello @SumaiyaSultan2002 ,
I'm encountering the same issue as you when using the Groq API. Unfortunately, I believe the only way to utilize open-source LLMs while working with CrewAI is to work locally using Ollama.

**Comment by TaoAthe** [comment]
Can someone explain this in more detail?  What is the workaround, if any?

**Comment by gadgethome** [comment]
Found this on crewai discord that may help

tool = JSONSearchTool(
    json_path=file_path,
    config={
        "llm": {
            "provider": "google",
            "config": {
                "model": "gemini-pro",
                "temperature": 0.7,
            },
        },
        "embedder": {
            "provider": "google",
            "config": {
                "model": "text-embedding-004",
                "task_type": "retrieval_document",
            },
        },
    }
)
