### ISSUE TITLE
Add AWS as an Embedder Provider (required for Memory configuration)

### ISSUE THREAD

**Issue by dgallitelli** [crewAIInc/crewAI#637]
In order to configure a Crew with `memory=True` without a OpenAI API Key, one needs to configure an Embedder provider. Currently, AWS (Amazon Bedrock and Amazon SageMaker) are not supported providers. 

## Ask

- Include AWS in the providers list (`'openai', 'gpt4all', 'huggingface', 'vertexai', 'azure_openai', 'google', 'mistralai', 'nvidia'`).
- Support Amazon Bedrock Embedding models
- Support Amazon SageMaker Real-time Endpoints

## Things to note

Provider `aws_bedrock` is already supported in llm configuration, e.g.:

```python
semantic_search_resume = MDXSearchTool(
    mdx='./fake_resume.md',
    config=dict(
        llm=dict(
            provider="aws_bedrock", # <=== WORKS!
            config=dict(
                model="anthropic.claude-3-haiku-20240307-v1:0",
                # Optional parameters can be included here.
                # temperature=0.5,
                # top_p=1,
                # stream=true,
            ),
        ),
        embedder=dict(
            provider="aws_bedrock", <=== DOES NOT WORK!
            config=dict(
                model="cohere.embed-english-v3",
                task_type="retrieval_document",
                # Optional title for the embeddings can be added here.
                # title="Embeddings",
            ),
        ),
    )
)
```

**Comment by KE7** [comment]
I'll add one more option that's missing, Oracle Cloud

**Comment by chappers00** [comment]
Watching - would very much appreciate this feature

**Comment by dgallitelli** [comment]
Still relevant

**Comment by dgallitelli** [comment]
I can confirm this has worked for me, or at least it hasn't failed. `deployment_name` parameter is unnecessary I think - please let me know if that's not the case. This can be closed for now.

```python
crew = Crew(
  agents=agents_list, tasks=tasks_list,
  verbose=True, memory=True,
  embedder={
    "provider": "aws_bedrock",
    "config":{
      "model": "amazon.titan-embed-text-v2:0",
      "vector_dimension": 1024
    }
  }
)
```
