### ISSUE TITLE
How can the temperature of all agents be controlled?

### ISSUE THREAD

**Issue by Chriszhangmw** [crewAIInc/crewAI#643]
Hi, Thanks for your amazing work for Crewai.

My experiment involves 4 agents sharing the same LLM object with a temperature of 0.0. Despite identical inputs, the output varies each time, contrary to the expected consistency.

Could you share what parameters can control this? Thanks.

**Comment by robertobalestri** [comment]
Temperature 0 doesn't mean same results. Obviously there is an high probability that results are not so random liek with higher temperature, but LLMs are not deterministic, even with temperature 0.
