### ISSUE TITLE
Suppress `---` separator in `crew.kickoff` output

### ISSUE THREAD

**Issue by heaversm** [crewAIInc/crewAI#653]
In the output from a crew result (`result = crew.kickoff()`), the leading `---` separator prevents markdown files from being rendered properly. Is there a way to suppress these separators in the options? (I'm using the getting started code sample and attempting to write to an 'md' file:

```python
filename = "output.md"
with open(filename, "w") as file:
    file.write(result)
![Screenshot 2024-05-20 at 2 38 54 PM](https://github.com/joaomdmoura/crewAI/assets/520541/2127245d-04ac-476f-86f5-ce4ab3ca5c3f)

```

**Comment by noggynoggy** [comment]
then just remove them 

```python
for line in your_out.split("\n"):
    if line == "---": line = "" 
```
