### ISSUE TITLE
Why did the author make this error when I pip install 'crewai [tools]'

### ISSUE THREAD

**Issue by yxl23** [crewAIInc/crewAI#670]
![image](https://github.com/joaomdmoura/crewAI/assets/115678682/47958b77-f910-41c3-bdfd-8497735a235c)

**Comment by yxl23** [comment]
ok，thanks

**Comment by yxl23** [comment]
The author wants to run this project. Which OpenAI library should I install? I installed 0.28.0, 0.28.1, 1.0.0, 1.31.0, and so on

**Comment by FengXiaoGu** [comment]
the latest version can run
