### ISSUE TITLE
WARNING: Overriding of current TracerProvider is not allowed

### ISSUE THREAD

**Issue by waminos** [crewAIInc/crewAI#675]
hi, im doing a loop and the process get stuck. After the first iterations i get the following warning 'WARNING: Overriding of current TracerProvider is not allowed' and then always stuck at the same moment.

for i in [] :
  inputs = ...
  r = AnalystCrew().crew().kickoff(inputs=inputs)

**Comment by leungmanhin** [comment]
I got this warning as well, it seems to happen if we create more than one crew in the code

**Comment by sathyapriyaa13** [comment]
> I got this warning as well, it seems to happen if we create more than one crew in the code

Hi @leungmanhin how did you manage to sort this issue?

**Comment by luctrate** [comment]
This warning doesn't cause any harm, but in case you want to not see it in you console output.

https://github.com/crewAIInc/crewAI/issues/953#issuecomment-2665075504

**Comment by arnaud0617** [comment]
I also get this warning - not sure how to get rid of it.

**Comment by luctrate** [comment]
@EnggQasim the warning doesn't make it slow, llm execution is just slow on normaly computers ( even with gpu support).
@arnaud0617 
Take a look at https://github.com/crewAIInc/crewAI/issues/953#issuecomment-2665075504 if you don't want to see this warning.
