### ISSUE TITLE
OpenAI assistants

### ISSUE THREAD

**Issue by ezequiroga** [crewAIInc/crewAI#677]
Hi, I would like to know if it possible to configure an `Agent` to use an `OpenAI Assistant`.

Thanks!

**Comment by gadgethome** [comment]
Hi, do you mean a gpt you have built?

**Comment by rapcal** [comment]
You should probably build a custom tool that interacts with the assistant

**Comment by ezequiroga** [comment]
Hi guys, exactly. I have my own Assistant in [OpenAI Platform](https://platform.openai.com/) with an specific domain GPT and I would like to use it by the CrewAI agents, because it has specific domain knowledge.

**Comment by rapcal** [comment]
> Hi guys, exactly. I have my own Assistant in [OpenAI Platform](https://platform.openai.com/) with an specific domain GPT and I would like to use it by the CrewAI agents, because it has specific domain knowledge.

Yes - so just create a custom tool

```python
from crewai_tools import BaseTool

class AssistantChatTool(BaseTool):
    name: str = "Assistant Chat Tool"
    description: str = "Talks to an OpenAI assistant with specific domain knowledge"

    def _run(self, query: str) -> str:
        # your code
```

**Comment by ezequiroga** [comment]
Great, I'll do that.

Thank you!!!
