### ISSUE TITLE
OpenAI usage

### ISSUE THREAD

**Issue by ezequiroga** [crewAIInc/crewAI#678]
Hi, I would like to know how to get information about the OpenAI usage from Agents. I mean, how could I know the tokens used by each Agents.

I need to know that for being able to estimate the cost of the solution.

Thanks!

**Comment by imnotdev25** [comment]
You can use langchain for that.

**Comment by cbruyndoncx** [comment]
I added at the end of the crew run
    result = {{crew_name}}.kickoff()
    metrics={{crew_name}}.usage_metrics

return (result, metrics)

And captured on the calling side like

(result, metrics) = custom_crew.run()
