### ISSUE TITLE
"chromadb 0.4.24 depends on onnxruntime>=1.14.1" on python 3.12.3

### ISSUE THREAD

**Issue by prescriptionlifeline** [crewAIInc/crewAI#679]
When I do `pip3 install crewai` I get this error:

```
ERROR: Cannot install embedchain because these package versions have conflicting dependencies.

The conflict is caused by:
    chromadb 0.4.24 depends on onnxruntime>=1.14.1
    chromadb 0.4.23 depends on onnxruntime>=1.14.1
    chromadb 0.4.22 depends on onnxruntime>=1.14.1
    chromadb 0.4.21 depends on onnxruntime>=1.14.1
    chromadb 0.4.20 depends on onnxruntime>=1.14.1
    chromadb 0.4.19 depends on onnxruntime>=1.14.1
    chromadb 0.4.18 depends on onnxruntime>=1.14.1
    chromadb 0.4.17 depends on onnxruntime>=1.14.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
I'm running Python 3.12.3.

Any ideas?

**Comment by goran-ristic-dev** [comment]
Try picking lower version of chroma.
add lower version of chroma to  requirements.txt and install it first .  Then install crewai

**Comment by prescriptionlifeline** [comment]
Where do I find the requirements.txt? I did `git clone https://github.com/joaomdmoura/crewAI.git` and then `find . -type f -name requirements.txt` in the newly created crewAI directory and it does not appear to be in the repo.

Google suggests that I could create one with `pip freeze` but that appears to only work for something that you've _successfully_ installed and I can't install crewai.

I tried to install chromadb on it's own by doing `pip3 install chromadb` and that installed without issue..

**Comment by prescriptionlifeline** [comment]
So per https://pypi.org/pypi/embedchain/json it looks like embedchain requires chromadb<0.6.0,>=0.5.0 whilst https://pypi.org/pypi/crewai-tools/json requires chromadb<0.5.0,>=0.4.22. So embedchain requires a newer version of chromadb than crewai-tools does, if I'm interpreting this correctly.

Can crewai-tools to be updated to work with new versions of chromadb? Or is the only solution here to fork crewai-tools, create a pypi.org account and profile for my fork and then also fork crewai to use the crewai-tools fork? That seems ridiculous that anyone should have to go to those kinds of lengths to install any Python package.

**Comment by prescriptionlifeline** [comment]
Installing an older version of crewAI worked. `pip3 install crewai==0.22.5`. The latest version of crewAI, however, is 

0.22.5 was released on March 12. Latest version is 0.3.11, released on May 14.

**Comment by prescriptionlifeline** [comment]
I almost wonder if `"graphlib-backport>=1.0.3; python_version < "3.9""` is the issue (from https://pypi.org/pypi/chromadb/json / https://pypi.org/pypi/chromadb/0.5.0/json).

Like if chromadb only works on Python 3.8.x and I'm running 0.12.x then that'd 'cause the problem.

I note that https://pypi.org/pypi/crewai/0.22.5/json doesn't require embedchain whereas https://pypi.org/pypi/crewai/0.30.11/json does.

**Comment by joaomdmoura** [comment]
hey folks, just flagging I'll be looking into this later today :) updating overall dependencies

**Comment by caitlinhudon** [comment]
I was able to get crewai installed using the advice from @prescriptionlifeline above to install an older version via `pip3 install crewai==0.22.5`. I'm running into the same error described above when trying to `pip install 'crewai[tools]==0.22.5'` to access the crewai tools. 

Would love advice if anyone has run into this and solved for it!

**Comment by swimmingkiim** [comment]
In my case, downgrading the Python version to `3.10.14` solved this issue.
