### ISSUE TITLE
Approximate costs for running multi agent workflows?

### ISSUE THREAD

**Issue by nyck33** [crewAIInc/crewAI#691]
https://learn.deeplearning.ai/courses/multi-ai-agent-systems-with-crewai/lesson/16/build-a-crew-to-trailor-job-applications-(code)

If I were to tailor that to scrape job sites, get notified when there are at least five new positions that fit my criteria then automate tailoring the resume, human final check then send off, how much money will it cost for all the api usage?

**Comment by gadgethome** [comment]
You can use langtrace, langfuse etc to calculate the costs of each crew run

https://www.langtrace.ai/
