### ISSUE TITLE
Getting an error  cannot import name 'SubmitEmbeddingRecord' from 'chromadb.types' , when setting memory = True 

### ISSUE THREAD

**Issue by iamyihwa** [crewAIInc/crewAI#700]
Hello, 
Thanks for the great tool! 

I was following through the course of Multi AI agent systems with CrewAI. 
In lesson 9, when I  create crew, when I set memory to True, I am getting following error. (when I set memory to False, the error isn't present anymore. ) 

[course link](https://learn.deeplearning.ai/courses/multi-ai-agent-systems-with-crewai/lesson/9/tools-for-a-customer-outreach-campaign-(code))
```
crew = Crew(
    agents=[sales_rep_agent, 
            lead_sales_rep_agent],
    
    tasks=[lead_profiling_task, 
           personalized_outreach_task],
	
    verbose=2,
	memory=True
)

```

ImportError: cannot import name 'SubmitEmbeddingRecord' from 'chromadb.types' (c:\Users\kiyi2001\Miniconda3\envs\LLM_Learning\Lib\site-packages\chromadb\types.py)

The version of chroma db is '0.5.0'

**Comment by gadgethome** [comment]
Hi, are you using the current version?

crewai                                   0.30.11
crewai-tools                             0.2.6

We are aware of an issue with memory as it defaults to using openai and requests an API key when using a llm.
