### ISSUE TITLE
Question: is agents arg to Crew() redundant 

### ISSUE THREAD

**Issue by wgong** [crewAIInc/crewAI#704]
new to CrewAI, have a question on creating the crew instance:
```
because one could derive `agents` list from `tasks` list, wouldn't the `agents` arg be redundant ?
```

**Comment by lugq1990** [comment]
Based on my understanding to the source code that I think from the main entry of kickoff() will for the full agent list, should be inited like callback and execution env init,  after that, we could just based on the type of jobs like sequential or else, could just use the inited agent to do interactions with other agents or do their own works.

Please just correct me if i'm wrong.

**Comment by greg80303** [comment]
@wgong When you have `allow_delegation=True` in the Agent constructor, the Agent executing a particular task can ask questions or delegate the task to the other agents you provided in the Crew constructor.  So, you have Task-specific agents, then you have global Crew agents that can be used for delegation.
