### ISSUE TITLE
AttributeError: type object 'hnswlib.Index' has no attribute 'file_handle_count'

### ISSUE THREAD

**Issue by RameshAdavi** [crewAIInc/crewAI#705]
While creating a crew , as below:
crew = Crew(
  agents=[support_agent, support_quality_assurance_agent],
  tasks=[inquiry_resolution, quality_assurance_review],
  verbose=2,
  memory=True
)

I get the error as below:
AttributeError: type object 'hnswlib.Index' has no attribute 'file_handle_count'

I am working in a Conda environment, using the following packages: 
 crewai==0.28.8
 crewai_tools==0.1.6
 langchain_community==0.0.29
python==3.11.8
hnswlib==0.8.0
chromadb==0.4.24
chroma-hnswlib==0.7.3

Please help

**Comment by gadgethome** [comment]
Please can you test in the latest version to see if it's still an issue. Thanks

crewai                                   0.30.11
crewai-tools                          0.2.6

**Comment by cws887** [comment]
fdfdd

**Comment by cws887** [comment]
Duplicate of #

**Comment by RameshAdavi** [comment]
> I pip installed  crewai 0.30.11 crewai-tools 0.2.6 as suggested by you. **The issue persists.**

- AttributeError: type object 'hnswlib.Index' has no attribute 'file_handle_count'

**Comment by RameshAdavi** [comment]
I tested with latest versions of crewai and crewai-tools. The issue
persists

**Comment by helenadeus** [comment]
same issue
