### ISSUE TITLE
[Feature Request] Add Human Input Tool like langchain.

### ISSUE THREAD

**Issue by jcoombes** [crewAIInc/crewAI#710]
https://python.langchain.com/v0.1/docs/integrations/tools/human_tools/

Human are AGI so they can certainly be used as a tool to help out AI agent when it is confused.

I think my current pipeline requires too much thought to complete this task successfully, so whilst debugging I would like the model to query a human for answers when it gets stuck.

This might be as simple as asking for an input() from stdin, and then composing this into the prompt?

**Comment by gadgethome** [comment]
Have you tried this? 

https://docs.crewai.com/how-to/Human-Input-on-Execution/

**Comment by jcoombes** [comment]
I saw this and got the impression that it would only ask for input directly before giving the final answer, but this might just be myself reading the docs incorrectly.

I would want it to ask for help the moment it gets stuck and uses the tool, and then potentially do a bunch more task calls or crew member calls afterwards?

**Comment by gadgethome** [comment]
It currently works after each task is completed but only once per task. It may be something that we can improve on in a future release. 

You can also use allow delegation https://docs.crewai.com/core-concepts/Agents/#agent-attributes
