### ISSUE TITLE
JSONSearchTool giving KeyError: 'OPENAI_API_KEY'

### ISSUE THREAD

**Issue by lusabo** [crewAIInc/crewAI#711]
I'm running it on Google Colab, I created a JSON file and uploaded it.

The code is quite simple:

`json_tool = JSONSearchTool(json_path='/content/hotels.json')`

When I am running the code I getting the error:

`KeyError: 'OPENAI_API_KEY'`

Wasn't it supposed to only fetch the information within JSON?

**Comment by gadgethome** [comment]
Hi you will need to override the default embedding that uses openai. Please see 

[https://docs.crewai.com/tools/JSONSearchTool/#usage-examples](url)

**Comment by arnav77** [comment]
@gadgethome why is there a need to override when I want to use ada from openai. It works well with only a language model but gives a key error when embeddings are required.

**Comment by theCyberTech** [comment]
> @gadgethome why is there a need to override when I want to use ada from Openai? The key works as intended when only a language model is required but gives a key error when embeddings are used.

What does your embedding conf look like? If there is anything wrong with it crew will default to gpt4

**Comment by lusabo** [comment]
As my crew is using Llama3, I thought the tool would use what is defined in the crew. I tried to override like below without success, maybe because I don't have the Google API configured. I will do it in a moment.

```python
json_tool = JSONSearchTool(
    json_path='/content/hotels.json', #Is it correct?
    config={
        "llm": {
            "provider": "ollama",
            "config": {
                "model": "llama3"
            },
        },
        "embedder": {
            "provider": "google",
            "config": {
                "model": "models/embedding-001", #what add here?
                "task_type": "retrieval_document" #where can I see task_type?
            },
        },
    }
)
```

**Comment by lusabo** [comment]
Whether or not I configure the API key created in AIStudio, I have the error below.

`os.environ["API_KEY"] = "my_key_comes_here"`


ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x791ecbfd5cc0>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 128, in refresh
    self._retrieve_info(request)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 101, in _retrieve_info
    info = _metadata.get_service_account_info(
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 323, in get_service_account_info
    return get(request, path, params={"recursive": "true"})
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 248, in get
    raise exceptions.TransportError(
google.auth.exceptions.TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x791ecae217e0>)

The above exception was the direct cause of the following exception:

**Comment by lusabo** [comment]
I solved the connection problem with::

```python
import google.generativeai as genai
...
os.environ["API_KEY"] = "The key"
genai.configure(api_key=os.environ['API_KEY'])
```

**Comment by arnav77** [comment]
> I solved the connection problem with::
> 
> ```python
> import google.generativeai as genai
> ...
> os.environ["API_KEY"] = "The key"
> genai.configure(api_key=os.environ['API_KEY'])
> ```

I have used this to authenticate Gemini models but this still doesn't work with crew. Tbh I don't understand how this could be a key error.

**Comment by cbruyndoncx** [comment]
I think this is also related to the known issue that RAG out of the box only works with openai, and there is an embedchain chromate version conflict in v0.30.11
Hoping for next version to fix this, there are some workarounds mentioned here and on the Discord server.

**Comment by lusabo** [comment]
HI all,

Suddenly my example stopped working and now I receive the error:

> ModuleNotFoundError: No module named 'ollama'

I put details on Discord: https://discord.com/channels/1192246288507474000/1252690687804051529
