### ISSUE TITLE
not able to modify the custom embeddings 

### ISSUE THREAD

**Issue by RajvanshMalhotra** [crewAIInc/crewAI#719]
i want to summarize youtube videos using crew so in my tool file. I had picked this code from the documentation 
tool = YoutubeVideoSearchTool(
    config=dict(
        llm=dict(
            provider="ollama", # or google, openai, anthropic, llama2, ...
            config=dict(
                model="llama2",
                # temperature=0.5,
                # top_p=1,
                # stream=true,
            ),
        ),
        embedder=dict(
            provider="google", # or openai, ollama, ...
            config=dict(
                model="models/embedding-001",
                task_type="retrieval_document",
                # title="Embeddings",
            ),
        ),
    )
)
now i amusing google gemini api for this project so i had changed it to yt_tool = YoutubeChannelSearchTool(
    config=dict(
        llm=dict(
            provider="google",  # or google, openai, anthropic, llama2, ...
            config=dict(
                model="gemini-1.5-flash",
                # temperature=0.5,
                # top_p=1,
                # stream=true,
            ),
        ),
        embedder=dict(
            provider="google",  # or openai, ollama, ...
            config=dict(
                model="models/embedding-001",
                task_type="retrieval_document",
                # title="Embeddings",
            ),
        ),
    )
)  now i want to add the chanel name but it dosent work it gives error key error or i directly write youtube_channel_handle="@xyz" in the code it dosent work kindly solve!

**Comment by cbruyndoncx** [comment]
RAG currently v0.30.11 only works out of the box with openai because of chroma embedchain dependencies.

You might be able to work around it if manually installing from github, but issue is known and solution is being worked on.
