### ISSUE TITLE
Problem with using Custom Tool (for making POST API call)

### ISSUE THREAD

**Issue by ADINATHDESAI** [crewAIInc/crewAI#722]
Hello @joaomdmoura , 

I’m working on a small task using CrewAI to make a POST API call. I've set up one agent, task, and tool with a function using the 'requests' library in Python and the Llama3 model on my local machine. The agent recognizes inputs but can't use the tool. Any idea why this might be happening and how I can fix it?

Please let me know if you need more info to help.

Thank you so much!

**Comment by cbruyndoncx** [comment]
Use the Discord server for help and share your code, this might be related to a known issue, or completely specific to your setup. share as much details as you can in the support channel over there and perhaps go through some of the resources first to improve your understanding of crewai.

**Comment by joaomdmoura** [comment]
@ADINATHDESAI Would be ideal if you could share some of the code, specially the code on the custom tool and how you are passing it to the agents

**Comment by ADINATHDESAI** [comment]
Thank you so much, @joaomdmoura, for your prompt response. I truly appreciate your assistance.

I have provided a link to the GitHub repository where all necessary details are mentioned. The JSON file in the code is not real but is similar to the original file. Unfortunately, I can't share the actual URL due to my company's policies. However, the URL for the POST API call is open and does not require a token.
Github Repo Link: https://github.com/ADINATHDESAI/CrewAI/tree/40c587cd5108669c838b6dc08c08aea02ae57ec4

Please let me know if you need more information to help.

Screenshot of Error with llama3:8b model
![image](https://github.com/joaomdmoura/crewAI/assets/155618201/e1fcd4ea-83be-4708-b741-3e6d95162d04)
Similar issue occurred with phi3:mini model. 

Screenshot of Error with llama2:13b model:
![image](https://github.com/joaomdmoura/crewAI/assets/155618201/ba8f5294-9492-4b5a-a03a-b206960439b2)
![image](https://github.com/joaomdmoura/crewAI/assets/155618201/9bd7038e-bfbe-4463-9c43-10c2127460bf)
![image](https://github.com/joaomdmoura/crewAI/assets/155618201/a2892124-c298-423b-b6b4-a42ecc59d435)
![image](https://github.com/joaomdmoura/crewAI/assets/155618201/9a24883e-ef26-4fbe-9a7e-aa3b5829abe1)




LLM used: llama3:8b, phi3:mini, llama2:13b  
System Information:  
Operating System: Windows 10  
RAM: 16GB  
My machine does not have a dedicated GPU.


Could you please tell me what I might be doing wrong and if there is anything I need to change or improve in my code? I am a beginner in this field, and your support would be immensely helpful for me.

Thank you once again for your time and guidance.
