### ISSUE TITLE
Agents are not receiving context from prior tasks

### ISSUE THREAD

**Issue by JustlyAI** [crewAIInc/crewAI#724]
When I create a crew using the `crewai create` setup,
And I add a context parameter to tasks,
The Agents are not able to receive the context from the previous task.

@CrewBase
class StoryProductionCrew:
    """Story production crew"""

    agents_config = "config/agents.yaml"
    tasks_config = "config/tasks.yaml"

    @agent
    def screenwriter(self) -> Agent:
        return Agent(
            config=self.agents_config["screenwriter"],
            tools=[],
            memory=True,
            allow_delegation=False,
            verbose=True,
            max_iter=3,
        )

    @agent
    def creative_director(self) -> Agent:
        return Agent(
            config=self.agents_config["creative_director"],
            tools=[],
            memory=True,
            allow_delegation=False,
            verbose=True,
            max_iter=3,
        )

    @task
    def write_beats(self) -> Task:
        return Task(
            config=self.tasks_config["write_beats"],
            agent=self.screenwriter(),
            async_execution=False,
            human_input=True,
        )

    @task
    def write_script(self) -> Task:
        return Task(
            config=self.tasks_config["write_script"],
            agent=self.screenwriter(),
            async_execution=False,
            context=[self.write_beats()],
        )

    @task
    def write_visual_prompts(self) -> Task:
        return Task(
            config=self.tasks_config["write_visual_prompts"],
            agent=self.creative_director(),
            async_execution=False,
            context=[self.write_beats(), self.write_script()],
        )

   

    @crew
    def crew(self) -> Crew:
        """Creates the story production crew"""
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
        )

**Comment by greg80303** [comment]
See my comment [here](https://github.com/joaomdmoura/crewAI/issues/759#issuecomment-2167150506).
