### ISSUE TITLE
how to trun off the crew share

### ISSUE THREAD

**Issue by hhn12138** [crewAIInc/crewAI#726]
Can the sharing parameters be turned off for privacy reasons? What is the sharing mechanism? If users are not sure about your sharing mechanism, the company will not dare to use your framework

**Comment by gadgethome** [comment]
Hi, its documented here

https://docs.crewai.com/telemetry/Telemetry/

**Comment by smortezah** [comment]
As I understood, it's either basic or complete telemetry sharing. However, @hhn12138 and many others are requesting for "no sharing".

**Comment by JavierCCC** [comment]
+1, it would be great to have a way to disable it. Sometimes you don't even have a chance to post that telemetry data, you have to see how telemetry posting fails everytime you run your crew.
