### ISSUE TITLE
Can not modify the task exported_output result

### ISSUE THREAD

**Issue by BlackLiuJiang** [crewAIInc/crewAI#730]
This is source code of crewai:
"""
        exported_output = self._export_output(result)

        self.output = TaskOutput(
            description=self.description,
            exported_output=exported_output,
            raw_output=result,
        )

        if self.callback:
            self.callback(self.output)

        return exported_output
"""

if I change the value of output.exported_output, it is no user because here just return exported_output instead of self.output.exported_output.  Can you change this logic so that we can modify the task result as the input of next task

**Comment by greg80303** [comment]
The callback is not meant to help you modify the Task output. It is just for debugging or other actions external to the Crew. The `TaskOutput` contains the description of the Task, the raw string output as well as any "exported" (Pydantic or JSON) output.  Purely for use outside the Crew.
