### ISSUE TITLE
Getting Error of Time out when hitting gradio endpoint with Crew Ai

### ISSUE THREAD

**Issue by SyedMuqtasidAli** [crewAIInc/crewAI#731]
@stephenwithav @jonathanmv @shreyaskarnik @baktakt  Hello all, i have created a gradio endpoint using hugging face model " CodeQwen1.5-7B" the gradio endpoint generate successfully but when I try to infrencing my crew agent with gradio endpoint its giving me error :
![image](https://github.com/joaomdmoura/crewAI/assets/107794270/0f5dd28b-d423-4a19-8d94-e89bf41a5d3e)

but at first try its give me error but when I did same prompt second time its show this error. even my gradio endpoint working fine. also I retest my gradio endpoint its working fine. 
I am using colab with latest version of crewai, gradio.
kindly is there anyone who face same issue ?

**Comment by gadgethome** [comment]
Can you test outside of colab and does it work?

**Comment by SyedMuqtasidAli** [comment]
Yes i try on local its not working same issues time out

**Comment by gadgethome** [comment]
Can you upload the full code and exclude any keys?

**Comment by SyedMuqtasidAli** [comment]
Now The main things is when i am running CodeQwen1.5-7B-Chat-AWQ model its
giving timeout error but when i am running any other llama model its giving
output anf working fine i dont know why is this happneing with codeqwen
model
