### ISSUE TITLE
The task cannot output one question and one text box recursively

### ISSUE THREAD

**Issue by inceatakan** [crewAIInc/crewAI#734]
I am trying to develop a 'reading comprehension' app with CrewAI. One task is to generate comprehension questions and output the first question and a text box of the user to enter their answers. Once they enter their answer, the second question etc. Is that possible with CrewAI to generate output dynamically?

The task:

description="You generate basic comprehension questions in French about the text"
                "as to who did what to whom where, when so that you make sure"
                "the reader comprehends the gist of the text."
                "You present questions one by one with a text box under so the learner"
                "enters their answer. Once they enter their answer, you ask the next question",
    expected_output="Basic reading questions in French with a textbox under" 
                    "each question for the learner to enter their answer.",
    tools=[file_read_tool, learner_answers_tool],
    agent=comprehensionQuestionsBasic_agent,

The agent is:

comprehensionQuestionsBasic_agent=Agent(
				role='Question Preparation Specialist',
				goal='Generate basic comprehension questions in French as to who did what to whom where, when.',
				#tools=[file_read_tool],
				backstory='A meticulous reader of French, with an eye for detail.'
                  'Expert in preparing questions to check if the learner understand the basic aspects of the text',
				verbose=True,
				memory=True,
        #llm=llm
			)

The custom tool:

def learner_answers_tool(question: str) -> str:
    """Open a text box for the learner to enter their answer for each question."""
    """Include the questions in the text box so that the learner can enter their"""
    """for each question below the relevant question"""
    # Function logic here
    return "Return the list of questions and the answer to each question"

**Comment by gadgethome** [comment]
Human input currently only works once per task. It is something we are looking at improving in a future release.
