### ISSUE TITLE
Error on Did not find openai_api_key while using crewai with Anthropic claude3

### ISSUE THREAD

**Issue by Microsvuln** [crewAIInc/crewAI#736]
Hi .

I have the following code :

```
os.environ["ANTHROPIC_API_KEY"] = 'MY_API_KEY'


from langchain.llms import anthropic

llm = ChatAnthropic(
    model="claude-3-opus-20240229"
)


search = DuckDuckGoSearchRun()

tools = [
    Tool(
        name="Search",
        func=search.run,
        description="useful for when you search for info"
    )
]
```

But when I run my script I get the following error which is irrelevant as I want to use crewai with claude3 :

` Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error) ` 

Any ideas how to solve this ?

Thanks.

**Comment by gadgethome** [comment]
Are you setting the llm on each of the agents?

# Create an agent and set the LLM
agent = Agent(
    role='Software Engineer',
    goal='Develop a simple Python application',
    backstory='You are a skilled software engineer with experience in Python.',
    verbose=True,
    allow_delegation=False,
    llm=llm,
)

**Comment by Microsvuln** [comment]
Thanks @gadgethome , that's solved the problem .

My other question is, is it possible to use GPT-4, LLAMA3 and Claude3 at the same time ? if so, how to do this ?

Thanks.

**Comment by yuripourre** [comment]
> Thanks @gadgethome , that's solved the problem .
> 
> My other question is, is it possible to use GPT-4, LLAMA3 and Claude3 at the same time ? if so, how to do this ?
> 
> Thanks.

You can assign one LLM to each agent.
