### ISSUE TITLE
Using Anthropic's Claude 3 rather than OpenAI's GPT models

### ISSUE THREAD

**Issue by atulkkwater** [crewAIInc/crewAI#752]
How can I use Anthropic's Claude 3 rather than OpenAI's GPT models? I think, giving this is an open source project, you must have this flexibility of modifying ai calls. So please lemme know how can we do that. Which file I have to change to accommodate the Anthropic.

**Comment by raulduke9119** [comment]
from langchain_anthropic import ChatAnthropic

u need to define the llm :

anthropic_llm = ChatAnthropic(model=modelnameifllmuwannause)

then u need to add llm Parameter to each agent what is equal anthropic_llm

KK Water ***@***.***> schrieb am Di., 11. Juni 2024, 04:35:

**Comment by atulkkwater** [comment]
thanks a lot
