### ISSUE TITLE
AttributeError: 'WrappedClass' object has no attribute

### ISSUE THREAD

**Issue by vmsaif** [crewAIInc/crewAI#765]
```
File "G:\ats_pass_ai\.venv\Lib\site-packages\crewai\project\annotations.py", line 38, in wrapper
    possible_task = getattr(self, task_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WrappedClass' object has no attribute 'generation_task'
PS G:\ats_pass_ai> 
```

This error occurs when trying to use multiple crews with crewai.projects. It is looking for tasks within other crews.

**Comment by hiddenkirby** [comment]
Just passing along this workaround for now. https://github.com/joaomdmoura/crewAI/issues/346

**Comment by joaomdmoura** [comment]
I think we now fixed this in main, would you folks mind double checking this in case?
