### ISSUE TITLE
integration with big data corpus

### ISSUE THREAD

**Issue by phdykd** [crewAIInc/crewAI#773]
Hi, I have tried to integrate big data corpus (all of them txt file and have are very large documents). Each time, I ask a question, it starts to search among all of the files that are in the corpus and can not go directly to the relevant txt where it can dig and find the answer... I am getting this error.. I have tried smenatic reranking, splitting documents, several things, and getting eror....

# Function to split large content into chunks
def split_content(text_content, max_length=10000):
    return [text_content[i:i + max_length] for i in range(0, len(text_content), max_length)]

# Chat with agents
def chat_with_agents(query, processed_texts):
    tasks = []
    agent, task_description = determine_agent(query)

    for file_path, text_content in processed_texts:
        # Split the content into manageable chunks
        content_chunks = split_content(text_content)
        for chunk in content_chunks:
            if len(chunk) > 1048576:
                continue  # Ensure the chunk length is within allowable limits
            tasks.append(create_task_with_content(
                agent,
                task_description,
                chunk,
                file_path  # Pass the file path as the source
            ))

    chat_crew = Crew(
        agents=[agent],
        tasks=tasks,
        process=Process.sequential
    )

    result = chat_crew.kickoff(inputs={'query': query})
    return result

# Example usage
if __name__ == "__main__":
    user_query = "What is the projected growth trajectory for PD-L1 therapy sales from 2022 to 2027, and what percentage of total oncology sales is it expected to represent in 2027?"
    ranked_texts = search_and_rank(user_query, output_directory)
    chat_result = chat_with_agents(user_query, ranked_texts)
    print(chat_result)

BadRequestError: Error code: 400 - {'error': {'message': "Invalid 'messages[0].content': string too long. Expected a string with maximum length 1048576, but got a string with length 1163812 instead.", 'type': 'invalid_request_error', 'param': 'messages[0].content', 'code': 'string_above_max_length'}}

**Comment by greg80303** [comment]
This doesn't seem like the correct way to use CrewAI.  However, I don't see the implementation of `create_task_with_content`.  To be sure, can you post all of your code used to create the tasks?

If you want to do semantic searching or Q/A against a large data corpus, you should be putting that data into a vector store and then having a Tool that does a search of that corpus for chunks relevant to your query.  Those search results are then inserted into the prompt sent to the LLM.  You should not be passing your raw corpus text into the prompts (by creating a task for each chunk).

**Comment by phdykd** [comment]
Thanks for the reply. I have azure ai search index. Do you think would that be logical to use crewai agents as mentioned above integrating with the azure ai index/vectorstore? Thanks again.....

**Comment by greg80303** [comment]
You'll need to define a custom tool.  Either [create your own](https://docs.crewai.com/core-concepts/Tools/#creating-your-own-tools), or maybe check LangChain to see if they have a tool already defined that will use your vector store.  CrewAI [supports LangChain tools natively](https://docs.crewai.com/core-concepts/Tools/#using-langchain-tools).

**Comment by phdykd** [comment]
Hi,
This is the code I created trying to use the azure search index.. i am still getting the same errorr...

import os
import logging
from dotenv import load_dotenv
from azure.search.documents import SearchClient
from azure.search.documents.models import QueryType, SearchMode
from azure.core.credentials import AzureKeyCredential
import crewai
from crewai_tools import BaseTool
from pydantic import BaseModel, Field

# Load environment variables
dotenv_path = '.env'
load_dotenv(dotenv_path=dotenv_path)

class ToolOutput:
    def __init__(self, output=None, error=None):
        self.output = output
        self.error = error

    def __repr__(self):
        return f"ToolOutput(output={self.output}, error={self.error})"

class AzureSearchTool(BaseTool, BaseModel):
    name: str = "AzureSearchTool"
    description: str = "Fetches data from Azure Search service."
    endpoint: str = Field(default=None)
    index_name: str = Field(default=None)
    api_key: str = Field(default=None)
    client: SearchClient = Field(default=None)

    class Config:
        arbitrary_types_allowed = True

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.endpoint = os.getenv('AZURE_SEARCH_ENDPOINT')
        self.index_name = os.getenv('AZURE_SEARCH_INDEX')
        self.api_key = os.getenv('AZURE_SEARCH_KEY')
        self.client = SearchClient(endpoint=self.endpoint, index_name=self.index_name, credential=AzureKeyCredential(self.api_key))

    def search(self, query: str):
        results = self.client.search(
            search_text=query,
            search_mode=SearchMode.All,
            query_type=QueryType.Full
        )
        return results

    def execute(self, query: str) -> ToolOutput:
        try:
            results = self.search(query)
            output = []
            count = 0  # Add a counter to limit the number of results printed
            for result in results:
                if count >= 10:  # Limit to 10 results
                    break
                output.append({
                    'content': result['content'],
                    'filepath': result.get('filepath', None),
                    'title': result.get('title', None),
                    'url': result.get('url', None)
                })
                count += 1
            return ToolOutput(output)
        except Exception as e:
            logging.error(f"Error executing search with query '{query}': {e}")
            return ToolOutput(error=str(e))

    def _run(self, query: str):
        return self.execute(query)

# Create an instance of the tool
azure_search_tool = AzureSearchTool()

# Step 2: Create Agents
# Define agents with specific roles, goals, and tools.

from crewai import Agent

clinical_trial_strategist = Agent(
    role="Clinical Trial Strategist",
    goal="Design and optimize clinical trial strategies to maximize success rates.",
    backstory=(
        "Specializing in clinical trial design, the Clinical Trial Strategist develops innovative strategies "
        "to ensure the efficacy and safety of new treatments, optimizing trial protocols for better outcomes."
    ),
    verbose=True,
    allow_delegation=True,
    tools=[azure_search_tool]
)

pharmaceutical_market_analyst = Agent(
    role="Pharmaceutical Market Analyst",
    goal="Track market trends and predict future opportunities for new treatments.",
    backstory=(
        "Focused on the pharmaceutical industry, the Market Analyst identifies emerging trends, assesses market "
        "needs, and forecasts the potential of new drugs to provide strategic market insights."
    ),
    verbose=True,
    allow_delegation=True,
    tools=[azure_search_tool]
)

chatbot_agent = Agent(
    role="Chatbot Agent",
    goal="Assist users by answering their queries based on available clinical trial data.",
    backstory=(
        "The Chatbot Agent interacts with users to understand their needs, "
        "delegates tasks to the appropriate agents, and provides comprehensive responses."
    ),
    verbose=True,
    allow_delegation=True,
    tools=[azure_search_tool]
)

clinical_data_analyst = Agent(
    role="Clinical Data Analyst",
    goal="Analyze clinical trial data to identify key outcomes and trends.",
    backstory=(
        "The Clinical Data Analyst specializes in examining clinical trial data to uncover significant findings, "
        "trends, and insights, providing comprehensive reports to inform decision-making."
    ),
    verbose=True,
    allow_delegation=True,
    tools=[azure_search_tool]
)

# Step 3: Define Tasks
# Create tasks that agents will perform based on user queries.

from crewai import Task

agent_task_descriptions = {
    'clinical_data_analyst': "Analyze the provided clinical trial data to identify key outcomes and trends. Prepare a comprehensive report highlighting significant findings and their implications. Search Query: {query}",
    'regulatory_affairs_specialist': "Monitor recent regulatory approvals and summarize the key points. Identify any potential impact on ongoing or upcoming trials. Search Query: {query}",
    'clinical_trial_strategist': "Develop and propose optimizations for the current clinical trial strategy. Focus on improving patient recruitment, retention, and overall trial efficiency. Search Query: {query}",
    'pharmaceutical_market_analyst': "Track and analyze market trends related to new treatments. Predict future opportunities and provide a market forecast. Search Query: {query}"
}

def create_task_with_search(agent, description, query):
    return Task(
        description=description.format(query=query),
        expected_output='A detailed report summarizing the findings.',
        tools=[azure_search_tool],
        agent=agent,
    )

# Step 4: Determine Agent Assignment
# Develop a function to assign the appropriate agent to a task based on the query.

def determine_agent(query):
    if "regulatory" in query or "approval" in query:
        return regulatory_affairs_specialist, agent_task_descriptions['regulatory_affairs_specialist']
    elif "trial strategy" in query or "patient recruitment" in query:
        return clinical_trial_strategist, agent_task_descriptions['clinical_trial_strategist']
    elif "market trends" in query or "forecast" in query:
        return pharmaceutical_market_analyst, agent_task_descriptions['pharmaceutical_market_analyst']
    else:
        return clinical_data_analyst, agent_task_descriptions['clinical_data_analyst']

# Step 5: Create and Execute Tasks
# Implement a function to create and execute tasks using the defined agents.

from crewai import Crew, Process
def chat_with_agents(query):
    tasks = []
    agent, task_description = determine_agent(query)

    tasks.append(create_task_with_search(
        agent,
        task_description,
        query
    ))

    chat_crew = Crew(
        agents=[agent],
        tasks=tasks,
        process=Process.sequential
    )

    # Truncate input if it's too long
    truncated_query = query[:1000]  # Adjust this number as needed to ensure it's within the limit

    result = chat_crew.kickoff(inputs={'query': truncated_query})
    return result

# Example usage
if __name__ == "__main__":
    user_query = "What is the projected growth trajectory for PD-L1 therapy sales from 2022 to 2027, and what percentage of total oncology sales is it expected to represent in 2027?"
    
    # Truncate the user query if necessary
    truncated_user_query = user_query[:1000]  # Adjust this number as needed
    
    chat_result = chat_with_agents(truncated_user_query)
    print(chat_result)

**Comment by greg80303** [comment]
I'm not sure your use-case is complex enough for crew.  You actually don't need multiple tasks in your crew, because each of your query types only generates 1 task.  Since each query falls into only one category, you should only be adding one task to your crew -- not all tasks.  So your logic should be updated such that you select your task based on the query, then instantiate the crew with only that single task.  So rather than multiple tasks, you actually have multiple crews, and you kickoff the correct crew based on the query type.

While I think this will work, it is sort of underutilizing CrewAI.  Typical crews have multiple agents and multiple tasks that need to be executed.  Maybe this is just a first revision of your project and you plan to add more functionality later.

**Comment by phdykd** [comment]
Despite to what you said, I should have multiple tasks. I am expecting these taska to be executed...
agent_task_descriptions = {
    'clinical_data_analyst': "Analyze the provided clinical trial data to identify key outcomes and trends. Prepare a comprehensive report highlighting significant findings and their implications. Search Query: {query}",
    'regulatory_affairs_specialist': "Monitor recent regulatory approvals and summarize the key points. Identify any potential impact on ongoing or upcoming trials. Search Query: {query}",
    'clinical_trial_strategist': "Develop and propose optimizations for the current clinical trial strategy. Focus on improving patient recruitment, retention, and overall trial efficiency. Search Query: {query}",
    'pharmaceutical_market_analyst': "Track and analyze market trends related to new treatments. Predict future opportunities and provide a market forecast. Search Query: {query}"
}

**Comment by greg80303** [comment]
From the code you posted earlier, here is how I read it:
 
* You have 4 "types" of queries (regulatory, trial strategy, market trends, clinical data analyst)
* For each query type you have a specific agent (role/backstory) and a specific task description
* In the function `determine_agent()`, you decide which type of query is being provided and you select the appropriate agent and task description
* In the function `create_task_with_search()`, you return a SINGLE task that uses the agent and task description you determined based on the query type
* You append the single task to the empty array (initialized as `tasks = []`) and instantiate your Crew.

Therefore, for every query, you create a new Crew instance with only a single agent and single task.  You may be using all of your tasks across multiple Crew instantiations, but again, each Crew instance has only one task.  This is where I was highlighting the fact that you are not using some of the more powerful features of CrewAI -- that is, to run a Crew with multiple agents in a multi-task workflow.

All that being said, I think the code that you showed me should work.  You are just assigning a single specific agent and a single specific task description based on the contents of the query.  You run a new Crew for each query -- that all makes sense.  Are you still getting an error?

**Comment by iukea1** [comment]
> Despite to what you said, I should have multiple tasks. I am expecting these taska to be executed...
> agent_task_descriptions = {
>     'clinical_data_analyst': "Analyze the provided clinical trial data to identify key outcomes and trends. Prepare a comprehensive report highlighting significant findings and their implications. Search Query: {query}",
>     'regulatory_affairs_specialist': "Monitor recent regulatory approvals and summarize the key points. Identify any potential impact on ongoing or upcoming trials. Search Query: {query}",
>     'clinical_trial_strategist': "Develop and propose optimizations for the current clinical trial strategy. Focus on improving patient recruitment, retention, and overall trial efficiency. Search Query: {query}",
>     'pharmaceutical_market_analyst': "Track and analyze market trends related to new treatments. Predict future opportunities and provide a market forecast. Search Query: {query}"
> }

I don't mean to butt in  or be rude. But your use case is complex enough where you need to use langchain graph and  traditional lang chain ..

The difficulty curve here is much greater, but the rewards are worth it. I'm currently going through 450 GB of raw structured and unstructured data per day 
- auto categorization 
- content meta data labeling 
- going back and forth with 2 models (all local)  to verify reasoning 

- And then I have three vector databases. 

Recommendation 
- get all the GitHub repor, and library documentation  
- use langchain to help you parse and embed all that data. 

Then use that embedded data to help you code your solution. 

Otherwise the skill set for Lang-graph it's just not there yet and publicly available aka blogs.


But we now have a 18 agent system and proper  intra  agent communication and flow is being done with little loss of context between all agent steps. 


In total per day going through 40 million tokens
