### ISSUE TITLE
Official documentation site is down

### ISSUE THREAD

**Issue by leungmanhin** [crewAIInc/crewAI#780]
It has been down for at least a week or so, and still unable to reach, can someone look into it please?

**Comment by AllwynJesu** [comment]
[Docs is ](https://docs.crewai.com/)  still down. Any update on this issue?

**Comment by gadgethome** [comment]
I just tried and seems to be working ok now. Thanks

**Comment by leungmanhin** [comment]
It's still not working as I tried:
```
This site can’t be reachedThe web page at https://docs.crewai.com/ might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED
```

**Comment by AllwynJesu** [comment]
I can access using my mobile, but I'm having trouble accessing on my laptop even after disabling the VPN.

**Comment by leungmanhin** [comment]
Interesting that we all get different results.. and here's what I see from my mobile:
![Screenshot_20240624-144620](https://github.com/joaomdmoura/crewAI/assets/7465047/7d550be2-78d9-4b23-9946-9b1aa37f986c)

**Comment by AllwynJesu** [comment]
Still not working for me 👎
