### ISSUE TITLE
error when using a Groq LLM in a CrewAI setting

### ISSUE THREAD

**Issue by jbdatascience** [crewAIInc/crewAI#783]
I get this error when using a Groq LLM in a CrewAI setting:

BadRequestError                           Traceback (most recent call last)
[<ipython-input-40-062cf5f970f2>](https://localhost:8080/#) in <cell line: 2>()
      1 # Kickoff the Crew
----> 2 result = rag_crew.kickoff(inputs=inputs)

---
26 frames
---
[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in _request(self, cast_to, options, remaining_retries, stream, stream_cls)
   1018 
   1019             log.debug("Re-raising status error")
-> 1020             raise self._make_status_error_from_response(err.response) from None
   1021 
   1022         return self._process_response(

BadRequestError: Error code: 400 - {'error': {'message': 'Organization has been restricted. Please reach out to support if you believe this was in error.', 'type': 'invalid_request_error', 'code': 'organization_restricted'}}

The error is : 
Organization has been restricted

Is it Groq that causes this?

Please support for this error.

**Comment by AIMPED** [comment]
Hi, 

I'm using groq without any problems in combination with crewAI. 

Not sure what's causing the issue. I would guess, that the error message refers to the organisation in your groq account.

**Comment by jbdatascience** [comment]
I have asked Groq itself about, but did not receive an answer yet.

**Comment by monstermax** [comment]
any answer from Groq ?
As soon as I use the api for a while, I have this problem.
However, I respect the quotas per schedule.
I'm tired of creating new accounts.
They don't answer my company registration request.

**Comment by moonpiee** [comment]
> any answer from Groq ? As soon as I use the api for a while, I have this problem. However, I respect the quotas per schedule. I'm tired of creating new accounts. They don't answer my company registration request.

Any update yet? Facing the same issue here, Can't we use groq account for personal projects?
