### ISSUE TITLE
(Not an issue)  how does CrewAI handle SQL and vector database queries?

### ISSUE THREAD

**Issue by james92kj** [crewAIInc/crewAI#789]
Hi everyone, how does CrewAI handle SQL and vector database queries? For example, if I have a query that needs to retrieve records from both a vector database and PostgreSQL, can it specify or let me know that one part of the subquery should go to PostgreSQL and another part should go to the vector database?

**Comment by cccadet** [comment]
Hi!

There is a concept in Langchain that you can apply, which is Routing. There is a series of Langchain that is cool and explains this and other concepts well. Here is the link:

https://www.youtube.com/watch?v=pfpIndq7Fi8

But in CrewAI, I would suggest you create two agents that query different tools, one the vector store and the other the SQL database. Then you would give a task to each agent that queries its respective tool and a third agent that gets the result of the previous two in the context and returns the desired output.

I'm still learning, but it should work well. I'll send you a repository where I did some tests and has examples of built tools.

https://github.com/cccadet/personal-search/blob/main/src/personal_search/tools/books.py
