### ISSUE TITLE
Suddenly stop printing anything during `crew.kickoff()`

### ISSUE THREAD

**Issue by leungmanhin** [crewAIInc/crewAI#791]
It is observed that it would seemingly randomly stop printing the execution log (e.g. the debug, info, etc) all the sudden without giving out any error, which would even cause the normal  Python `print()` to not print anything afterwards. I'm not entirely sure what may be the cause but it seems to associate with the memory feature that we can enable for an agent, i.e. it seems to happen if I have `memory = True` set for my agents.

**Comment by leungmanhin** [comment]
It's still happening using the latest crewai version 0.36.0, and again it seems that it would only happen if I set `memory = True` for my agents.

**Comment by guxi798** [comment]
I'm experiencing the same issue, that `print()` stop outputing anything after `crew.kickoff()`. The issue is still present in the latest crewai` version `0.193.2`. It impacts performance monitoring and token tracking. Can the issue be re-open and someone please help?
