### ISSUE TITLE
PDF Tool and UTc-8

### ISSUE THREAD

**Issue by 1d2g** [crewAIInc/crewAI#825]
Trying to read a PDF and keep running into an "invalid continuation byte" from some searching it seems that this is due to the encoding of the PDF but I haven't found a viable way to get around this. Any help would be greatly appreciated. I'm new to Github so also please let me know if this is the improper way to go about asking this. Thanks!

**Comment by kareemramd** [comment]
In my case, if your Pdf only contain text and tables better convert it to markdown file, its more readable by LLM.

you can use Llamaparse, they give a good job for me and give 1k free pages free daily.
