### ISSUE TITLE
CrewAI Agent Hallucinations

### ISSUE THREAD

**Issue by kareemramd** [crewAIInc/crewAI#826]
Hello,

I've been using CrewAI to put together business proposals. My crew includes a researcher, market analyst, financial analyst, and a few others. I enabled memory for the crew, hoping it would help with the output.

Here's the problem, due to errors and 429, I've had to rerun the crew several times. At first, everything was great. Each agent gave necessarily good answers. But after a few reruns, they started to go off the rails, Im keeping attention to the runtime output carefully. The responses turned into hallucinations, the output completely unusable for me.

How exactly does the memory feature work in CrewAI, tho? I thought it was supposed to improve performance by retaining past information, but it seems like it's causing the agents to degrade instead.

So, what should I do to fix this? Should I change the LLM or resetting the API? Do I need to create a whole new virtual environment? Is there some kind of command line that can clear its memory or choose the memory start point? that whould be so great.

Im using googleai, temp:0.5 fyi.

Any guidance? Thanks!

**Comment by Ricky1975** [comment]
The memory is stored here (on a windows machine). I delete the files when running into issues. Not sure, if this is the best solution :-)
%userprofile%\AppData\Local\CrewAI\

**Comment by kareemramd** [comment]
> The memory is stored here (on a windows machine). I delete the files when running into issues. Not sure, if this is the best solution :-) %userprofile%\AppData\Local\CrewAI\

Mmmm there's only empty \src folder inside.
