### ISSUE TITLE
ImportError: cannot import name 'SerperDevTool' from 'crewai_tools'

### ISSUE THREAD

**Issue by anandbhaskaran** [crewAIInc/crewAI#829]
![Screenshot 2024-06-28 at 14 57 57](https://github.com/joaomdmoura/crewAI/assets/6847984/59b439b7-050b-4dfd-9af2-05c3885532d2)

Python version: 3.12.0
Computer: Mac M1

Same as: https://github.com/joaomdmoura/crewAI/issues/762

**Comment by DragonAngel** [comment]
try with:
from crewai_tools import SerperDevTool, BrowserbaseLoadTool, EXASearchTool

**Comment by JamesStallings** [comment]
Yeah, now I need a BROWSERBASE_API_KEY.

Thing is, I'm trying to keep all this local, via ollama, with only opensource models and resources.

**Comment by syedaameena** [comment]
ImportError: cannot import name 'NL2SQLTool' from 'crewai_tools'  I am also similar issue with other tool
