### ISSUE TITLE
how to achieve detailed logging of an agent's actions in CrewAI?

### ISSUE THREAD

**Issue by TailinZhou** [crewAIInc/crewAI#833]
I had set Verbose=True when defining my Customizable Agents and also set Verbose=True in Crew function. The saved log I obtained only includes the output of each task, but not the action log of each agent. how to achieve detailed logging of an agent's actions in the log file?

**Comment by brunooseliero** [comment]
Hey TailinZhou!

Maybe this can help you:

| **Step Callback** *(optional)* | A function that is called after each step of the agent. This can be used to log the agent's actions or to perform other operations. It will overwrite the crew `step_callback`.                                                               |

**Comment by TailinZhou** [comment]
> Hey TailinZhou!
> 
> Maybe this can help you:
> 
> | **Step Callback** _(optional)_ | A function that is called after each step of the agent. This can be used to log the agent's actions or to perform other operations. It will overwrite the crew `step_callback`. |

Many thanks for your information. I had thought that the log file would automatically save the agent action history when setting Verbose=True in the Crew function. I would overwrite the crew `step_callback`. |Thanks again.

**Comment by casualcomputer** [comment]
> Hey TailinZhou!
> 
> Maybe this can help you:
> 
> | **Step Callback** _(optional)_ | A function that is called after each step of the agent. This can be used to log the agent's actions or to perform other operations. It will overwrite the crew `step_callback`. |

Please give an example. step_callback logs the results as crew objects, not what's in the console. I couldn't extract the crew objects as raw texts.

**Comment by Dyegoy9** [comment]
Hey TailinZhou! 

You can save the log using the parameter output_log_file = True in the Crew, as the following:

    crew = Crew(
        agents=[researcher],
        tasks=[ research_task],
        verbose=True,
        output_log_file = True,  ----->> Here to save the logs into a txt file.
        process=Process.sequential
    )

**Comment by Dadiya-Harsh-wappnet** [comment]
@brunooseliero, @TailinZhou, @casualcomputer , @sundaresan-r , @Dyegoy9 
How can I redirect or integrate CrewAI agent logs into standard application log files?
