### ISSUE TITLE
Dependancy conflict with langchain_anthropic and crewai (langchain dep)

### ISSUE THREAD

**Issue by theCyberTech** [crewAIInc/crewAI#837]
when trying to install langchain_anthropic, the following dependency conflict occurs:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-community 0.0.38 requires langchain-core<0.2.0,>=0.1.52, but you have langchain-core 0.2.10 which is incompatible.
langchain 0.1.20 requires langchain-core<0.2.0,>=0.1.52, but you have langchain-core 0.2.10 which is incompatible.`

**Environment**

Python version: 3.11.9
pip version: 24.1.1
Operating System: MacOS

**Steps to Reproduce**

1. Install crewai to a new venv 
`pip install crewai`
2. Install langchain_anthropic
`pip install langchain-anthropic`

**Expected Behavior**
The packages should install without conflicts, or pip should be able to resolve the dependency issues automatically.

The langchain version(s) set by crewai is around ~2 months behind now I think this is going too start causing issues more and more

**Comment by joaomdmoura** [comment]
Currently updating it should be done in a few hours :)
