### ISSUE TITLE
Error while : from crewai import Agent,Task , Crew

### ISSUE THREAD

**Issue by mohammad-gh009** [crewAIInc/crewAI#846]
PackageNotFoundError: No package metadata was found for embedchain.

**Comment by robsonc** [comment]
I received the same error after install a totally fresh new project

**Comment by strnad** [comment]
same problem here, for me it was possible to fix it by installing embedchain from git instead of wheel.
`pip install git+https://github.com/joaomdmoura/embedchain.git`

**Comment by gromag** [comment]
Fresh new project, new python environment, first I got the same `embedchain` problem then after manually pip installing it I got:

```
from crewai_tools import SerperDevTool, BrowserbaseTool, ExaSearchTool
ImportError: cannot import name 'BrowserbaseTool' from 'crewai_tools'
```

I'm using the getting starter code:

```
import os

from langchain.llms import OpenAI
from crewai import Agent
from crewai_tools import SerperDevTool, BrowserbaseTool, ExaSearchTool
from dotenv import load_dotenv

load_dotenv("cred.env")

assert os.environ["OPENAI_API_KEY"] is not None
assert os.environ["SERPER_API_KEY"] is not None

search_tool = SerperDevTool()
browser_tool = BrowserbaseTool()
exa_search_tool = ExaSearchTool()

# Creating a senior researcher agent with advanced configurations
researcher = Agent(
    role="Senior Researcher",
    goal="Uncover groundbreaking technologies in {topic}",
    backstory=(
        "Driven by curiosity, you're at the forefront of innovation, "
        "eager to explore and share knowledge that could change the world."
    ),
    memory=True,
    verbose=True,
    allow_delegation=False,
    tools=[search_tool, browser_tool],
    allow_code_execution=False,  # New attribute for enabling code execution
    max_iter=15,  # Maximum number of iterations for task execution
    max_rpm=100,  # Maximum requests per minute
    max_execution_time=3600,  # Maximum execution time in seconds
    system_template="Your custom system template here",  # Custom system template
    prompt_template="Your custom prompt template here",  # Custom prompt template
    response_template="Your custom response template here",  # Custom response template
)

# Creating a writer agent with custom tools and specific configurations
writer = Agent(
    role="Writer",
    goal="Narrate compelling tech stories about {topic}",
    backstory=(
        "With a flair for simplifying complex topics, you craft engaging "
        "narratives that captivate and educate, bringing new discoveries to light."
    ),
    verbose=True,
    allow_delegation=False,
    memory=True,
    tools=[exa_search_tool],
    function_calling_llm=OpenAI(
        model_name="gpt-3.5-turbo"
    ),  # Separate LLM for function calling
)

# Setting a specific manager agent
manager = Agent(
    role="Manager",
    goal="Ensure the smooth operation and coordination of the team",
    verbose=True,
    backstory=(
        "As a seasoned project manager, you excel in organizing "
        "tasks, managing timelines, and ensuring the team stays on track."
    ),
    allow_code_execution=True,  # Enable code execution for the manager
)
```

**Comment by LarsAC** [comment]
The dependency in crewai is on embedchain-crewai, but that does not solve the problem for me either.

**Comment by gromag** [comment]
Did anyone get anywhere with this?

**Comment by JamesStallings** [comment]
This is giving me a problem as well; it seems that the tools depend on embedchain, which depends on langchain; so if you are using langchain-community,  installing embed chain replaces it with langchain and breaks a lot of stuff....and you won't be able to install the tools.

**Comment by joaomdmoura** [comment]
Hey folks thanks for reporting the error, what version are you using? He did see this bug but should be fixed on 0.35.8

**Comment by joaomdmoura** [comment]
in the new version we will update the dependency with them as well to sue new versions

**Comment by wasimsafdar** [comment]
Does anybody know how to solve it? I followed and got this error.

**Comment by JamesStallings** [comment]
My experience is no one here is really interested in having crewai work
with locally hosted LLM, and these calls for assistance are barely
acknowledged and the issue quickly closed.

My recommendation is to simply code your agents from scratch using python
or node. It isn’t near as difficult as I had thought.

The roughest part is the prompt engineering, and if you can’t get that part
right, all the agentic frameworks in the world wont help.

have a look at e.g., AICodeKing https://www.youtube.com/watch?v=w5of-CBDlfU
(that might be an ‘I’ instead of an ‘l’)

Don’t let the smarminess or the sybthesized voice track throw you off -
there’s meat on them bones.

ॐ♲ ♥ ☸☮ ☯☰☶☯☮ ☸ ♥ ♲ॐ
KI5SMN

**Comment by joaomdmoura** [comment]
Hey folks, if there is an on going problem we would love to help, we do need more information though to be able to replicated it, like the versions being used, logs and some code to help us to it.

**Comment by joaomdmoura** [comment]
We update embedchain in the latest versions so this should be gone, but lmk if I'm wrong

**Comment by wasimsafdar** [comment]
I am following this tutorial. https://lablab.ai/t/mastering-ai-content-creation-leveraging-llama-3-and-groq-api. Is this error related to "langchain_groq"? I also installed embedchain but I do not know how to update imports.

**Comment by windbd** [comment]
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by syedaameena** [comment]
cannot import name 'NL2SQLTool' from 'crewai_tools' I am facing this issue in mac OS, python version 3.11 
crewai==0.22.5
crewai-tools==0.0.15

**Comment by devudit** [comment]
Install the following module with Google Colab
!pip install -q google-generativeai
