### ISSUE TITLE
Save the conversation in cache

### ISSUE THREAD

**Issue by vinhpd-miagi** [crewAIInc/crewAI#850]
from crewai.tools.cache_tools import CacheTools
from crewai.agents.cache import CacheHandler

def __init__(self):
        self.cache_handler = CacheHandler()
        self.cache_tool = CacheTools(cache_handler=self.cache_handler)

        cached_result = self.cache_handler.read("system_generator", title)
        if cached_result:
            self.logger.info('Using cached result')
            return cl.run_sync(cl.Message(content=cached_result).send())

       self.cache_handler.add("system_generator", title, result)

I added it to the agent but currently it is only saved in the conversation. I want it to be retrieved when I open a new chat.

**Comment by theCyberTech** [comment]
So just to summarise:

You would like to have the cache handler save the tools output in a more persistent manner?

**Comment by vinhpd-miagi** [comment]
Yes, that's what I need

**Comment by C130187** [comment]
any updates please?
