### ISSUE TITLE
Is it possible to kickoff another crew using an already running crew?

### ISSUE THREAD

**Issue by rohanprasadsap** [crewAIInc/crewAI#857]
I am currently trying build a project which involves multiple crews. In my project design there is a orchestrator level crew which takes in a user query and then kicks off the respective crew for that user request. Keep in mind that this user request might involve multiple crews.

How can I implement this?

**Comment by theCyberTech** [comment]
Is there an issue here? Questions like this are better placed on our Discord server as this is for actual issues/bugs

**Comment by fatmind** [comment]
> Is there an issue here? Questions like this are better placed on our Discord server as this is for actual issues/bugs

Logically, an agent can also be a team without being tied to a specific role, allowing for self-nesting. 
However, I don't recommend supporting this natively in the project. Instead, @rohanprasadsap can implement an agent at the top level to coordinate between multiple crews on their own.
