### ISSUE TITLE
json output format error

### ISSUE THREAD

**Issue by snailfrying** [crewAIInc/crewAI#900]
When CrewAI uses output_file to save as a JSON file, I also use the output_json convention for a specific format. However, the output file consistently contains the characters ```json *```, which cause parsing errors. If not corrected, it directly reports an error and switches to raw output.

**Comment by theCyberTech** [comment]
Can you submit an example of your code + example issue so we can reproduce

**Comment by snailfrying** [comment]
When crew calls this tool, the data parameter is too long and truncation can occur, resulting in an error in saving the data
"""
   @tool("存储json数据为文件")
    def save_json(data, filename):
        """
        将数据存储为JSON文件。
        参数:
        data (dict): 要存储的数据字典，必须传入整体数据，不可传入变量。
        filename (str): 存储数据的文件名。
        """
        filename = re.sub(r'"', '', filename)
        try:
            with open(filename, 'w', encoding='utf-8') as file:
                json.dump(data, file, ensure_ascii=False, indent=4)
            print(f"数据已成功存储到 {filename}")
        except Exception as e:
            print(f"存储数据时出错: {e}")
"""

**Comment by priyanshshah23** [comment]
When CrewAI utilizes output_file to store data in JSON format, adherence to the output_json convention ensures structured output. However, the generated file repeatedly contains unintended $ characters, leading to parsing failures. If these anomalies are not addressed, the system promptly triggers an error and defaults to raw output mode. What to do to overcome this issue of JSON not being generated properly?
