### ISSUE TITLE
Surprise Trip Example: troubles with the installation

### ISSUE THREAD

**Issue by cesaregerbino** [crewAIInc/crewAI#906]
I'm trying to use CrewAI on a Ubuntu 22.04 virtual machine with python 3.10.12

The installation works fine with the default project using Open AI Key and Serper Key.

Now I'd like to try to use the Surprise Trip example: I've cloned the project 

![image](https://github.com/joaomdmoura/crewAI/assets/4707083/dfea7b33-5a7a-487d-838c-ec443f8df5c4)

Trying the command `poetry lock` (on my virtual machine the poetry version is 1.112 ...), the error is

![image](https://github.com/joaomdmoura/crewAI/assets/4707083/3b97c43d-485e-4272-a0ea-7acf5bf32db5)

Any suggestions will be appreciated.

Thank you in advance!!

**Comment by gadgethome** [comment]
Can you try deleting the lock file and then retrying
