### ISSUE TITLE
Parameters passed  to building the crew using the Crew() API

### ISSUE THREAD

**Issue by simith** [crewAIInc/crewAI#913]
As per the API, when building a crew a List of Tasks needs to be provided, however, tasks <--> Agent are already associated when Task is created, see below, An Agent should know what tasks it has to do,

**Agent**
volleyball_enthusiast = Agent(
    role="Volleyball Enthusiast",
    goal="Help with general tasks related to Volleyball",
    backstory="An ex volleyball player with 20 years of game experience, including organising games",
    tools=[search_tool]
)

**Task**
rebounding_wall_building_task = Task(
    description="Plan for building a wall for practicing volleyball at university college",
    **agent=volleyball_enthusiast,**
    expected_output="provide a JSON output so that my web application can process it"
)

**Crew**
volleyball_club_crew = Crew(
    agents=[volleyball_enthusiast],
    **_tasks=[rebounding_wall_building_task],_**
    process=Process.sequential
)

Are tasks really required to be passed during a Crew creation, as a Crew is just a list of Agents or Crew members, and providing tasks in the Crew creation API does not make much sense to me? Please let me know.

**Comment by theCyberTech** [comment]
Which API are you referring to here?

**Comment by simith** [comment]
volleyball_club_crew = Crew(
agents=[volleyball_enthusiast],
tasks=[rebounding_wall_building_task],
process=Process.sequential
)

The above crew creation API, Does the above one need to be passed Tasks? As we are already passing Agent references to Tasks
