### ISSUE TITLE
when use the `crew.kickoff_for_each(inputs=datasets)`; the agent will lost the `llm` property .

### ISSUE THREAD

**Issue by lipengming** [crewAIInc/crewAI#922]
when use the `crew.kickoff_for_each(inputs=datasets)`; the agent will lost the `llm` property .

![image](https://github.com/user-attachments/assets/4fe8e4cb-a932-409b-adf6-b6801d170106)

![image](https://github.com/user-attachments/assets/3a131b4d-f9f4-482d-bf59-17ce4a91ea23)

**Comment by gadgethome** [comment]
Hi, please upgrade to the latest release as the issue has now been fixed. thanks

crewai                                   0.36.0
crewai-tools                          0.4.8
