### ISSUE TITLE
[Improvement] Token Usage Metrics for Each Task

### ISSUE THREAD

**Issue by lirockyzhang** [crewAIInc/crewAI#933]
Is it possible to get a usage metrics for each task after execution instead of a total usage metrics after the whole crew finished running? It would be easier to target tasks that use excessive tokens and reduce their token usage.

**Comment by ChaseRichardsonGit** [comment]
+1 - Would love this feature as well.  What I'm getting out of crew usage metrics and Langtrace aren't adding up and being able to solve it out via individual task metrics would be ideal.

**Comment by Hisan-007** [comment]
i'm still looking for a solution, did anyone find anything, or a work around perhaps ?
