### ISSUE TITLE
The annoying warning while using the Huggingfaces' models

### ISSUE THREAD

**Issue by mohammad-gh009** [crewAIInc/crewAI#953]
I am using hugging face models and each time I kick off a crew I receive the following warning it is very annoying especially in loops(I can't properly keep track of my work in loops !!!!)

WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /root/.cache/huggingface/token
Login successful

**Comment by theCyberTech** [comment]
Can you advise what version you are using of crewai / crewai-tools

**Comment by mohammad-gh009** [comment]
> Can you advise what version you are using of crewai / crewai-tools
@theCyberTech 
The latest version! ----> crewai 0.36.1

**Comment by NurzihanReya** [comment]
Facing the same issue, have you found any solution?

**Comment by luctrate** [comment]
If you want to ignore the TracerProvider Warning Message add the following to your main.py


    import logging

    class IgnoreTracerProviderFilter(logging.Filter):
        def filter(self, record):
            return record.getMessage() != 'Overriding of current TracerProvider is not allowed'
            
    logging.getLogger('opentelemetry.trace').addFilter(IgnoreTracerProviderFilter())



This message gets logged from the opentelemetry module. 
The method gets called whenever a new crew is getting started, not directly but over the "litellm" implementation. 

opentelemetry.trace module


    def _set_tracer_provider(tracer_provider: TracerProvider, log: bool) -> None:
        def set_tp() -> None:
            global _TRACER_PROVIDER  # pylint: disable=global-statement
            _TRACER_PROVIDER = tracer_provider
    
        did_set = _TRACER_PROVIDER_SET_ONCE.do_once(set_tp)
    
        if log and not did_set:
            logger.warning("Overriding of current TracerProvider is not allowed")
