### ISSUE TITLE
Controlling Search Tool Usage

### ISSUE THREAD

**Issue by allisonc2323** [crewAIInc/crewAI#956]
Hi! I had a question on if it's possible to control tool usage in CrewAI, particularly where it concerns SerpAPI. 

Can you construct an agent such that it only calls a SerpAPI Google Search tool if **absolutely necessary**? I am running into the issue where the LLM will automatically default to calling this SerpAPI Google Search tool, even if the LLM is capable of responding to it without using a tool. I want to restrict these tools such that it is the agent's last resort. 

Thanks.

**Comment by theCyberTech** [comment]
What do you define as "absolutely necessary"? You can maybe try updating your tasks prompts to guide it accordingly
