### ISSUE TITLE
ModuleNotFoundError: No module named 'crewai'

### ISSUE THREAD

**Issue by michaelcutajar1995** [crewAIInc/crewAI#959]
Used Poetry, updated the versions, checked through all the tasks that were recommended from previous people that his bug, yet still nothing. 

<img width="1118" alt="Screenshot 2024-07-17 at 23 30 12" src="https://github.com/user-attachments/assets/a240426f-b19c-4104-89cb-e5059301e6bb">

**Comment by theCyberTech** [comment]
How are you running your Crew?

**Comment by michaelcutajar1995** [comment]
Thanks for your response, I'm running my CrewAI setup as follows:

1. **Execution Method**: I use `Poetry` to manage dependencies and run my script with `poetry run python main.py`.
2. **Virtual Environment**: I have created a virtual environment using `Poetry`, which is specified in the `pyproject.toml` file; 3.11.7 
3. **Deployment Environment**: Currently, I'm running everything locally on my machine.
4. **Dependency Management**: Dependencies are managed through `Poetry`, and all versions are specified in `pyproject.toml`

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
crewai = "0.36.1"
langchain-core = "0.2.20"
langchain-community = "0.2.7"
langsmith = "0.1.88"
langchain-openai = "0.1.17"
python-dotenv = "^1.0.1"

5. **Configuration and Setup**: Environment variables are set using a `.env` file and loaded with `python-dotenv`.

Please let me know if you need more specific details on any of these points.

**Comment by USTAADCOM** [comment]
Hi @michaelcutajar1995 do you found any solution? Because I am facing the issue and I perfectly install crewai package but it still showing not found crewai error.

**Comment by michaelcutajar1995** [comment]
Nothing for the moment, waiting for the crewai guys. How are you running?

**Comment by alphaveneno** [comment]
Something doesn't look right.

It does not appear you are actually in the poetry virtual environment, unless it is called 'running'

at the terminal:
poetry  shell

if the name of your project is "markdown-validation-crew", prompt should now look something like this:
(markdown-validation-crew-py3.11) ra@debian:~/Documents/webCourses/TDD/crew_ai/crew_ai4/crew-ai-local-llm-main/crewai-simple-example$ 

at the terminal, now you can enter:
poetry run python main.py

**Comment by michaelcutajar1995** [comment]
Worked
