### ISSUE TITLE
Iteration on Agent with human feedback , if human does not approve it should not move forward

### ISSUE THREAD

**Issue by rshah1990** [crewAIInc/crewAI#960]
I am experimenting with a sample code that involves a team of two AI agents.

Agent 1 is responsible for crafting a travel blog,

Agent 2 then transforms this blog into a Facebook post, essentially creating marketing content.

My intention is to ensure that Agent 1 collaborates with a human user for revisions until the user approves the content. Only then should it be passed on to Agent 2 for further re-purposing. I initially believed that incorporating human feedback would facilitate this process. However, despite specifying this in the task description, the process advances to the next step without the desired iteration.

**Comment by theCyberTech** [comment]
How have you se up your tasks? did you enable as per the docs?

https://docs.crewai.com/how-to/Human-Input-on-Execution/

**Comment by rshah1990** [comment]
Yes I did as per documentation, also I have specifically mentioned in the task description do not move forward without human approving it, it takes input modifies the output but move to next agent. It does not iterate on the same step.
