### ISSUE TITLE
Parameter to disable Pydantic

### ISSUE THREAD

**Issue by EilidhMc** [crewAIInc/crewAI#977]
Is it possible to turn the pydantic validation off? whilst it is a useful feature for ensuring your pipeline doesn't fail in prod; when you are in the prompt testing and iteration stage it is such a struggle to experiment with different prompts without having to refactor other parts of the code.

There needs to be a little bit of flexibility. When you are first setting up project you need to be able to explore the data with the agents and see what capabilities there are before you start refining and restricting the outputs.

I find I need to build a simple LLM chain using OpenAI's api to get my prompts; but if I am doing that anyway then there is no point in using crew ai and I can go build it myself

**Comment by joaomdmoura** [comment]
Hey @EilidhMc I would love to understand more the issues you're experiencing, I'm not sure I follow, you mean the outputs of the crew being pydantic models?

**Comment by theCyberTech** [comment]
Hi @EilidhMc 

Unfortunately, we cannot help you further until you provide some expansion on your issue. We will close this for now.

**Comment by red-scorp** [comment]
Example:

`Traceback (most recent call last):
  File "C:\Dev\Test\Devyan\main.py", line 67, in <module>
    result = crew.run()
             ^^^^^^^^^^
  File "C:\Dev\Test\Devyan\main.py", line 40, in run
    architect_agent = agents.architect_agent(architect_tools)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\Test\Devyan\agents.py", line 16, in architect_agent
    return Agent(
           ^^^^^^
  File "C:\Dev\Test\Devyan\venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Agent
tools
  Value error, Invalid tool type: <class 'langchain_community.tools.ddg_search.tool.DuckDuckGoSearchRun'>. Tool must be an instance of BaseTool or an object with 'name', 'func', and 'description' attributes. [type=value_error, input_value=[DuckDuckGoSearchRun(api_...at 0x000001B64784B380>)], input_type=list]
    For further information visit https://errors.pydantic.dev/2.10/v/value_error`
