### ISSUE TITLE
Meaning of Entering new CrewAgentExecutor chain... and Finished chain.

### ISSUE THREAD

**Issue by pradeepdev-1995** [crewAIInc/crewAI#978]
I have three agents and their corresponding tasks. While running the crew() function, I noticed multiple verbose messages in the console, such as "Entering new CrewAgentExecutor chain..." and "Finished chain."
What does this mean? each agent will generate each  "Entering new CrewAgentExecutor chain..." and "Finished chain." in the time of their trigger.?

**Comment by theCyberTech** [comment]
Every time tyour agents start a task your will see "Entering new CrewAgentExecutor chain..."

CrewAgentExecutor chain is these of step the agent will take to complete its task
As there is no issue I will resolve this, your  moe than welcome to ask these sort of questions in Discrd
