### ISSUE TITLE
Accessing input information in Tools

### ISSUE THREAD

**Issue by dudesparsh** [crewAIInc/crewAI#986]
I'm trying to pass input information to my crew, but I'm having trouble accessing those inputs within my tool.

When I include these variables in prompts (goals) or descriptions, I can access them inside my tool. However, I prefer not to mention the inputs in the prompt and still access them within my tool.

Can anyone suggest the right way to achieve this? Do agents or tasks have the functionality to take inputs or configurations directly, similar to how it's done in crews?

Thank you.

**Comment by carvalhorafael** [comment]
+1
