### ISSUE TITLE
what does training a crew do under the hood?

### ISSUE THREAD

**Issue by pluiez** [crewAIInc/crewAI#988]

**Comment by theCyberTech** [comment]
Setup:
- Enables human input for all tasks

Training Loop:

- Runs tasks for a set number of iterations
- After each task, asks for human feedback
- Stores initial output, feedback, and improved output

Evaluation:
- Analyzes the differences between initial and improved outputs
- Generates suggestions for improvement

- Storage:
- Saves improvement suggestions for each agent

 Application: 
- In future runs, adds these suggestions to task prompts
- Guides agents to produce better results based on past feedback
