### ISSUE TITLE
self.crew is None

### ISSUE THREAD

**Issue by snailfrying** [crewAIInc/crewAI#991]
CrewAgentExeutor self.crew is None. Causes the memory build to fail
code:
   if self.crew and self.crew.memory:
              contextual_memory = ContextualMemory(
                  self.crew._short_term_memory,
                  self.crew._long_term_memory,
                  self.crew._entity_memory,
              )
              memory = contextual_memory.build_context_for_task(task, context)
              if memory.strip() != "":
                  task_prompt += self.i18n.slice("memory").format(memory=memory)

**Comment by theCyberTech** [comment]
Hi @snailfrying 
Can you share how you're configuring your crew to generate this issue?
